/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.resources.records.requests;

import ai.vectros.core.ObjectMappers;
import ai.vectros.resources.records.types.LookupRecordsRequestOrder;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = LookupRecordsRequest.Builder.class
)
public final class LookupRecordsRequest {
  private final String type;

  private final String field;

  private final Optional<String> value;

  private final Optional<String> from;

  private final Optional<String> to;

  private final Optional<String> prefix;

  private final Optional<String> startFrom;

  private final Optional<Long> limit;

  private final Optional<String> includePayload;

  private final Optional<LookupRecordsRequestOrder> order;

  private final Map<String, Object> additionalProperties;

  private LookupRecordsRequest(String type, String field, Optional<String> value,
      Optional<String> from, Optional<String> to, Optional<String> prefix,
      Optional<String> startFrom, Optional<Long> limit, Optional<String> includePayload,
      Optional<LookupRecordsRequestOrder> order, Map<String, Object> additionalProperties) {
    this.type = type;
    this.field = field;
    this.value = value;
    this.from = from;
    this.to = to;
    this.prefix = prefix;
    this.startFrom = startFrom;
    this.limit = limit;
    this.includePayload = includePayload;
    this.order = order;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The record type to look up, e.g. <code>intake_form</code>.
   */
  @JsonProperty("type")
  public String getType() {
    return type;
  }

  /**
   * @return The name of the lookup field to match on, as declared on the type's schema.
   */
  @JsonProperty("field")
  public String getField() {
    return field;
  }

  /**
   * @return Exact value to match. Mutually exclusive with <code>from</code>/<code>to</code> and <code>prefix</code>. Rejected for a sensitive field — use <code>POST /v1/records/lookup</code> instead so the value is not exposed in the URL.
   */
  @JsonProperty("value")
  public Optional<String> getValue() {
    return value;
  }

  /**
   * @return Inclusive lower bound of a range lookup (requires <code>to</code>; non-sensitive fields only). Mutually exclusive with <code>value</code> and <code>prefix</code>.
   */
  @JsonProperty("from")
  public Optional<String> getFrom() {
    return from;
  }

  /**
   * @return Inclusive upper bound of a range lookup (requires <code>from</code>).
   */
  @JsonProperty("to")
  public Optional<String> getTo() {
    return to;
  }

  /**
   * @return Prefix to match (string, non-sensitive fields only). Mutually exclusive with <code>value</code> and <code>from</code>/<code>to</code>.
   */
  @JsonProperty("prefix")
  public Optional<String> getPrefix() {
    return prefix;
  }

  /**
   * @return Pagination cursor. Pass the <code>nextCursor</code> from the previous page; omit it for the first page.
   */
  @JsonProperty("startFrom")
  public Optional<String> getStartFrom() {
    return startFrom;
  }

  /**
   * @return Maximum number of records to return per page. Allowed range 1–100; defaults to 20.
   */
  @JsonProperty("limit")
  public Optional<Long> getLimit() {
    return limit;
  }

  /**
   * @return Set to <code>true</code> to include each record's full payload, rehydrating any payloads stored externally (capped per page). Defaults to <code>false</code>, which returns only the indexed projection.
   */
  @JsonProperty("includePayload")
  public Optional<String> getIncludePayload() {
    return includePayload;
  }

  /**
   * @return Sort direction by the field's value: <code>asc</code> (ascending, the default) or <code>desc</code> (descending).
   */
  @JsonProperty("order")
  public Optional<LookupRecordsRequestOrder> getOrder() {
    return order;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof LookupRecordsRequest && equalTo((LookupRecordsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(LookupRecordsRequest other) {
    return type.equals(other.type) && field.equals(other.field) && value.equals(other.value) && from.equals(other.from) && to.equals(other.to) && prefix.equals(other.prefix) && startFrom.equals(other.startFrom) && limit.equals(other.limit) && includePayload.equals(other.includePayload) && order.equals(other.order);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.field, this.value, this.from, this.to, this.prefix, this.startFrom, this.limit, this.includePayload, this.order);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TypeStage builder() {
    return new Builder();
  }

  public interface TypeStage {
    /**
     * <p>The record type to look up, e.g. <code>intake_form</code>.</p>
     */
    FieldStage type(@NotNull String type);

    Builder from(LookupRecordsRequest other);
  }

  public interface FieldStage {
    /**
     * <p>The name of the lookup field to match on, as declared on the type's schema.</p>
     */
    _FinalStage field(@NotNull String field);
  }

  public interface _FinalStage {
    LookupRecordsRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Exact value to match. Mutually exclusive with <code>from</code>/<code>to</code> and <code>prefix</code>. Rejected for a sensitive field — use <code>POST /v1/records/lookup</code> instead so the value is not exposed in the URL.</p>
     */
    _FinalStage value(Optional<String> value);

    _FinalStage value(String value);

    /**
     * <p>Inclusive lower bound of a range lookup (requires <code>to</code>; non-sensitive fields only). Mutually exclusive with <code>value</code> and <code>prefix</code>.</p>
     */
    _FinalStage from(Optional<String> from);

    _FinalStage from(String from);

    /**
     * <p>Inclusive upper bound of a range lookup (requires <code>from</code>).</p>
     */
    _FinalStage to(Optional<String> to);

    _FinalStage to(String to);

    /**
     * <p>Prefix to match (string, non-sensitive fields only). Mutually exclusive with <code>value</code> and <code>from</code>/<code>to</code>.</p>
     */
    _FinalStage prefix(Optional<String> prefix);

    _FinalStage prefix(String prefix);

    /**
     * <p>Pagination cursor. Pass the <code>nextCursor</code> from the previous page; omit it for the first page.</p>
     */
    _FinalStage startFrom(Optional<String> startFrom);

    _FinalStage startFrom(String startFrom);

    /**
     * <p>Maximum number of records to return per page. Allowed range 1–100; defaults to 20.</p>
     */
    _FinalStage limit(Optional<Long> limit);

    _FinalStage limit(Long limit);

    /**
     * <p>Set to <code>true</code> to include each record's full payload, rehydrating any payloads stored externally (capped per page). Defaults to <code>false</code>, which returns only the indexed projection.</p>
     */
    _FinalStage includePayload(Optional<String> includePayload);

    _FinalStage includePayload(String includePayload);

    /**
     * <p>Sort direction by the field's value: <code>asc</code> (ascending, the default) or <code>desc</code> (descending).</p>
     */
    _FinalStage order(Optional<LookupRecordsRequestOrder> order);

    _FinalStage order(LookupRecordsRequestOrder order);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TypeStage, FieldStage, _FinalStage {
    private String type;

    private String field;

    private Optional<LookupRecordsRequestOrder> order = Optional.empty();

    private Optional<String> includePayload = Optional.empty();

    private Optional<Long> limit = Optional.empty();

    private Optional<String> startFrom = Optional.empty();

    private Optional<String> prefix = Optional.empty();

    private Optional<String> to = Optional.empty();

    private Optional<String> from = Optional.empty();

    private Optional<String> value = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(LookupRecordsRequest other) {
      type(other.getType());
      field(other.getField());
      value(other.getValue());
      from(other.getFrom());
      to(other.getTo());
      prefix(other.getPrefix());
      startFrom(other.getStartFrom());
      limit(other.getLimit());
      includePayload(other.getIncludePayload());
      order(other.getOrder());
      return this;
    }

    /**
     * <p>The record type to look up, e.g. <code>intake_form</code>.</p>
     * <p>The record type to look up, e.g. <code>intake_form</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("type")
    public FieldStage type(@NotNull String type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    /**
     * <p>The name of the lookup field to match on, as declared on the type's schema.</p>
     * <p>The name of the lookup field to match on, as declared on the type's schema.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("field")
    public _FinalStage field(@NotNull String field) {
      this.field = Objects.requireNonNull(field, "field must not be null");
      return this;
    }

    /**
     * <p>Sort direction by the field's value: <code>asc</code> (ascending, the default) or <code>desc</code> (descending).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage order(LookupRecordsRequestOrder order) {
      this.order = Optional.ofNullable(order);
      return this;
    }

    /**
     * <p>Sort direction by the field's value: <code>asc</code> (ascending, the default) or <code>desc</code> (descending).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "order",
        nulls = Nulls.SKIP
    )
    public _FinalStage order(Optional<LookupRecordsRequestOrder> order) {
      this.order = order;
      return this;
    }

    /**
     * <p>Set to <code>true</code> to include each record's full payload, rehydrating any payloads stored externally (capped per page). Defaults to <code>false</code>, which returns only the indexed projection.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage includePayload(String includePayload) {
      this.includePayload = Optional.ofNullable(includePayload);
      return this;
    }

    /**
     * <p>Set to <code>true</code> to include each record's full payload, rehydrating any payloads stored externally (capped per page). Defaults to <code>false</code>, which returns only the indexed projection.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "includePayload",
        nulls = Nulls.SKIP
    )
    public _FinalStage includePayload(Optional<String> includePayload) {
      this.includePayload = includePayload;
      return this;
    }

    /**
     * <p>Maximum number of records to return per page. Allowed range 1–100; defaults to 20.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage limit(Long limit) {
      this.limit = Optional.ofNullable(limit);
      return this;
    }

    /**
     * <p>Maximum number of records to return per page. Allowed range 1–100; defaults to 20.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "limit",
        nulls = Nulls.SKIP
    )
    public _FinalStage limit(Optional<Long> limit) {
      this.limit = limit;
      return this;
    }

    /**
     * <p>Pagination cursor. Pass the <code>nextCursor</code> from the previous page; omit it for the first page.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage startFrom(String startFrom) {
      this.startFrom = Optional.ofNullable(startFrom);
      return this;
    }

    /**
     * <p>Pagination cursor. Pass the <code>nextCursor</code> from the previous page; omit it for the first page.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "startFrom",
        nulls = Nulls.SKIP
    )
    public _FinalStage startFrom(Optional<String> startFrom) {
      this.startFrom = startFrom;
      return this;
    }

    /**
     * <p>Prefix to match (string, non-sensitive fields only). Mutually exclusive with <code>value</code> and <code>from</code>/<code>to</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage prefix(String prefix) {
      this.prefix = Optional.ofNullable(prefix);
      return this;
    }

    /**
     * <p>Prefix to match (string, non-sensitive fields only). Mutually exclusive with <code>value</code> and <code>from</code>/<code>to</code>.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "prefix",
        nulls = Nulls.SKIP
    )
    public _FinalStage prefix(Optional<String> prefix) {
      this.prefix = prefix;
      return this;
    }

    /**
     * <p>Inclusive upper bound of a range lookup (requires <code>from</code>).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage to(String to) {
      this.to = Optional.ofNullable(to);
      return this;
    }

    /**
     * <p>Inclusive upper bound of a range lookup (requires <code>from</code>).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "to",
        nulls = Nulls.SKIP
    )
    public _FinalStage to(Optional<String> to) {
      this.to = to;
      return this;
    }

    /**
     * <p>Inclusive lower bound of a range lookup (requires <code>to</code>; non-sensitive fields only). Mutually exclusive with <code>value</code> and <code>prefix</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage from(String from) {
      this.from = Optional.ofNullable(from);
      return this;
    }

    /**
     * <p>Inclusive lower bound of a range lookup (requires <code>to</code>; non-sensitive fields only). Mutually exclusive with <code>value</code> and <code>prefix</code>.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "from",
        nulls = Nulls.SKIP
    )
    public _FinalStage from(Optional<String> from) {
      this.from = from;
      return this;
    }

    /**
     * <p>Exact value to match. Mutually exclusive with <code>from</code>/<code>to</code> and <code>prefix</code>. Rejected for a sensitive field — use <code>POST /v1/records/lookup</code> instead so the value is not exposed in the URL.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage value(String value) {
      this.value = Optional.ofNullable(value);
      return this;
    }

    /**
     * <p>Exact value to match. Mutually exclusive with <code>from</code>/<code>to</code> and <code>prefix</code>. Rejected for a sensitive field — use <code>POST /v1/records/lookup</code> instead so the value is not exposed in the URL.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "value",
        nulls = Nulls.SKIP
    )
    public _FinalStage value(Optional<String> value) {
      this.value = value;
      return this;
    }

    @java.lang.Override
    public LookupRecordsRequest build() {
      return new LookupRecordsRequest(type, field, value, from, to, prefix, startFrom, limit, includePayload, order, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
