/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.resources.documents.requests;

import ai.vectros.core.ObjectMappers;
import ai.vectros.resources.documents.types.FileUploadRequestIndexMode;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = FileUploadRequest.Builder.class
)
public final class FileUploadRequest {
  private final String fileName;

  private final String fileType;

  private final Optional<FileUploadRequestIndexMode> indexMode;

  private final Optional<String> folderId;

  private final Optional<Map<String, Object>> payload;

  private final Optional<String> schemaId;

  private final Optional<String> userId;

  private final Optional<String> orgId;

  private final Optional<String> clientId;

  private final Optional<String> externalId;

  private final Map<String, Object> additionalProperties;

  private FileUploadRequest(String fileName, String fileType,
      Optional<FileUploadRequestIndexMode> indexMode, Optional<String> folderId,
      Optional<Map<String, Object>> payload, Optional<String> schemaId, Optional<String> userId,
      Optional<String> orgId, Optional<String> clientId, Optional<String> externalId,
      Map<String, Object> additionalProperties) {
    this.fileName = fileName;
    this.fileType = fileType;
    this.indexMode = indexMode;
    this.folderId = folderId;
    this.payload = payload;
    this.schemaId = schemaId;
    this.userId = userId;
    this.orgId = orgId;
    this.clientId = clientId;
    this.externalId = externalId;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Original file name, including its extension. Used as the document title when no separate title is provided.
   */
  @JsonProperty("fileName")
  public String getFileName() {
    return fileName;
  }

  /**
   * @return MIME type of the file being uploaded. Used to set the correct Content-Type on the stored object.
   */
  @JsonProperty("fileType")
  public String getFileType() {
    return fileType;
  }

  /**
   * @return Indexing strategy applied after the file is processed and its text is extracted. <code>HYBRID</code> runs both BM25 keyword and dense-vector semantic indexing (recommended). <code>SEMANTIC</code> indexes only as dense vectors. <code>TEXT</code> indexes only with BM25. <code>NONE</code> is store-only (archival): the file is still uploaded and its text extracted, but it is not search-indexed — retrievable by id/download and structured-field lookup only. Optional: omit to inherit the bound schema's default index mode. If neither this field nor the schema specifies one, the request is rejected. When both are set, this per-file value wins.
   */
  @JsonProperty("indexMode")
  public Optional<FileUploadRequestIndexMode> getIndexMode() {
    return indexMode;
  }

  /**
   * @return ID of the folder in which to place this document. Omit to use your account's default root folder.
   */
  @JsonProperty("folderId")
  public Optional<String> getFolderId() {
    return folderId;
  }

  /**
   * @return The document's structured data, as a flat key/value object. When <code>schemaId</code> is set, declared fields are validated against the schema and its lookup fields become directly queryable (matching record and text-ingest behavior); undeclared keys pass through as free-form and are searchable via the <code>filters</code> parameter on <code>POST /v1/search</code>.
   */
  @JsonProperty("payload")
  public Optional<Map<String, Object>> getPayload() {
    return payload;
  }

  /**
   * @return Optional ID of a record schema to bind this document to. When set, the document's <code>payload</code> is validated against the schema and its lookup fields become directly queryable (matching record and text-ingest behavior).
   */
  @JsonProperty("schemaId")
  public Optional<String> getSchemaId() {
    return schemaId;
  }

  /**
   * @return Owning user ID — the Vectros-assigned UUID of a user in your account. Optional. With an API key, sets the document's owner explicitly. With a scoped token, must match the token's identity claim (if set) or fall within its data scope.
   */
  @JsonProperty("userId")
  public Optional<String> getUserId() {
    return userId;
  }

  /**
   * @return Owning organization ID — the Vectros-assigned UUID of an organization in your account. Optional. With an API key, sets the document's owning organization explicitly. With a scoped token, must match the token's identity claim (if set) or fall within its data scope.
   */
  @JsonProperty("orgId")
  public Optional<String> getOrgId() {
    return orgId;
  }

  /**
   * @return Associated client ID — the Vectros-assigned UUID of a client in your account. Optional. With an API key, sets the document's client explicitly. With a scoped token, must match the token's identity claim (if set) or fall within its data scope.
   */
  @JsonProperty("clientId")
  public Optional<String> getClientId() {
    return clientId;
  }

  /**
   * @return Stable, caller-supplied identifier for this document. Optional. Immutable after create. Unique within your account and context: initiating an upload again with the same <code>externalId</code> returns the same document plus a fresh presigned URL (idempotent — no duplicate), and it is the key other records use to reference this one. Max 256 characters.
   */
  @JsonProperty("externalId")
  public Optional<String> getExternalId() {
    return externalId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof FileUploadRequest && equalTo((FileUploadRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(FileUploadRequest other) {
    return fileName.equals(other.fileName) && fileType.equals(other.fileType) && indexMode.equals(other.indexMode) && folderId.equals(other.folderId) && payload.equals(other.payload) && schemaId.equals(other.schemaId) && userId.equals(other.userId) && orgId.equals(other.orgId) && clientId.equals(other.clientId) && externalId.equals(other.externalId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.fileName, this.fileType, this.indexMode, this.folderId, this.payload, this.schemaId, this.userId, this.orgId, this.clientId, this.externalId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static FileNameStage builder() {
    return new Builder();
  }

  public interface FileNameStage {
    /**
     * <p>Original file name, including its extension. Used as the document title when no separate title is provided.</p>
     */
    FileTypeStage fileName(@NotNull String fileName);

    Builder from(FileUploadRequest other);
  }

  public interface FileTypeStage {
    /**
     * <p>MIME type of the file being uploaded. Used to set the correct Content-Type on the stored object.</p>
     */
    _FinalStage fileType(@NotNull String fileType);
  }

  public interface _FinalStage {
    FileUploadRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Indexing strategy applied after the file is processed and its text is extracted. <code>HYBRID</code> runs both BM25 keyword and dense-vector semantic indexing (recommended). <code>SEMANTIC</code> indexes only as dense vectors. <code>TEXT</code> indexes only with BM25. <code>NONE</code> is store-only (archival): the file is still uploaded and its text extracted, but it is not search-indexed — retrievable by id/download and structured-field lookup only. Optional: omit to inherit the bound schema's default index mode. If neither this field nor the schema specifies one, the request is rejected. When both are set, this per-file value wins.</p>
     */
    _FinalStage indexMode(Optional<FileUploadRequestIndexMode> indexMode);

    _FinalStage indexMode(FileUploadRequestIndexMode indexMode);

    /**
     * <p>ID of the folder in which to place this document. Omit to use your account's default root folder.</p>
     */
    _FinalStage folderId(Optional<String> folderId);

    _FinalStage folderId(String folderId);

    /**
     * <p>The document's structured data, as a flat key/value object. When <code>schemaId</code> is set, declared fields are validated against the schema and its lookup fields become directly queryable (matching record and text-ingest behavior); undeclared keys pass through as free-form and are searchable via the <code>filters</code> parameter on <code>POST /v1/search</code>.</p>
     */
    _FinalStage payload(Optional<Map<String, Object>> payload);

    _FinalStage payload(Map<String, Object> payload);

    /**
     * <p>Optional ID of a record schema to bind this document to. When set, the document's <code>payload</code> is validated against the schema and its lookup fields become directly queryable (matching record and text-ingest behavior).</p>
     */
    _FinalStage schemaId(Optional<String> schemaId);

    _FinalStage schemaId(String schemaId);

    /**
     * <p>Owning user ID — the Vectros-assigned UUID of a user in your account. Optional. With an API key, sets the document's owner explicitly. With a scoped token, must match the token's identity claim (if set) or fall within its data scope.</p>
     */
    _FinalStage userId(Optional<String> userId);

    _FinalStage userId(String userId);

    /**
     * <p>Owning organization ID — the Vectros-assigned UUID of an organization in your account. Optional. With an API key, sets the document's owning organization explicitly. With a scoped token, must match the token's identity claim (if set) or fall within its data scope.</p>
     */
    _FinalStage orgId(Optional<String> orgId);

    _FinalStage orgId(String orgId);

    /**
     * <p>Associated client ID — the Vectros-assigned UUID of a client in your account. Optional. With an API key, sets the document's client explicitly. With a scoped token, must match the token's identity claim (if set) or fall within its data scope.</p>
     */
    _FinalStage clientId(Optional<String> clientId);

    _FinalStage clientId(String clientId);

    /**
     * <p>Stable, caller-supplied identifier for this document. Optional. Immutable after create. Unique within your account and context: initiating an upload again with the same <code>externalId</code> returns the same document plus a fresh presigned URL (idempotent — no duplicate), and it is the key other records use to reference this one. Max 256 characters.</p>
     */
    _FinalStage externalId(Optional<String> externalId);

    _FinalStage externalId(String externalId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements FileNameStage, FileTypeStage, _FinalStage {
    private String fileName;

    private String fileType;

    private Optional<String> externalId = Optional.empty();

    private Optional<String> clientId = Optional.empty();

    private Optional<String> orgId = Optional.empty();

    private Optional<String> userId = Optional.empty();

    private Optional<String> schemaId = Optional.empty();

    private Optional<Map<String, Object>> payload = Optional.empty();

    private Optional<String> folderId = Optional.empty();

    private Optional<FileUploadRequestIndexMode> indexMode = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(FileUploadRequest other) {
      fileName(other.getFileName());
      fileType(other.getFileType());
      indexMode(other.getIndexMode());
      folderId(other.getFolderId());
      payload(other.getPayload());
      schemaId(other.getSchemaId());
      userId(other.getUserId());
      orgId(other.getOrgId());
      clientId(other.getClientId());
      externalId(other.getExternalId());
      return this;
    }

    /**
     * <p>Original file name, including its extension. Used as the document title when no separate title is provided.</p>
     * <p>Original file name, including its extension. Used as the document title when no separate title is provided.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("fileName")
    public FileTypeStage fileName(@NotNull String fileName) {
      this.fileName = Objects.requireNonNull(fileName, "fileName must not be null");
      return this;
    }

    /**
     * <p>MIME type of the file being uploaded. Used to set the correct Content-Type on the stored object.</p>
     * <p>MIME type of the file being uploaded. Used to set the correct Content-Type on the stored object.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("fileType")
    public _FinalStage fileType(@NotNull String fileType) {
      this.fileType = Objects.requireNonNull(fileType, "fileType must not be null");
      return this;
    }

    /**
     * <p>Stable, caller-supplied identifier for this document. Optional. Immutable after create. Unique within your account and context: initiating an upload again with the same <code>externalId</code> returns the same document plus a fresh presigned URL (idempotent — no duplicate), and it is the key other records use to reference this one. Max 256 characters.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage externalId(String externalId) {
      this.externalId = Optional.ofNullable(externalId);
      return this;
    }

    /**
     * <p>Stable, caller-supplied identifier for this document. Optional. Immutable after create. Unique within your account and context: initiating an upload again with the same <code>externalId</code> returns the same document plus a fresh presigned URL (idempotent — no duplicate), and it is the key other records use to reference this one. Max 256 characters.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "externalId",
        nulls = Nulls.SKIP
    )
    public _FinalStage externalId(Optional<String> externalId) {
      this.externalId = externalId;
      return this;
    }

    /**
     * <p>Associated client ID — the Vectros-assigned UUID of a client in your account. Optional. With an API key, sets the document's client explicitly. With a scoped token, must match the token's identity claim (if set) or fall within its data scope.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage clientId(String clientId) {
      this.clientId = Optional.ofNullable(clientId);
      return this;
    }

    /**
     * <p>Associated client ID — the Vectros-assigned UUID of a client in your account. Optional. With an API key, sets the document's client explicitly. With a scoped token, must match the token's identity claim (if set) or fall within its data scope.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "clientId",
        nulls = Nulls.SKIP
    )
    public _FinalStage clientId(Optional<String> clientId) {
      this.clientId = clientId;
      return this;
    }

    /**
     * <p>Owning organization ID — the Vectros-assigned UUID of an organization in your account. Optional. With an API key, sets the document's owning organization explicitly. With a scoped token, must match the token's identity claim (if set) or fall within its data scope.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage orgId(String orgId) {
      this.orgId = Optional.ofNullable(orgId);
      return this;
    }

    /**
     * <p>Owning organization ID — the Vectros-assigned UUID of an organization in your account. Optional. With an API key, sets the document's owning organization explicitly. With a scoped token, must match the token's identity claim (if set) or fall within its data scope.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "orgId",
        nulls = Nulls.SKIP
    )
    public _FinalStage orgId(Optional<String> orgId) {
      this.orgId = orgId;
      return this;
    }

    /**
     * <p>Owning user ID — the Vectros-assigned UUID of a user in your account. Optional. With an API key, sets the document's owner explicitly. With a scoped token, must match the token's identity claim (if set) or fall within its data scope.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage userId(String userId) {
      this.userId = Optional.ofNullable(userId);
      return this;
    }

    /**
     * <p>Owning user ID — the Vectros-assigned UUID of a user in your account. Optional. With an API key, sets the document's owner explicitly. With a scoped token, must match the token's identity claim (if set) or fall within its data scope.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "userId",
        nulls = Nulls.SKIP
    )
    public _FinalStage userId(Optional<String> userId) {
      this.userId = userId;
      return this;
    }

    /**
     * <p>Optional ID of a record schema to bind this document to. When set, the document's <code>payload</code> is validated against the schema and its lookup fields become directly queryable (matching record and text-ingest behavior).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage schemaId(String schemaId) {
      this.schemaId = Optional.ofNullable(schemaId);
      return this;
    }

    /**
     * <p>Optional ID of a record schema to bind this document to. When set, the document's <code>payload</code> is validated against the schema and its lookup fields become directly queryable (matching record and text-ingest behavior).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "schemaId",
        nulls = Nulls.SKIP
    )
    public _FinalStage schemaId(Optional<String> schemaId) {
      this.schemaId = schemaId;
      return this;
    }

    /**
     * <p>The document's structured data, as a flat key/value object. When <code>schemaId</code> is set, declared fields are validated against the schema and its lookup fields become directly queryable (matching record and text-ingest behavior); undeclared keys pass through as free-form and are searchable via the <code>filters</code> parameter on <code>POST /v1/search</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage payload(Map<String, Object> payload) {
      this.payload = Optional.ofNullable(payload);
      return this;
    }

    /**
     * <p>The document's structured data, as a flat key/value object. When <code>schemaId</code> is set, declared fields are validated against the schema and its lookup fields become directly queryable (matching record and text-ingest behavior); undeclared keys pass through as free-form and are searchable via the <code>filters</code> parameter on <code>POST /v1/search</code>.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "payload",
        nulls = Nulls.SKIP
    )
    public _FinalStage payload(Optional<Map<String, Object>> payload) {
      this.payload = payload;
      return this;
    }

    /**
     * <p>ID of the folder in which to place this document. Omit to use your account's default root folder.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage folderId(String folderId) {
      this.folderId = Optional.ofNullable(folderId);
      return this;
    }

    /**
     * <p>ID of the folder in which to place this document. Omit to use your account's default root folder.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "folderId",
        nulls = Nulls.SKIP
    )
    public _FinalStage folderId(Optional<String> folderId) {
      this.folderId = folderId;
      return this;
    }

    /**
     * <p>Indexing strategy applied after the file is processed and its text is extracted. <code>HYBRID</code> runs both BM25 keyword and dense-vector semantic indexing (recommended). <code>SEMANTIC</code> indexes only as dense vectors. <code>TEXT</code> indexes only with BM25. <code>NONE</code> is store-only (archival): the file is still uploaded and its text extracted, but it is not search-indexed — retrievable by id/download and structured-field lookup only. Optional: omit to inherit the bound schema's default index mode. If neither this field nor the schema specifies one, the request is rejected. When both are set, this per-file value wins.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage indexMode(FileUploadRequestIndexMode indexMode) {
      this.indexMode = Optional.ofNullable(indexMode);
      return this;
    }

    /**
     * <p>Indexing strategy applied after the file is processed and its text is extracted. <code>HYBRID</code> runs both BM25 keyword and dense-vector semantic indexing (recommended). <code>SEMANTIC</code> indexes only as dense vectors. <code>TEXT</code> indexes only with BM25. <code>NONE</code> is store-only (archival): the file is still uploaded and its text extracted, but it is not search-indexed — retrievable by id/download and structured-field lookup only. Optional: omit to inherit the bound schema's default index mode. If neither this field nor the schema specifies one, the request is rejected. When both are set, this per-file value wins.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "indexMode",
        nulls = Nulls.SKIP
    )
    public _FinalStage indexMode(Optional<FileUploadRequestIndexMode> indexMode) {
      this.indexMode = indexMode;
      return this;
    }

    @java.lang.Override
    public FileUploadRequest build() {
      return new FileUploadRequest(fileName, fileType, indexMode, folderId, payload, schemaId, userId, orgId, clientId, externalId, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
