/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.resources.documents.requests;

import ai.vectros.core.ObjectMappers;
import ai.vectros.types.DocumentRequest;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = IngestDocumentRequest.Builder.class
)
public final class IngestDocumentRequest {
  private final Optional<Boolean> upsert;

  private final Optional<Boolean> allowClear;

  private final DocumentRequest body;

  private final Map<String, Object> additionalProperties;

  private IngestDocumentRequest(Optional<Boolean> upsert, Optional<Boolean> allowClear,
      DocumentRequest body, Map<String, Object> additionalProperties) {
    this.upsert = upsert;
    this.allowClear = allowClear;
    this.body = body;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return When <code>true</code>, if a document with the same <code>externalId</code> already exists its content is overwritten (the submitted <code>payload</code>, <code>title</code>, and — when supplied — <code>text</code> are applied and the version is bumped) instead of being returned unchanged; the immutable <code>externalId</code>, <code>schemaId</code>, <code>indexMode</code>, and ownership are never changed. Defaults to <code>false</code>. Requires the <code>documents:u</code> scope in addition to <code>documents:c</code>.
   */
  @JsonProperty("upsert")
  public Optional<Boolean> getUpsert() {
    return upsert;
  }

  /**
   * @return Only relevant with <code>?upsert=true</code>, which overwrites an existing document as a full replacement. If the submitted request omits (or sends as null) a stored field that a list or lookup response returns only as an indexed projection (a large document whose payload is stored externally), the overwrite is rejected unless you set <code>allowClear=true</code> to confirm that clearing those fields is intended. Use PATCH to update without clearing omitted fields. Defaults to <code>false</code>.
   */
  @JsonProperty("allowClear")
  public Optional<Boolean> getAllowClear() {
    return allowClear;
  }

  @JsonProperty("body")
  public DocumentRequest getBody() {
    return body;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof IngestDocumentRequest && equalTo((IngestDocumentRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(IngestDocumentRequest other) {
    return upsert.equals(other.upsert) && allowClear.equals(other.allowClear) && body.equals(other.body);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.upsert, this.allowClear, this.body);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static BodyStage builder() {
    return new Builder();
  }

  public interface BodyStage {
    _FinalStage body(@NotNull DocumentRequest body);

    Builder from(IngestDocumentRequest other);
  }

  public interface _FinalStage {
    IngestDocumentRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>When <code>true</code>, if a document with the same <code>externalId</code> already exists its content is overwritten (the submitted <code>payload</code>, <code>title</code>, and — when supplied — <code>text</code> are applied and the version is bumped) instead of being returned unchanged; the immutable <code>externalId</code>, <code>schemaId</code>, <code>indexMode</code>, and ownership are never changed. Defaults to <code>false</code>. Requires the <code>documents:u</code> scope in addition to <code>documents:c</code>.</p>
     */
    _FinalStage upsert(Optional<Boolean> upsert);

    _FinalStage upsert(Boolean upsert);

    /**
     * <p>Only relevant with <code>?upsert=true</code>, which overwrites an existing document as a full replacement. If the submitted request omits (or sends as null) a stored field that a list or lookup response returns only as an indexed projection (a large document whose payload is stored externally), the overwrite is rejected unless you set <code>allowClear=true</code> to confirm that clearing those fields is intended. Use PATCH to update without clearing omitted fields. Defaults to <code>false</code>.</p>
     */
    _FinalStage allowClear(Optional<Boolean> allowClear);

    _FinalStage allowClear(Boolean allowClear);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements BodyStage, _FinalStage {
    private DocumentRequest body;

    private Optional<Boolean> allowClear = Optional.empty();

    private Optional<Boolean> upsert = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(IngestDocumentRequest other) {
      upsert(other.getUpsert());
      allowClear(other.getAllowClear());
      body(other.getBody());
      return this;
    }

    @java.lang.Override
    @JsonSetter("body")
    public _FinalStage body(@NotNull DocumentRequest body) {
      this.body = Objects.requireNonNull(body, "body must not be null");
      return this;
    }

    /**
     * <p>Only relevant with <code>?upsert=true</code>, which overwrites an existing document as a full replacement. If the submitted request omits (or sends as null) a stored field that a list or lookup response returns only as an indexed projection (a large document whose payload is stored externally), the overwrite is rejected unless you set <code>allowClear=true</code> to confirm that clearing those fields is intended. Use PATCH to update without clearing omitted fields. Defaults to <code>false</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage allowClear(Boolean allowClear) {
      this.allowClear = Optional.ofNullable(allowClear);
      return this;
    }

    /**
     * <p>Only relevant with <code>?upsert=true</code>, which overwrites an existing document as a full replacement. If the submitted request omits (or sends as null) a stored field that a list or lookup response returns only as an indexed projection (a large document whose payload is stored externally), the overwrite is rejected unless you set <code>allowClear=true</code> to confirm that clearing those fields is intended. Use PATCH to update without clearing omitted fields. Defaults to <code>false</code>.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "allowClear",
        nulls = Nulls.SKIP
    )
    public _FinalStage allowClear(Optional<Boolean> allowClear) {
      this.allowClear = allowClear;
      return this;
    }

    /**
     * <p>When <code>true</code>, if a document with the same <code>externalId</code> already exists its content is overwritten (the submitted <code>payload</code>, <code>title</code>, and — when supplied — <code>text</code> are applied and the version is bumped) instead of being returned unchanged; the immutable <code>externalId</code>, <code>schemaId</code>, <code>indexMode</code>, and ownership are never changed. Defaults to <code>false</code>. Requires the <code>documents:u</code> scope in addition to <code>documents:c</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage upsert(Boolean upsert) {
      this.upsert = Optional.ofNullable(upsert);
      return this;
    }

    /**
     * <p>When <code>true</code>, if a document with the same <code>externalId</code> already exists its content is overwritten (the submitted <code>payload</code>, <code>title</code>, and — when supplied — <code>text</code> are applied and the version is bumped) instead of being returned unchanged; the immutable <code>externalId</code>, <code>schemaId</code>, <code>indexMode</code>, and ownership are never changed. Defaults to <code>false</code>. Requires the <code>documents:u</code> scope in addition to <code>documents:c</code>.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "upsert",
        nulls = Nulls.SKIP
    )
    public _FinalStage upsert(Optional<Boolean> upsert) {
      this.upsert = upsert;
      return this;
    }

    @java.lang.Override
    public IngestDocumentRequest build() {
      return new IngestDocumentRequest(upsert, allowClear, body, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
