/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.resources.identity.requests;

import ai.vectros.core.ObjectMappers;
import ai.vectros.types.EntityRequest;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpdateEntityRequest.Builder.class
)
public final class UpdateEntityRequest {
  private final EntityRequest body;

  private final Map<String, Object> additionalProperties;

  private UpdateEntityRequest(EntityRequest body, Map<String, Object> additionalProperties) {
    this.body = body;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("body")
  public EntityRequest getBody() {
    return body;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpdateEntityRequest && equalTo((UpdateEntityRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpdateEntityRequest other) {
    return body.equals(other.body);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.body);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static BodyStage builder() {
    return new Builder();
  }

  public interface BodyStage {
    _FinalStage body(@NotNull EntityRequest body);

    Builder from(UpdateEntityRequest other);
  }

  public interface _FinalStage {
    UpdateEntityRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements BodyStage, _FinalStage {
    private EntityRequest body;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(UpdateEntityRequest other) {
      body(other.getBody());
      return this;
    }

    @java.lang.Override
    @JsonSetter("body")
    public _FinalStage body(@NotNull EntityRequest body) {
      this.body = Objects.requireNonNull(body, "body must not be null");
      return this;
    }

    @java.lang.Override
    public UpdateEntityRequest build() {
      return new UpdateEntityRequest(body, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
