/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.resources.compliance.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ExportRequestSubjectType {
  public static final ExportRequestSubjectType ORG = new ExportRequestSubjectType(Value.ORG, "org");

  public static final ExportRequestSubjectType USER = new ExportRequestSubjectType(Value.USER, "user");

  public static final ExportRequestSubjectType CLIENT = new ExportRequestSubjectType(Value.CLIENT, "client");

  private final Value value;

  private final String string;

  ExportRequestSubjectType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ExportRequestSubjectType && this.string.equals(((ExportRequestSubjectType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case ORG:
        return visitor.visitOrg();
      case USER:
        return visitor.visitUser();
      case CLIENT:
        return visitor.visitClient();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ExportRequestSubjectType valueOf(String value) {
    switch (value) {
      case "org":
        return ORG;
      case "user":
        return USER;
      case "client":
        return CLIENT;
      default:
        return new ExportRequestSubjectType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    USER,

    CLIENT,

    ORG,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitUser();

    T visitClient();

    T visitOrg();

    T visitUnknown(String unknownType);
  }
}
