/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.resources.inference.requests;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Float;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DocumentAskRequest.Builder.class
)
public final class DocumentAskRequest {
  private final String prompt;

  private final Optional<String> instructions;

  private final Optional<String> model;

  private final Optional<Integer> maxTokens;

  private final Optional<Float> temperature;

  private final Optional<Boolean> allowGlobalRegion;

  private final Map<String, Object> additionalProperties;

  private DocumentAskRequest(String prompt, Optional<String> instructions, Optional<String> model,
      Optional<Integer> maxTokens, Optional<Float> temperature, Optional<Boolean> allowGlobalRegion,
      Map<String, Object> additionalProperties) {
    this.prompt = prompt;
    this.instructions = instructions;
    this.model = model;
    this.maxTokens = maxTokens;
    this.temperature = temperature;
    this.allowGlobalRegion = allowGlobalRegion;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The question or instruction to answer about the document.
   */
  @JsonProperty("prompt")
  public String getPrompt() {
    return prompt;
  }

  /**
   * @return Optional system prompt that overrides the default. Defaults to a generic instruction to act as a helpful document analyst.
   */
  @JsonProperty("instructions")
  public Optional<String> getInstructions() {
    return instructions;
  }

  /**
   * @return Model alias to use, from the list returned by <code>GET /v1/models</code>. Defaults to <code>claude-haiku-4-5</code>.
   */
  @JsonProperty("model")
  public Optional<String> getModel() {
    return model;
  }

  /**
   * @return Maximum number of tokens to generate. Defaults to 2048; the maximum is 8192.
   */
  @JsonProperty("maxTokens")
  public Optional<Integer> getMaxTokens() {
    return maxTokens;
  }

  /**
   * @return Sampling temperature. Defaults to 0.2.
   */
  @JsonProperty("temperature")
  public Optional<Float> getTemperature() {
    return temperature;
  }

  /**
   * @return Opt this request into global (non-US) region serving for lower cost. Requires a signed global-processing waiver on your account that permits per-request override; otherwise the request is rejected with 403. When omitted, the request follows your account's default residency setting.
   */
  @JsonProperty("allowGlobalRegion")
  public Optional<Boolean> getAllowGlobalRegion() {
    return allowGlobalRegion;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DocumentAskRequest && equalTo((DocumentAskRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DocumentAskRequest other) {
    return prompt.equals(other.prompt) && instructions.equals(other.instructions) && model.equals(other.model) && maxTokens.equals(other.maxTokens) && temperature.equals(other.temperature) && allowGlobalRegion.equals(other.allowGlobalRegion);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.prompt, this.instructions, this.model, this.maxTokens, this.temperature, this.allowGlobalRegion);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static PromptStage builder() {
    return new Builder();
  }

  public interface PromptStage {
    /**
     * <p>The question or instruction to answer about the document.</p>
     */
    _FinalStage prompt(@NotNull String prompt);

    Builder from(DocumentAskRequest other);
  }

  public interface _FinalStage {
    DocumentAskRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Optional system prompt that overrides the default. Defaults to a generic instruction to act as a helpful document analyst.</p>
     */
    _FinalStage instructions(Optional<String> instructions);

    _FinalStage instructions(String instructions);

    /**
     * <p>Model alias to use, from the list returned by <code>GET /v1/models</code>. Defaults to <code>claude-haiku-4-5</code>.</p>
     */
    _FinalStage model(Optional<String> model);

    _FinalStage model(String model);

    /**
     * <p>Maximum number of tokens to generate. Defaults to 2048; the maximum is 8192.</p>
     */
    _FinalStage maxTokens(Optional<Integer> maxTokens);

    _FinalStage maxTokens(Integer maxTokens);

    /**
     * <p>Sampling temperature. Defaults to 0.2.</p>
     */
    _FinalStage temperature(Optional<Float> temperature);

    _FinalStage temperature(Float temperature);

    /**
     * <p>Opt this request into global (non-US) region serving for lower cost. Requires a signed global-processing waiver on your account that permits per-request override; otherwise the request is rejected with 403. When omitted, the request follows your account's default residency setting.</p>
     */
    _FinalStage allowGlobalRegion(Optional<Boolean> allowGlobalRegion);

    _FinalStage allowGlobalRegion(Boolean allowGlobalRegion);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements PromptStage, _FinalStage {
    private String prompt;

    private Optional<Boolean> allowGlobalRegion = Optional.empty();

    private Optional<Float> temperature = Optional.empty();

    private Optional<Integer> maxTokens = Optional.empty();

    private Optional<String> model = Optional.empty();

    private Optional<String> instructions = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(DocumentAskRequest other) {
      prompt(other.getPrompt());
      instructions(other.getInstructions());
      model(other.getModel());
      maxTokens(other.getMaxTokens());
      temperature(other.getTemperature());
      allowGlobalRegion(other.getAllowGlobalRegion());
      return this;
    }

    /**
     * <p>The question or instruction to answer about the document.</p>
     * <p>The question or instruction to answer about the document.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("prompt")
    public _FinalStage prompt(@NotNull String prompt) {
      this.prompt = Objects.requireNonNull(prompt, "prompt must not be null");
      return this;
    }

    /**
     * <p>Opt this request into global (non-US) region serving for lower cost. Requires a signed global-processing waiver on your account that permits per-request override; otherwise the request is rejected with 403. When omitted, the request follows your account's default residency setting.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage allowGlobalRegion(Boolean allowGlobalRegion) {
      this.allowGlobalRegion = Optional.ofNullable(allowGlobalRegion);
      return this;
    }

    /**
     * <p>Opt this request into global (non-US) region serving for lower cost. Requires a signed global-processing waiver on your account that permits per-request override; otherwise the request is rejected with 403. When omitted, the request follows your account's default residency setting.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "allowGlobalRegion",
        nulls = Nulls.SKIP
    )
    public _FinalStage allowGlobalRegion(Optional<Boolean> allowGlobalRegion) {
      this.allowGlobalRegion = allowGlobalRegion;
      return this;
    }

    /**
     * <p>Sampling temperature. Defaults to 0.2.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage temperature(Float temperature) {
      this.temperature = Optional.ofNullable(temperature);
      return this;
    }

    /**
     * <p>Sampling temperature. Defaults to 0.2.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "temperature",
        nulls = Nulls.SKIP
    )
    public _FinalStage temperature(Optional<Float> temperature) {
      this.temperature = temperature;
      return this;
    }

    /**
     * <p>Maximum number of tokens to generate. Defaults to 2048; the maximum is 8192.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage maxTokens(Integer maxTokens) {
      this.maxTokens = Optional.ofNullable(maxTokens);
      return this;
    }

    /**
     * <p>Maximum number of tokens to generate. Defaults to 2048; the maximum is 8192.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "maxTokens",
        nulls = Nulls.SKIP
    )
    public _FinalStage maxTokens(Optional<Integer> maxTokens) {
      this.maxTokens = maxTokens;
      return this;
    }

    /**
     * <p>Model alias to use, from the list returned by <code>GET /v1/models</code>. Defaults to <code>claude-haiku-4-5</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage model(String model) {
      this.model = Optional.ofNullable(model);
      return this;
    }

    /**
     * <p>Model alias to use, from the list returned by <code>GET /v1/models</code>. Defaults to <code>claude-haiku-4-5</code>.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "model",
        nulls = Nulls.SKIP
    )
    public _FinalStage model(Optional<String> model) {
      this.model = model;
      return this;
    }

    /**
     * <p>Optional system prompt that overrides the default. Defaults to a generic instruction to act as a helpful document analyst.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage instructions(String instructions) {
      this.instructions = Optional.ofNullable(instructions);
      return this;
    }

    /**
     * <p>Optional system prompt that overrides the default. Defaults to a generic instruction to act as a helpful document analyst.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "instructions",
        nulls = Nulls.SKIP
    )
    public _FinalStage instructions(Optional<String> instructions) {
      this.instructions = instructions;
      return this;
    }

    @java.lang.Override
    public DocumentAskRequest build() {
      return new DocumentAskRequest(prompt, instructions, model, maxTokens, temperature, allowGlobalRegion, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
