/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.resources.identity;

import ai.vectros.core.ClientOptions;
import ai.vectros.core.RequestOptions;
import ai.vectros.resources.identity.requests.DeleteClientRequest;
import ai.vectros.resources.identity.requests.DeleteOrgRequest;
import ai.vectros.resources.identity.requests.DeleteUserRequest;
import ai.vectros.resources.identity.requests.GetClientRequest;
import ai.vectros.resources.identity.requests.GetClientVersionsRequest;
import ai.vectros.resources.identity.requests.GetOrgRequest;
import ai.vectros.resources.identity.requests.GetOrgVersionsRequest;
import ai.vectros.resources.identity.requests.GetUserRequest;
import ai.vectros.resources.identity.requests.GetUserVersionsRequest;
import ai.vectros.resources.identity.requests.ListClientsRequest;
import ai.vectros.resources.identity.requests.ListOrgsRequest;
import ai.vectros.resources.identity.requests.ListUsersRequest;
import ai.vectros.resources.identity.requests.UpdateClientRequest;
import ai.vectros.resources.identity.requests.UpdateOrgRequest;
import ai.vectros.resources.identity.requests.UpdateUserRequest;
import ai.vectros.types.ClientPage;
import ai.vectros.types.ClientRequest;
import ai.vectros.types.ClientResponse;
import ai.vectros.types.IdentityLookupRequest;
import ai.vectros.types.ModelDataVersionPage;
import ai.vectros.types.OrgPage;
import ai.vectros.types.OrgRequest;
import ai.vectros.types.OrgResponse;
import ai.vectros.types.UserPage;
import ai.vectros.types.UserRequest;
import ai.vectros.types.UserResponse;
import java.lang.String;
import java.lang.Void;
import java.util.concurrent.CompletableFuture;

public class AsyncIdentityClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawIdentityClient rawClient;

  public AsyncIdentityClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawIdentityClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawIdentityClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Returns a paginated list of clients in your account. Narrow the results with <code>orgId</code> or <code>userId</code>, or use <code>externalId</code> for an exact lookup by your own identifier. For schema-bound clients, you can also query by a schema-declared lookup field using <code>type</code>, <code>field</code>, and one lookup mode (<code>value</code> for equality, <code>from</code>/<code>to</code> for a range, or <code>prefix</code>). The response is a <code>{data, nextCursor}</code> envelope; pass <code>nextCursor</code> back as <code>startFrom</code> to fetch the next page. Requires the <code>clients:r</code> scope.
   */
  public CompletableFuture<ClientPage> listClients() {
    return this.rawClient.listClients().thenApply(response -> response.body());
  }

  /**
   * Returns a paginated list of clients in your account. Narrow the results with <code>orgId</code> or <code>userId</code>, or use <code>externalId</code> for an exact lookup by your own identifier. For schema-bound clients, you can also query by a schema-declared lookup field using <code>type</code>, <code>field</code>, and one lookup mode (<code>value</code> for equality, <code>from</code>/<code>to</code> for a range, or <code>prefix</code>). The response is a <code>{data, nextCursor}</code> envelope; pass <code>nextCursor</code> back as <code>startFrom</code> to fetch the next page. Requires the <code>clients:r</code> scope.
   */
  public CompletableFuture<ClientPage> listClients(RequestOptions requestOptions) {
    return this.rawClient.listClients(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a paginated list of clients in your account. Narrow the results with <code>orgId</code> or <code>userId</code>, or use <code>externalId</code> for an exact lookup by your own identifier. For schema-bound clients, you can also query by a schema-declared lookup field using <code>type</code>, <code>field</code>, and one lookup mode (<code>value</code> for equality, <code>from</code>/<code>to</code> for a range, or <code>prefix</code>). The response is a <code>{data, nextCursor}</code> envelope; pass <code>nextCursor</code> back as <code>startFrom</code> to fetch the next page. Requires the <code>clients:r</code> scope.
   */
  public CompletableFuture<ClientPage> listClients(ListClientsRequest request) {
    return this.rawClient.listClients(request).thenApply(response -> response.body());
  }

  /**
   * Returns a paginated list of clients in your account. Narrow the results with <code>orgId</code> or <code>userId</code>, or use <code>externalId</code> for an exact lookup by your own identifier. For schema-bound clients, you can also query by a schema-declared lookup field using <code>type</code>, <code>field</code>, and one lookup mode (<code>value</code> for equality, <code>from</code>/<code>to</code> for a range, or <code>prefix</code>). The response is a <code>{data, nextCursor}</code> envelope; pass <code>nextCursor</code> back as <code>startFrom</code> to fetch the next page. Requires the <code>clients:r</code> scope.
   */
  public CompletableFuture<ClientPage> listClients(ListClientsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.listClients(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Creates a new client identity in your account. This call is idempotent on <code>externalId</code>: if a client with the same <code>externalId</code> already exists, the existing record is returned instead of creating a duplicate. Requires the <code>clients:c</code> scope.
   */
  public CompletableFuture<ClientResponse> createClient(ClientRequest request) {
    return this.rawClient.createClient(request).thenApply(response -> response.body());
  }

  /**
   * Creates a new client identity in your account. This call is idempotent on <code>externalId</code>: if a client with the same <code>externalId</code> already exists, the existing record is returned instead of creating a duplicate. Requires the <code>clients:c</code> scope.
   */
  public CompletableFuture<ClientResponse> createClient(ClientRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.createClient(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a single client by its Vectros-assigned UUID. Requires the <code>clients:r</code> scope.
   */
  public CompletableFuture<ClientResponse> getClient(String id) {
    return this.rawClient.getClient(id).thenApply(response -> response.body());
  }

  /**
   * Returns a single client by its Vectros-assigned UUID. Requires the <code>clients:r</code> scope.
   */
  public CompletableFuture<ClientResponse> getClient(String id, RequestOptions requestOptions) {
    return this.rawClient.getClient(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a single client by its Vectros-assigned UUID. Requires the <code>clients:r</code> scope.
   */
  public CompletableFuture<ClientResponse> getClient(String id, GetClientRequest request) {
    return this.rawClient.getClient(id, request).thenApply(response -> response.body());
  }

  /**
   * Returns a single client by its Vectros-assigned UUID. Requires the <code>clients:r</code> scope.
   */
  public CompletableFuture<ClientResponse> getClient(String id, GetClientRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getClient(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Updates mutable fields on an existing client. Omitted fields are preserved (a null does not clear a field); when <code>payload</code> is supplied it replaces the stored payload in full rather than being deep-merged. Requires the <code>clients:u</code> scope.
   */
  public CompletableFuture<ClientResponse> updateClient(String id, UpdateClientRequest request) {
    return this.rawClient.updateClient(id, request).thenApply(response -> response.body());
  }

  /**
   * Updates mutable fields on an existing client. Omitted fields are preserved (a null does not clear a field); when <code>payload</code> is supplied it replaces the stored payload in full rather than being deep-merged. Requires the <code>clients:u</code> scope.
   */
  public CompletableFuture<ClientResponse> updateClient(String id, UpdateClientRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.updateClient(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes the client. This action cannot be undone. Requires the <code>clients:d</code> scope.
   */
  public CompletableFuture<Void> deleteClient(String id) {
    return this.rawClient.deleteClient(id).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes the client. This action cannot be undone. Requires the <code>clients:d</code> scope.
   */
  public CompletableFuture<Void> deleteClient(String id, RequestOptions requestOptions) {
    return this.rawClient.deleteClient(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes the client. This action cannot be undone. Requires the <code>clients:d</code> scope.
   */
  public CompletableFuture<Void> deleteClient(String id, DeleteClientRequest request) {
    return this.rawClient.deleteClient(id, request).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes the client. This action cannot be undone. Requires the <code>clients:d</code> scope.
   */
  public CompletableFuture<Void> deleteClient(String id, DeleteClientRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.deleteClient(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Body-based equivalent of the <code>type</code>/<code>field</code>/<code>value</code> lookup on <code>GET /v1/clients</code>. Use this when looking up by a sensitive (blind-indexed) field: the value travels in the request body rather than the URL. The <code>GET</code> list rejects a sensitive field's value and directs you here. The response is a <code>{data, nextCursor}</code> envelope. Requires the <code>clients:r</code> scope.
   */
  public CompletableFuture<ClientPage> lookupClients(IdentityLookupRequest request) {
    return this.rawClient.lookupClients(request).thenApply(response -> response.body());
  }

  /**
   * Body-based equivalent of the <code>type</code>/<code>field</code>/<code>value</code> lookup on <code>GET /v1/clients</code>. Use this when looking up by a sensitive (blind-indexed) field: the value travels in the request body rather than the URL. The <code>GET</code> list rejects a sensitive field's value and directs you here. The response is a <code>{data, nextCursor}</code> envelope. Requires the <code>clients:r</code> scope.
   */
  public CompletableFuture<ClientPage> lookupClients(IdentityLookupRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.lookupClients(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes to a client, newest first. Identity auditing is always on, so this history is always available; sensitive field values are redacted in each version. The response is a <code>{data, nextCursor}</code> envelope. Requires the <code>clients:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getClientVersions(String id) {
    return this.rawClient.getClientVersions(id).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes to a client, newest first. Identity auditing is always on, so this history is always available; sensitive field values are redacted in each version. The response is a <code>{data, nextCursor}</code> envelope. Requires the <code>clients:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getClientVersions(String id,
      RequestOptions requestOptions) {
    return this.rawClient.getClientVersions(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes to a client, newest first. Identity auditing is always on, so this history is always available; sensitive field values are redacted in each version. The response is a <code>{data, nextCursor}</code> envelope. Requires the <code>clients:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getClientVersions(String id,
      GetClientVersionsRequest request) {
    return this.rawClient.getClientVersions(id, request).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes to a client, newest first. Identity auditing is always on, so this history is always available; sensitive field values are redacted in each version. The response is a <code>{data, nextCursor}</code> envelope. Requires the <code>clients:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getClientVersions(String id,
      GetClientVersionsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getClientVersions(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a paginated list of organizations in your account. Filter by <code>userId</code> to return only the organizations owned by a specific user, or by <code>externalId</code> for an exact lookup using your own identifier. You can also query schema-declared lookup fields by supplying <code>type</code> and <code>field</code> together with one lookup mode (<code>value</code> for equality, <code>from</code>/<code>to</code> for a range, or <code>prefix</code>). Requires the <code>orgs:r</code> scope.
   */
  public CompletableFuture<OrgPage> listOrgs() {
    return this.rawClient.listOrgs().thenApply(response -> response.body());
  }

  /**
   * Returns a paginated list of organizations in your account. Filter by <code>userId</code> to return only the organizations owned by a specific user, or by <code>externalId</code> for an exact lookup using your own identifier. You can also query schema-declared lookup fields by supplying <code>type</code> and <code>field</code> together with one lookup mode (<code>value</code> for equality, <code>from</code>/<code>to</code> for a range, or <code>prefix</code>). Requires the <code>orgs:r</code> scope.
   */
  public CompletableFuture<OrgPage> listOrgs(RequestOptions requestOptions) {
    return this.rawClient.listOrgs(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a paginated list of organizations in your account. Filter by <code>userId</code> to return only the organizations owned by a specific user, or by <code>externalId</code> for an exact lookup using your own identifier. You can also query schema-declared lookup fields by supplying <code>type</code> and <code>field</code> together with one lookup mode (<code>value</code> for equality, <code>from</code>/<code>to</code> for a range, or <code>prefix</code>). Requires the <code>orgs:r</code> scope.
   */
  public CompletableFuture<OrgPage> listOrgs(ListOrgsRequest request) {
    return this.rawClient.listOrgs(request).thenApply(response -> response.body());
  }

  /**
   * Returns a paginated list of organizations in your account. Filter by <code>userId</code> to return only the organizations owned by a specific user, or by <code>externalId</code> for an exact lookup using your own identifier. You can also query schema-declared lookup fields by supplying <code>type</code> and <code>field</code> together with one lookup mode (<code>value</code> for equality, <code>from</code>/<code>to</code> for a range, or <code>prefix</code>). Requires the <code>orgs:r</code> scope.
   */
  public CompletableFuture<OrgPage> listOrgs(ListOrgsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.listOrgs(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Creates a new organization in your account. This call is idempotent on <code>externalId</code>: if an organization with the same <code>externalId</code> already exists, the existing record is returned instead of creating a duplicate. Requires the <code>orgs:c</code> scope.
   */
  public CompletableFuture<OrgResponse> createOrg(OrgRequest request) {
    return this.rawClient.createOrg(request).thenApply(response -> response.body());
  }

  /**
   * Creates a new organization in your account. This call is idempotent on <code>externalId</code>: if an organization with the same <code>externalId</code> already exists, the existing record is returned instead of creating a duplicate. Requires the <code>orgs:c</code> scope.
   */
  public CompletableFuture<OrgResponse> createOrg(OrgRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.createOrg(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieves a single organization by its Vectros-assigned ID, returning its current name, status, payload, and schema binding. Requires the <code>orgs:r</code> scope.
   */
  public CompletableFuture<OrgResponse> getOrg(String id) {
    return this.rawClient.getOrg(id).thenApply(response -> response.body());
  }

  /**
   * Retrieves a single organization by its Vectros-assigned ID, returning its current name, status, payload, and schema binding. Requires the <code>orgs:r</code> scope.
   */
  public CompletableFuture<OrgResponse> getOrg(String id, RequestOptions requestOptions) {
    return this.rawClient.getOrg(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieves a single organization by its Vectros-assigned ID, returning its current name, status, payload, and schema binding. Requires the <code>orgs:r</code> scope.
   */
  public CompletableFuture<OrgResponse> getOrg(String id, GetOrgRequest request) {
    return this.rawClient.getOrg(id, request).thenApply(response -> response.body());
  }

  /**
   * Retrieves a single organization by its Vectros-assigned ID, returning its current name, status, payload, and schema binding. Requires the <code>orgs:r</code> scope.
   */
  public CompletableFuture<OrgResponse> getOrg(String id, GetOrgRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getOrg(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Updates the mutable fields of an organization. Omitted fields are preserved (a null value does not clear a field), and the <code>payload</code> object is replaced in full when supplied rather than deep-merged. Requires the <code>orgs:u</code> scope.
   */
  public CompletableFuture<OrgResponse> updateOrg(String id, UpdateOrgRequest request) {
    return this.rawClient.updateOrg(id, request).thenApply(response -> response.body());
  }

  /**
   * Updates the mutable fields of an organization. Omitted fields are preserved (a null value does not clear a field), and the <code>payload</code> object is replaced in full when supplied rather than deep-merged. Requires the <code>orgs:u</code> scope.
   */
  public CompletableFuture<OrgResponse> updateOrg(String id, UpdateOrgRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.updateOrg(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes an organization. This action cannot be undone. Requires the <code>orgs:d</code> scope.
   */
  public CompletableFuture<Void> deleteOrg(String id) {
    return this.rawClient.deleteOrg(id).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes an organization. This action cannot be undone. Requires the <code>orgs:d</code> scope.
   */
  public CompletableFuture<Void> deleteOrg(String id, RequestOptions requestOptions) {
    return this.rawClient.deleteOrg(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes an organization. This action cannot be undone. Requires the <code>orgs:d</code> scope.
   */
  public CompletableFuture<Void> deleteOrg(String id, DeleteOrgRequest request) {
    return this.rawClient.deleteOrg(id, request).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes an organization. This action cannot be undone. Requires the <code>orgs:d</code> scope.
   */
  public CompletableFuture<Void> deleteOrg(String id, DeleteOrgRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.deleteOrg(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Looks up organizations by a schema-declared field value, with the search criteria sent in the request body instead of the URL. Use this when looking up by a sensitive field: the value travels in the body and is never exposed in the URL. This is the body-based equivalent of the <code>type</code>/<code>field</code>/<code>value</code> lookup on <code>GET /v1/orgs</code>, which rejects sensitive-field values and directs you here. Returns a <code>{data, nextCursor}</code> envelope. Requires the <code>orgs:r</code> scope.
   */
  public CompletableFuture<OrgPage> lookupOrgs(IdentityLookupRequest request) {
    return this.rawClient.lookupOrgs(request).thenApply(response -> response.body());
  }

  /**
   * Looks up organizations by a schema-declared field value, with the search criteria sent in the request body instead of the URL. Use this when looking up by a sensitive field: the value travels in the body and is never exposed in the URL. This is the body-based equivalent of the <code>type</code>/<code>field</code>/<code>value</code> lookup on <code>GET /v1/orgs</code>, which rejects sensitive-field values and directs you here. Returns a <code>{data, nextCursor}</code> envelope. Requires the <code>orgs:r</code> scope.
   */
  public CompletableFuture<OrgPage> lookupOrgs(IdentityLookupRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.lookupOrgs(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes made to an organization, newest first. Version history is always recorded for identity entities, and sensitive field values are redacted in the history. Requires the <code>orgs:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getOrgVersions(String id) {
    return this.rawClient.getOrgVersions(id).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes made to an organization, newest first. Version history is always recorded for identity entities, and sensitive field values are redacted in the history. Requires the <code>orgs:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getOrgVersions(String id,
      RequestOptions requestOptions) {
    return this.rawClient.getOrgVersions(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes made to an organization, newest first. Version history is always recorded for identity entities, and sensitive field values are redacted in the history. Requires the <code>orgs:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getOrgVersions(String id,
      GetOrgVersionsRequest request) {
    return this.rawClient.getOrgVersions(id, request).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes made to an organization, newest first. Version history is always recorded for identity entities, and sensitive field values are redacted in the history. Requires the <code>orgs:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getOrgVersions(String id,
      GetOrgVersionsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getOrgVersions(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a paginated list of the users in your account. Pass <code>externalId</code> to look up a single user by your own identifier. To filter on schema-declared lookup fields, supply <code>type</code> and <code>field</code> together with one lookup mode: <code>value</code> (exact match), <code>from</code>+<code>to</code> (range), or <code>prefix</code>. Requires the <code>users:r</code> scope.
   */
  public CompletableFuture<UserPage> listUsers() {
    return this.rawClient.listUsers().thenApply(response -> response.body());
  }

  /**
   * Returns a paginated list of the users in your account. Pass <code>externalId</code> to look up a single user by your own identifier. To filter on schema-declared lookup fields, supply <code>type</code> and <code>field</code> together with one lookup mode: <code>value</code> (exact match), <code>from</code>+<code>to</code> (range), or <code>prefix</code>. Requires the <code>users:r</code> scope.
   */
  public CompletableFuture<UserPage> listUsers(RequestOptions requestOptions) {
    return this.rawClient.listUsers(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a paginated list of the users in your account. Pass <code>externalId</code> to look up a single user by your own identifier. To filter on schema-declared lookup fields, supply <code>type</code> and <code>field</code> together with one lookup mode: <code>value</code> (exact match), <code>from</code>+<code>to</code> (range), or <code>prefix</code>. Requires the <code>users:r</code> scope.
   */
  public CompletableFuture<UserPage> listUsers(ListUsersRequest request) {
    return this.rawClient.listUsers(request).thenApply(response -> response.body());
  }

  /**
   * Returns a paginated list of the users in your account. Pass <code>externalId</code> to look up a single user by your own identifier. To filter on schema-declared lookup fields, supply <code>type</code> and <code>field</code> together with one lookup mode: <code>value</code> (exact match), <code>from</code>+<code>to</code> (range), or <code>prefix</code>. Requires the <code>users:r</code> scope.
   */
  public CompletableFuture<UserPage> listUsers(ListUsersRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.listUsers(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Creates a user identity in your account. The operation is idempotent on <code>externalId</code>: if a user with the same <code>externalId</code> already exists, the existing record is returned instead of creating a duplicate. Requires the <code>users:c</code> scope.
   */
  public CompletableFuture<UserResponse> createUser(UserRequest request) {
    return this.rawClient.createUser(request).thenApply(response -> response.body());
  }

  /**
   * Creates a user identity in your account. The operation is idempotent on <code>externalId</code>: if a user with the same <code>externalId</code> already exists, the existing record is returned instead of creating a duplicate. Requires the <code>users:c</code> scope.
   */
  public CompletableFuture<UserResponse> createUser(UserRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.createUser(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieves a single user by its Vectros-assigned ID. Requires the <code>users:r</code> scope.
   */
  public CompletableFuture<UserResponse> getUser(String id) {
    return this.rawClient.getUser(id).thenApply(response -> response.body());
  }

  /**
   * Retrieves a single user by its Vectros-assigned ID. Requires the <code>users:r</code> scope.
   */
  public CompletableFuture<UserResponse> getUser(String id, RequestOptions requestOptions) {
    return this.rawClient.getUser(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieves a single user by its Vectros-assigned ID. Requires the <code>users:r</code> scope.
   */
  public CompletableFuture<UserResponse> getUser(String id, GetUserRequest request) {
    return this.rawClient.getUser(id, request).thenApply(response -> response.body());
  }

  /**
   * Retrieves a single user by its Vectros-assigned ID. Requires the <code>users:r</code> scope.
   */
  public CompletableFuture<UserResponse> getUser(String id, GetUserRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getUser(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Updates mutable fields on an existing user (such as email, status, payload, or schema binding). The <code>type</code> field is immutable after creation. This endpoint also activates an invited user: a PUT that moves a PENDING user to ACTIVE and carries <code>inviteToken</code>, <code>externalSubject</code>, and <code>emailVerifiedAttestation=true</code> completes the invitation. Requires the <code>users:u</code> scope.
   */
  public CompletableFuture<UserResponse> updateUser(String id, UpdateUserRequest request) {
    return this.rawClient.updateUser(id, request).thenApply(response -> response.body());
  }

  /**
   * Updates mutable fields on an existing user (such as email, status, payload, or schema binding). The <code>type</code> field is immutable after creation. This endpoint also activates an invited user: a PUT that moves a PENDING user to ACTIVE and carries <code>inviteToken</code>, <code>externalSubject</code>, and <code>emailVerifiedAttestation=true</code> completes the invitation. Requires the <code>users:u</code> scope.
   */
  public CompletableFuture<UserResponse> updateUser(String id, UpdateUserRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.updateUser(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes a user identity. This cannot be undone. If the user is a pending invitation, the associated access profile created for that invitation is also removed. Requires the <code>users:d</code> scope.
   */
  public CompletableFuture<Void> deleteUser(String id) {
    return this.rawClient.deleteUser(id).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes a user identity. This cannot be undone. If the user is a pending invitation, the associated access profile created for that invitation is also removed. Requires the <code>users:d</code> scope.
   */
  public CompletableFuture<Void> deleteUser(String id, RequestOptions requestOptions) {
    return this.rawClient.deleteUser(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes a user identity. This cannot be undone. If the user is a pending invitation, the associated access profile created for that invitation is also removed. Requires the <code>users:d</code> scope.
   */
  public CompletableFuture<Void> deleteUser(String id, DeleteUserRequest request) {
    return this.rawClient.deleteUser(id, request).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes a user identity. This cannot be undone. If the user is a pending invitation, the associated access profile created for that invitation is also removed. Requires the <code>users:d</code> scope.
   */
  public CompletableFuture<Void> deleteUser(String id, DeleteUserRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.deleteUser(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Looks up users by a schema lookup field, with the query criteria carried in the request body rather than the URL. Use this when looking up by a sensitive (blind-indexed) field: the value is blind-indexed server-side and never appears in the URL, request logs, or proxies. The query semantics are identical to the GET /v1/users lookup, which rejects sensitive-field values and directs you here. Returns a page in the <code>{data, nextCursor}</code> envelope. Requires the <code>users:r</code> scope.
   */
  public CompletableFuture<UserPage> lookupUsers(IdentityLookupRequest request) {
    return this.rawClient.lookupUsers(request).thenApply(response -> response.body());
  }

  /**
   * Looks up users by a schema lookup field, with the query criteria carried in the request body rather than the URL. Use this when looking up by a sensitive (blind-indexed) field: the value is blind-indexed server-side and never appears in the URL, request logs, or proxies. The query semantics are identical to the GET /v1/users lookup, which rejects sensitive-field values and directs you here. Returns a page in the <code>{data, nextCursor}</code> envelope. Requires the <code>users:r</code> scope.
   */
  public CompletableFuture<UserPage> lookupUsers(IdentityLookupRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.lookupUsers(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes to a user, most recent first. Identity history is always recorded and always available. Sensitive field values are redacted in every historical version. Returns a page in the <code>{data, nextCursor}</code> envelope. Requires the <code>users:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getUserVersions(String id) {
    return this.rawClient.getUserVersions(id).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes to a user, most recent first. Identity history is always recorded and always available. Sensitive field values are redacted in every historical version. Returns a page in the <code>{data, nextCursor}</code> envelope. Requires the <code>users:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getUserVersions(String id,
      RequestOptions requestOptions) {
    return this.rawClient.getUserVersions(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes to a user, most recent first. Identity history is always recorded and always available. Sensitive field values are redacted in every historical version. Returns a page in the <code>{data, nextCursor}</code> envelope. Requires the <code>users:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getUserVersions(String id,
      GetUserVersionsRequest request) {
    return this.rawClient.getUserVersions(id, request).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes to a user, most recent first. Identity history is always recorded and always available. Sensitive field values are redacted in every historical version. Returns a page in the <code>{data, nextCursor}</code> envelope. Requires the <code>users:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getUserVersions(String id,
      GetUserVersionsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getUserVersions(id, request, requestOptions).thenApply(response -> response.body());
  }
}
