/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.resources.auth.requests;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateScopedKeyRequest.Builder.class
)
public final class CreateScopedKeyRequest {
  private final String keyName;

  private final String tenantId;

  private final String contextId;

  private final String userId;

  private final Optional<String> label;

  private final Map<String, Object> additionalProperties;

  private CreateScopedKeyRequest(String keyName, String tenantId, String contextId, String userId,
      Optional<String> label, Map<String, Object> additionalProperties) {
    this.keyName = keyName;
    this.tenantId = tenantId;
    this.contextId = contextId;
    this.userId = userId;
    this.label = label;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return A human-readable name for the key, used to identify and disambiguate multiple keys for the same user. Maximum 100 characters.
   */
  @JsonProperty("keyName")
  public String getKeyName() {
    return keyName;
  }

  /**
   * @return The tenant the key will operate on. Must be your live tenant ID or your test tenant ID; an ID outside your account returns a uniform <code>404 not found</code> (no distinction is made between a missing and an out-of-account tenant).
   */
  @JsonProperty("tenantId")
  public String getTenantId() {
    return tenantId;
  }

  /**
   * @return The app context within the tenant. Must reference an app context that already exists (create one via <code>POST /v1/app-contexts</code>).
   */
  @JsonProperty("contextId")
  public String getContextId() {
    return contextId;
  }

  /**
   * @return The user the key binds to. May be a <code>HUMAN</code> or a <code>SERVICE</code> user (a service user is the typical agent or bot case). An access profile must already exist for this context and user — the key references that profile; it does not create one.
   */
  @JsonProperty("userId")
  public String getUserId() {
    return userId;
  }

  /**
   * @return Optional display label surfaced through <code>/v1/ping</code> as <code>principalLabel</code>. The MCP <code>current_identity</code> tool uses it to show &quot;signed in as ...&quot; hints to end users (e.g. &quot;Claude Desktop — clinical-notes RO&quot;). Distinct from <code>keyName</code>, which is your own identifier for the key. Maximum 80 characters; if present, it must not have leading or trailing whitespace.
   */
  @JsonProperty("label")
  public Optional<String> getLabel() {
    return label;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateScopedKeyRequest && equalTo((CreateScopedKeyRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateScopedKeyRequest other) {
    return keyName.equals(other.keyName) && tenantId.equals(other.tenantId) && contextId.equals(other.contextId) && userId.equals(other.userId) && label.equals(other.label);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.keyName, this.tenantId, this.contextId, this.userId, this.label);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static KeyNameStage builder() {
    return new Builder();
  }

  public interface KeyNameStage {
    /**
     * <p>A human-readable name for the key, used to identify and disambiguate multiple keys for the same user. Maximum 100 characters.</p>
     */
    TenantIdStage keyName(@NotNull String keyName);

    Builder from(CreateScopedKeyRequest other);
  }

  public interface TenantIdStage {
    /**
     * <p>The tenant the key will operate on. Must be your live tenant ID or your test tenant ID; an ID outside your account returns a uniform <code>404 not found</code> (no distinction is made between a missing and an out-of-account tenant).</p>
     */
    ContextIdStage tenantId(@NotNull String tenantId);
  }

  public interface ContextIdStage {
    /**
     * <p>The app context within the tenant. Must reference an app context that already exists (create one via <code>POST /v1/app-contexts</code>).</p>
     */
    UserIdStage contextId(@NotNull String contextId);
  }

  public interface UserIdStage {
    /**
     * <p>The user the key binds to. May be a <code>HUMAN</code> or a <code>SERVICE</code> user (a service user is the typical agent or bot case). An access profile must already exist for this context and user — the key references that profile; it does not create one.</p>
     */
    _FinalStage userId(@NotNull String userId);
  }

  public interface _FinalStage {
    CreateScopedKeyRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Optional display label surfaced through <code>/v1/ping</code> as <code>principalLabel</code>. The MCP <code>current_identity</code> tool uses it to show &quot;signed in as ...&quot; hints to end users (e.g. &quot;Claude Desktop — clinical-notes RO&quot;). Distinct from <code>keyName</code>, which is your own identifier for the key. Maximum 80 characters; if present, it must not have leading or trailing whitespace.</p>
     */
    _FinalStage label(Optional<String> label);

    _FinalStage label(String label);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements KeyNameStage, TenantIdStage, ContextIdStage, UserIdStage, _FinalStage {
    private String keyName;

    private String tenantId;

    private String contextId;

    private String userId;

    private Optional<String> label = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateScopedKeyRequest other) {
      keyName(other.getKeyName());
      tenantId(other.getTenantId());
      contextId(other.getContextId());
      userId(other.getUserId());
      label(other.getLabel());
      return this;
    }

    /**
     * <p>A human-readable name for the key, used to identify and disambiguate multiple keys for the same user. Maximum 100 characters.</p>
     * <p>A human-readable name for the key, used to identify and disambiguate multiple keys for the same user. Maximum 100 characters.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("keyName")
    public TenantIdStage keyName(@NotNull String keyName) {
      this.keyName = Objects.requireNonNull(keyName, "keyName must not be null");
      return this;
    }

    /**
     * <p>The tenant the key will operate on. Must be your live tenant ID or your test tenant ID; an ID outside your account returns a uniform <code>404 not found</code> (no distinction is made between a missing and an out-of-account tenant).</p>
     * <p>The tenant the key will operate on. Must be your live tenant ID or your test tenant ID; an ID outside your account returns a uniform <code>404 not found</code> (no distinction is made between a missing and an out-of-account tenant).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("tenantId")
    public ContextIdStage tenantId(@NotNull String tenantId) {
      this.tenantId = Objects.requireNonNull(tenantId, "tenantId must not be null");
      return this;
    }

    /**
     * <p>The app context within the tenant. Must reference an app context that already exists (create one via <code>POST /v1/app-contexts</code>).</p>
     * <p>The app context within the tenant. Must reference an app context that already exists (create one via <code>POST /v1/app-contexts</code>).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("contextId")
    public UserIdStage contextId(@NotNull String contextId) {
      this.contextId = Objects.requireNonNull(contextId, "contextId must not be null");
      return this;
    }

    /**
     * <p>The user the key binds to. May be a <code>HUMAN</code> or a <code>SERVICE</code> user (a service user is the typical agent or bot case). An access profile must already exist for this context and user — the key references that profile; it does not create one.</p>
     * <p>The user the key binds to. May be a <code>HUMAN</code> or a <code>SERVICE</code> user (a service user is the typical agent or bot case). An access profile must already exist for this context and user — the key references that profile; it does not create one.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("userId")
    public _FinalStage userId(@NotNull String userId) {
      this.userId = Objects.requireNonNull(userId, "userId must not be null");
      return this;
    }

    /**
     * <p>Optional display label surfaced through <code>/v1/ping</code> as <code>principalLabel</code>. The MCP <code>current_identity</code> tool uses it to show &quot;signed in as ...&quot; hints to end users (e.g. &quot;Claude Desktop — clinical-notes RO&quot;). Distinct from <code>keyName</code>, which is your own identifier for the key. Maximum 80 characters; if present, it must not have leading or trailing whitespace.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage label(String label) {
      this.label = Optional.ofNullable(label);
      return this;
    }

    /**
     * <p>Optional display label surfaced through <code>/v1/ping</code> as <code>principalLabel</code>. The MCP <code>current_identity</code> tool uses it to show &quot;signed in as ...&quot; hints to end users (e.g. &quot;Claude Desktop — clinical-notes RO&quot;). Distinct from <code>keyName</code>, which is your own identifier for the key. Maximum 80 characters; if present, it must not have leading or trailing whitespace.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "label",
        nulls = Nulls.SKIP
    )
    public _FinalStage label(Optional<String> label) {
      this.label = label;
      return this;
    }

    @java.lang.Override
    public CreateScopedKeyRequest build() {
      return new CreateScopedKeyRequest(keyName, tenantId, contextId, userId, label, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
