/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.resources.auth.requests;

import ai.vectros.core.ObjectMappers;
import ai.vectros.types.ScopeRequest;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TokenRequest.Builder.class
)
public final class TokenRequest {
  private final Optional<String> userId;

  private final ScopeRequest scope;

  private final Optional<Integer> expiresInSeconds;

  private final Map<String, Object> additionalProperties;

  private TokenRequest(Optional<String> userId, ScopeRequest scope,
      Optional<Integer> expiresInSeconds, Map<String, Object> additionalProperties) {
    this.userId = userId;
    this.scope = scope;
    this.expiresInSeconds = expiresInSeconds;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The Vectros user ID of the end user this token is minted for. This is the UUID returned when you created the user via <code>POST /v1/users</code>. Optional — omit it for service-to-service tokens that have no specific user context. If provided, it must reference a real user in your account. Use <code>GET /v1/users?externalId={yourId}</code> to resolve your own system's user ID to the Vectros user ID.
   */
  @JsonProperty("userId")
  public Optional<String> getUserId() {
    return userId;
  }

  @JsonProperty("scope")
  public ScopeRequest getScope() {
    return scope;
  }

  /**
   * @return How long the token remains valid, in seconds. Maximum 86400 (24 hours); defaults to 3600 (1 hour).
   */
  @JsonProperty("expiresInSeconds")
  public Optional<Integer> getExpiresInSeconds() {
    return expiresInSeconds;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TokenRequest && equalTo((TokenRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TokenRequest other) {
    return userId.equals(other.userId) && scope.equals(other.scope) && expiresInSeconds.equals(other.expiresInSeconds);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.userId, this.scope, this.expiresInSeconds);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ScopeStage builder() {
    return new Builder();
  }

  public interface ScopeStage {
    _FinalStage scope(@NotNull ScopeRequest scope);

    Builder from(TokenRequest other);
  }

  public interface _FinalStage {
    TokenRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>The Vectros user ID of the end user this token is minted for. This is the UUID returned when you created the user via <code>POST /v1/users</code>. Optional — omit it for service-to-service tokens that have no specific user context. If provided, it must reference a real user in your account. Use <code>GET /v1/users?externalId={yourId}</code> to resolve your own system's user ID to the Vectros user ID.</p>
     */
    _FinalStage userId(Optional<String> userId);

    _FinalStage userId(String userId);

    /**
     * <p>How long the token remains valid, in seconds. Maximum 86400 (24 hours); defaults to 3600 (1 hour).</p>
     */
    _FinalStage expiresInSeconds(Optional<Integer> expiresInSeconds);

    _FinalStage expiresInSeconds(Integer expiresInSeconds);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ScopeStage, _FinalStage {
    private ScopeRequest scope;

    private Optional<Integer> expiresInSeconds = Optional.empty();

    private Optional<String> userId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(TokenRequest other) {
      userId(other.getUserId());
      scope(other.getScope());
      expiresInSeconds(other.getExpiresInSeconds());
      return this;
    }

    @java.lang.Override
    @JsonSetter("scope")
    public _FinalStage scope(@NotNull ScopeRequest scope) {
      this.scope = Objects.requireNonNull(scope, "scope must not be null");
      return this;
    }

    /**
     * <p>How long the token remains valid, in seconds. Maximum 86400 (24 hours); defaults to 3600 (1 hour).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage expiresInSeconds(Integer expiresInSeconds) {
      this.expiresInSeconds = Optional.ofNullable(expiresInSeconds);
      return this;
    }

    /**
     * <p>How long the token remains valid, in seconds. Maximum 86400 (24 hours); defaults to 3600 (1 hour).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "expiresInSeconds",
        nulls = Nulls.SKIP
    )
    public _FinalStage expiresInSeconds(Optional<Integer> expiresInSeconds) {
      this.expiresInSeconds = expiresInSeconds;
      return this;
    }

    /**
     * <p>The Vectros user ID of the end user this token is minted for. This is the UUID returned when you created the user via <code>POST /v1/users</code>. Optional — omit it for service-to-service tokens that have no specific user context. If provided, it must reference a real user in your account. Use <code>GET /v1/users?externalId={yourId}</code> to resolve your own system's user ID to the Vectros user ID.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage userId(String userId) {
      this.userId = Optional.ofNullable(userId);
      return this;
    }

    /**
     * <p>The Vectros user ID of the end user this token is minted for. This is the UUID returned when you created the user via <code>POST /v1/users</code>. Optional — omit it for service-to-service tokens that have no specific user context. If provided, it must reference a real user in your account. Use <code>GET /v1/users?externalId={yourId}</code> to resolve your own system's user ID to the Vectros user ID.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "userId",
        nulls = Nulls.SKIP
    )
    public _FinalStage userId(Optional<String> userId) {
      this.userId = userId;
      return this;
    }

    @java.lang.Override
    public TokenRequest build() {
      return new TokenRequest(userId, scope, expiresInSeconds, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
