/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BatchWriteResponse.Builder.class
)
public final class BatchWriteResponse {
  private final Optional<List<BatchWriteResult>> results;

  private final Optional<Integer> succeeded;

  private final Optional<Integer> failed;

  private final Map<String, Object> additionalProperties;

  private BatchWriteResponse(Optional<List<BatchWriteResult>> results, Optional<Integer> succeeded,
      Optional<Integer> failed, Map<String, Object> additionalProperties) {
    this.results = results;
    this.succeeded = succeeded;
    this.failed = failed;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return One result per item you submitted. Match each result to its request item by the <code>index</code> field, since results are not guaranteed to be in request order.
   */
  @JsonProperty("results")
  public Optional<List<BatchWriteResult>> getResults() {
    return results;
  }

  /**
   * @return The number of items that were created or updated.
   */
  @JsonProperty("succeeded")
  public Optional<Integer> getSucceeded() {
    return succeeded;
  }

  /**
   * @return The number of items that failed (status <code>conflict</code> or <code>invalid</code>).
   */
  @JsonProperty("failed")
  public Optional<Integer> getFailed() {
    return failed;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BatchWriteResponse && equalTo((BatchWriteResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BatchWriteResponse other) {
    return results.equals(other.results) && succeeded.equals(other.succeeded) && failed.equals(other.failed);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.results, this.succeeded, this.failed);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<List<BatchWriteResult>> results = Optional.empty();

    private Optional<Integer> succeeded = Optional.empty();

    private Optional<Integer> failed = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(BatchWriteResponse other) {
      results(other.getResults());
      succeeded(other.getSucceeded());
      failed(other.getFailed());
      return this;
    }

    /**
     * <p>One result per item you submitted. Match each result to its request item by the <code>index</code> field, since results are not guaranteed to be in request order.</p>
     */
    @JsonSetter(
        value = "results",
        nulls = Nulls.SKIP
    )
    public Builder results(Optional<List<BatchWriteResult>> results) {
      this.results = results;
      return this;
    }

    public Builder results(List<BatchWriteResult> results) {
      this.results = Optional.ofNullable(results);
      return this;
    }

    /**
     * <p>The number of items that were created or updated.</p>
     */
    @JsonSetter(
        value = "succeeded",
        nulls = Nulls.SKIP
    )
    public Builder succeeded(Optional<Integer> succeeded) {
      this.succeeded = succeeded;
      return this;
    }

    public Builder succeeded(Integer succeeded) {
      this.succeeded = Optional.ofNullable(succeeded);
      return this;
    }

    /**
     * <p>The number of items that failed (status <code>conflict</code> or <code>invalid</code>).</p>
     */
    @JsonSetter(
        value = "failed",
        nulls = Nulls.SKIP
    )
    public Builder failed(Optional<Integer> failed) {
      this.failed = failed;
      return this;
    }

    public Builder failed(Integer failed) {
      this.failed = Optional.ofNullable(failed);
      return this;
    }

    public BatchWriteResponse build() {
      return new BatchWriteResponse(results, succeeded, failed, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
