/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BatchLookupInput.Builder.class
)
public final class BatchLookupInput {
  private final Optional<String> ref;

  private final Optional<String> type;

  private final Optional<String> field;

  private final Optional<String> value;

  private final Map<String, Object> additionalProperties;

  private BatchLookupInput(Optional<String> ref, Optional<String> type, Optional<String> field,
      Optional<String> value, Map<String, Object> additionalProperties) {
    this.ref = ref;
    this.type = type;
    this.field = field;
    this.value = value;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Your correlation id for this lookup, echoed back on the matching result group so you can pair results to inputs regardless of ordering.
   */
  @JsonProperty("ref")
  public Optional<String> getRef() {
    return ref;
  }

  /**
   * @return The record type to look up.
   */
  @JsonProperty("type")
  public Optional<String> getType() {
    return type;
  }

  /**
   * @return The name of the lookup field to match on, as declared on the record schema.
   */
  @JsonProperty("field")
  public Optional<String> getField() {
    return field;
  }

  /**
   * @return The exact value to match against the lookup field.
   */
  @JsonProperty("value")
  public Optional<String> getValue() {
    return value;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BatchLookupInput && equalTo((BatchLookupInput) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BatchLookupInput other) {
    return ref.equals(other.ref) && type.equals(other.type) && field.equals(other.field) && value.equals(other.value);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.ref, this.type, this.field, this.value);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> ref = Optional.empty();

    private Optional<String> type = Optional.empty();

    private Optional<String> field = Optional.empty();

    private Optional<String> value = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(BatchLookupInput other) {
      ref(other.getRef());
      type(other.getType());
      field(other.getField());
      value(other.getValue());
      return this;
    }

    /**
     * <p>Your correlation id for this lookup, echoed back on the matching result group so you can pair results to inputs regardless of ordering.</p>
     */
    @JsonSetter(
        value = "ref",
        nulls = Nulls.SKIP
    )
    public Builder ref(Optional<String> ref) {
      this.ref = ref;
      return this;
    }

    public Builder ref(String ref) {
      this.ref = Optional.ofNullable(ref);
      return this;
    }

    /**
     * <p>The record type to look up.</p>
     */
    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<String> type) {
      this.type = type;
      return this;
    }

    public Builder type(String type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    /**
     * <p>The name of the lookup field to match on, as declared on the record schema.</p>
     */
    @JsonSetter(
        value = "field",
        nulls = Nulls.SKIP
    )
    public Builder field(Optional<String> field) {
      this.field = field;
      return this;
    }

    public Builder field(String field) {
      this.field = Optional.ofNullable(field);
      return this;
    }

    /**
     * <p>The exact value to match against the lookup field.</p>
     */
    @JsonSetter(
        value = "value",
        nulls = Nulls.SKIP
    )
    public Builder value(Optional<String> value) {
      this.value = value;
      return this;
    }

    public Builder value(String value) {
      this.value = Optional.ofNullable(value);
      return this;
    }

    public BatchLookupInput build() {
      return new BatchLookupInput(ref, type, field, value, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
