/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ClientRequest.Builder.class
)
public final class ClientRequest {
  private final String externalId;

  private final Optional<String> name;

  private final Optional<ClientRequestStatus> status;

  private final Optional<String> orgId;

  private final Optional<Map<String, Object>> payload;

  private final Optional<String> schemaId;

  private final Map<String, Object> additionalProperties;

  private ClientRequest(String externalId, Optional<String> name,
      Optional<ClientRequestStatus> status, Optional<String> orgId,
      Optional<Map<String, Object>> payload, Optional<String> schemaId,
      Map<String, Object> additionalProperties) {
    this.externalId = externalId;
    this.name = name;
    this.status = status;
    this.orgId = orgId;
    this.payload = payload;
    this.schemaId = schemaId;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Your own unique identifier for this client. Used for idempotent create: if a client with this <code>externalId</code> already exists, it is returned instead of creating a duplicate.
   */
  @JsonProperty("externalId")
  public String getExternalId() {
    return externalId;
  }

  /**
   * @return Display name for this client.
   */
  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  /**
   * @return Lifecycle status of the client. <code>ACTIVE</code> clients can be used normally; <code>SUSPENDED</code> clients are retained but blocked from new operations. Defaults to <code>ACTIVE</code>.
   */
  @JsonProperty("status")
  public Optional<ClientRequestStatus> getStatus() {
    return status;
  }

  /**
   * @return The organization this client belongs to. Must be the Vectros-assigned UUID of an org created via <code>POST /v1/orgs</code>; use <code>GET /v1/orgs?externalId=</code> to resolve your own identifier to this UUID.
   */
  @JsonProperty("orgId")
  public Optional<String> getOrgId() {
    return orgId;
  }

  /**
   * @return Free-form key-value attributes to store with this client — handy for keeping extra data from your system without defining a schema. On update, the supplied object replaces the stored payload in full (it is not key-merged); omit it to leave the payload unchanged.
   */
  @JsonProperty("payload")
  public Optional<Map<String, Object>> getPayload() {
    return payload;
  }

  /**
   * @return Optional ID of a schema (created via <code>POST /v1/schemas</code>) that validates this client's payload and drives its lookup indexing. When set, the schema must belong to your account, the payload is validated against the schema's fields on save, and the schema's declared lookup fields become queryable via <code>GET /v1/clients?type=...&amp;field=...&amp;value=...</code>. When omitted, the payload is free-form and no lookup rows are written. On update, omit this field to leave it unchanged; once set, it cannot be cleared.
   */
  @JsonProperty("schemaId")
  public Optional<String> getSchemaId() {
    return schemaId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ClientRequest && equalTo((ClientRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ClientRequest other) {
    return externalId.equals(other.externalId) && name.equals(other.name) && status.equals(other.status) && orgId.equals(other.orgId) && payload.equals(other.payload) && schemaId.equals(other.schemaId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.externalId, this.name, this.status, this.orgId, this.payload, this.schemaId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ExternalIdStage builder() {
    return new Builder();
  }

  public interface ExternalIdStage {
    /**
     * <p>Your own unique identifier for this client. Used for idempotent create: if a client with this <code>externalId</code> already exists, it is returned instead of creating a duplicate.</p>
     */
    _FinalStage externalId(@NotNull String externalId);

    Builder from(ClientRequest other);
  }

  public interface _FinalStage {
    ClientRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Display name for this client.</p>
     */
    _FinalStage name(Optional<String> name);

    _FinalStage name(String name);

    /**
     * <p>Lifecycle status of the client. <code>ACTIVE</code> clients can be used normally; <code>SUSPENDED</code> clients are retained but blocked from new operations. Defaults to <code>ACTIVE</code>.</p>
     */
    _FinalStage status(Optional<ClientRequestStatus> status);

    _FinalStage status(ClientRequestStatus status);

    /**
     * <p>The organization this client belongs to. Must be the Vectros-assigned UUID of an org created via <code>POST /v1/orgs</code>; use <code>GET /v1/orgs?externalId=</code> to resolve your own identifier to this UUID.</p>
     */
    _FinalStage orgId(Optional<String> orgId);

    _FinalStage orgId(String orgId);

    /**
     * <p>Free-form key-value attributes to store with this client — handy for keeping extra data from your system without defining a schema. On update, the supplied object replaces the stored payload in full (it is not key-merged); omit it to leave the payload unchanged.</p>
     */
    _FinalStage payload(Optional<Map<String, Object>> payload);

    _FinalStage payload(Map<String, Object> payload);

    /**
     * <p>Optional ID of a schema (created via <code>POST /v1/schemas</code>) that validates this client's payload and drives its lookup indexing. When set, the schema must belong to your account, the payload is validated against the schema's fields on save, and the schema's declared lookup fields become queryable via <code>GET /v1/clients?type=...&amp;field=...&amp;value=...</code>. When omitted, the payload is free-form and no lookup rows are written. On update, omit this field to leave it unchanged; once set, it cannot be cleared.</p>
     */
    _FinalStage schemaId(Optional<String> schemaId);

    _FinalStage schemaId(String schemaId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ExternalIdStage, _FinalStage {
    private String externalId;

    private Optional<String> schemaId = Optional.empty();

    private Optional<Map<String, Object>> payload = Optional.empty();

    private Optional<String> orgId = Optional.empty();

    private Optional<ClientRequestStatus> status = Optional.empty();

    private Optional<String> name = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ClientRequest other) {
      externalId(other.getExternalId());
      name(other.getName());
      status(other.getStatus());
      orgId(other.getOrgId());
      payload(other.getPayload());
      schemaId(other.getSchemaId());
      return this;
    }

    /**
     * <p>Your own unique identifier for this client. Used for idempotent create: if a client with this <code>externalId</code> already exists, it is returned instead of creating a duplicate.</p>
     * <p>Your own unique identifier for this client. Used for idempotent create: if a client with this <code>externalId</code> already exists, it is returned instead of creating a duplicate.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("externalId")
    public _FinalStage externalId(@NotNull String externalId) {
      this.externalId = Objects.requireNonNull(externalId, "externalId must not be null");
      return this;
    }

    /**
     * <p>Optional ID of a schema (created via <code>POST /v1/schemas</code>) that validates this client's payload and drives its lookup indexing. When set, the schema must belong to your account, the payload is validated against the schema's fields on save, and the schema's declared lookup fields become queryable via <code>GET /v1/clients?type=...&amp;field=...&amp;value=...</code>. When omitted, the payload is free-form and no lookup rows are written. On update, omit this field to leave it unchanged; once set, it cannot be cleared.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage schemaId(String schemaId) {
      this.schemaId = Optional.ofNullable(schemaId);
      return this;
    }

    /**
     * <p>Optional ID of a schema (created via <code>POST /v1/schemas</code>) that validates this client's payload and drives its lookup indexing. When set, the schema must belong to your account, the payload is validated against the schema's fields on save, and the schema's declared lookup fields become queryable via <code>GET /v1/clients?type=...&amp;field=...&amp;value=...</code>. When omitted, the payload is free-form and no lookup rows are written. On update, omit this field to leave it unchanged; once set, it cannot be cleared.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "schemaId",
        nulls = Nulls.SKIP
    )
    public _FinalStage schemaId(Optional<String> schemaId) {
      this.schemaId = schemaId;
      return this;
    }

    /**
     * <p>Free-form key-value attributes to store with this client — handy for keeping extra data from your system without defining a schema. On update, the supplied object replaces the stored payload in full (it is not key-merged); omit it to leave the payload unchanged.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage payload(Map<String, Object> payload) {
      this.payload = Optional.ofNullable(payload);
      return this;
    }

    /**
     * <p>Free-form key-value attributes to store with this client — handy for keeping extra data from your system without defining a schema. On update, the supplied object replaces the stored payload in full (it is not key-merged); omit it to leave the payload unchanged.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "payload",
        nulls = Nulls.SKIP
    )
    public _FinalStage payload(Optional<Map<String, Object>> payload) {
      this.payload = payload;
      return this;
    }

    /**
     * <p>The organization this client belongs to. Must be the Vectros-assigned UUID of an org created via <code>POST /v1/orgs</code>; use <code>GET /v1/orgs?externalId=</code> to resolve your own identifier to this UUID.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage orgId(String orgId) {
      this.orgId = Optional.ofNullable(orgId);
      return this;
    }

    /**
     * <p>The organization this client belongs to. Must be the Vectros-assigned UUID of an org created via <code>POST /v1/orgs</code>; use <code>GET /v1/orgs?externalId=</code> to resolve your own identifier to this UUID.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "orgId",
        nulls = Nulls.SKIP
    )
    public _FinalStage orgId(Optional<String> orgId) {
      this.orgId = orgId;
      return this;
    }

    /**
     * <p>Lifecycle status of the client. <code>ACTIVE</code> clients can be used normally; <code>SUSPENDED</code> clients are retained but blocked from new operations. Defaults to <code>ACTIVE</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage status(ClientRequestStatus status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    /**
     * <p>Lifecycle status of the client. <code>ACTIVE</code> clients can be used normally; <code>SUSPENDED</code> clients are retained but blocked from new operations. Defaults to <code>ACTIVE</code>.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public _FinalStage status(Optional<ClientRequestStatus> status) {
      this.status = status;
      return this;
    }

    /**
     * <p>Display name for this client.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    /**
     * <p>Display name for this client.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public _FinalStage name(Optional<String> name) {
      this.name = name;
      return this;
    }

    @java.lang.Override
    public ClientRequest build() {
      return new ClientRequest(externalId, name, status, orgId, payload, schemaId, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
