/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ContextDetail.Builder.class
)
public final class ContextDetail {
  private final Optional<String> contextId;

  private final Optional<String> tenantId;

  private final Optional<String> tenantMode;

  private final Optional<TenantCredits> credits;

  private final Optional<SearchSection> search;

  private final Optional<DocumentsSection> documents;

  private final Optional<RecordsSection> records;

  private final Optional<TenantInferenceSection> inference;

  private final Map<String, Object> additionalProperties;

  private ContextDetail(Optional<String> contextId, Optional<String> tenantId,
      Optional<String> tenantMode, Optional<TenantCredits> credits, Optional<SearchSection> search,
      Optional<DocumentsSection> documents, Optional<RecordsSection> records,
      Optional<TenantInferenceSection> inference, Map<String, Object> additionalProperties) {
    this.contextId = contextId;
    this.tenantId = tenantId;
    this.tenantMode = tenantMode;
    this.credits = credits;
    this.search = search;
    this.documents = documents;
    this.records = records;
    this.inference = inference;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return AppContext id (the contextId data is partitioned under).
   */
  @JsonProperty("contextId")
  public Optional<String> getContextId() {
    return contextId;
  }

  /**
   * @return Your account (tenant) id for the environment this context belongs to, as a UUID.
   */
  @JsonProperty("tenantId")
  public Optional<String> getTenantId() {
    return tenantId;
  }

  /**
   * @return Environment of the owning account: &quot;live&quot; or &quot;test&quot;.
   */
  @JsonProperty("tenantMode")
  public Optional<String> getTenantMode() {
    return tenantMode;
  }

  @JsonProperty("credits")
  public Optional<TenantCredits> getCredits() {
    return credits;
  }

  @JsonProperty("search")
  public Optional<SearchSection> getSearch() {
    return search;
  }

  @JsonProperty("documents")
  public Optional<DocumentsSection> getDocuments() {
    return documents;
  }

  @JsonProperty("records")
  public Optional<RecordsSection> getRecords() {
    return records;
  }

  @JsonProperty("inference")
  public Optional<TenantInferenceSection> getInference() {
    return inference;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ContextDetail && equalTo((ContextDetail) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ContextDetail other) {
    return contextId.equals(other.contextId) && tenantId.equals(other.tenantId) && tenantMode.equals(other.tenantMode) && credits.equals(other.credits) && search.equals(other.search) && documents.equals(other.documents) && records.equals(other.records) && inference.equals(other.inference);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.contextId, this.tenantId, this.tenantMode, this.credits, this.search, this.documents, this.records, this.inference);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> contextId = Optional.empty();

    private Optional<String> tenantId = Optional.empty();

    private Optional<String> tenantMode = Optional.empty();

    private Optional<TenantCredits> credits = Optional.empty();

    private Optional<SearchSection> search = Optional.empty();

    private Optional<DocumentsSection> documents = Optional.empty();

    private Optional<RecordsSection> records = Optional.empty();

    private Optional<TenantInferenceSection> inference = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ContextDetail other) {
      contextId(other.getContextId());
      tenantId(other.getTenantId());
      tenantMode(other.getTenantMode());
      credits(other.getCredits());
      search(other.getSearch());
      documents(other.getDocuments());
      records(other.getRecords());
      inference(other.getInference());
      return this;
    }

    /**
     * <p>AppContext id (the contextId data is partitioned under).</p>
     */
    @JsonSetter(
        value = "contextId",
        nulls = Nulls.SKIP
    )
    public Builder contextId(Optional<String> contextId) {
      this.contextId = contextId;
      return this;
    }

    public Builder contextId(String contextId) {
      this.contextId = Optional.ofNullable(contextId);
      return this;
    }

    /**
     * <p>Your account (tenant) id for the environment this context belongs to, as a UUID.</p>
     */
    @JsonSetter(
        value = "tenantId",
        nulls = Nulls.SKIP
    )
    public Builder tenantId(Optional<String> tenantId) {
      this.tenantId = tenantId;
      return this;
    }

    public Builder tenantId(String tenantId) {
      this.tenantId = Optional.ofNullable(tenantId);
      return this;
    }

    /**
     * <p>Environment of the owning account: &quot;live&quot; or &quot;test&quot;.</p>
     */
    @JsonSetter(
        value = "tenantMode",
        nulls = Nulls.SKIP
    )
    public Builder tenantMode(Optional<String> tenantMode) {
      this.tenantMode = tenantMode;
      return this;
    }

    public Builder tenantMode(String tenantMode) {
      this.tenantMode = Optional.ofNullable(tenantMode);
      return this;
    }

    @JsonSetter(
        value = "credits",
        nulls = Nulls.SKIP
    )
    public Builder credits(Optional<TenantCredits> credits) {
      this.credits = credits;
      return this;
    }

    public Builder credits(TenantCredits credits) {
      this.credits = Optional.ofNullable(credits);
      return this;
    }

    @JsonSetter(
        value = "search",
        nulls = Nulls.SKIP
    )
    public Builder search(Optional<SearchSection> search) {
      this.search = search;
      return this;
    }

    public Builder search(SearchSection search) {
      this.search = Optional.ofNullable(search);
      return this;
    }

    @JsonSetter(
        value = "documents",
        nulls = Nulls.SKIP
    )
    public Builder documents(Optional<DocumentsSection> documents) {
      this.documents = documents;
      return this;
    }

    public Builder documents(DocumentsSection documents) {
      this.documents = Optional.ofNullable(documents);
      return this;
    }

    @JsonSetter(
        value = "records",
        nulls = Nulls.SKIP
    )
    public Builder records(Optional<RecordsSection> records) {
      this.records = records;
      return this;
    }

    public Builder records(RecordsSection records) {
      this.records = Optional.ofNullable(records);
      return this;
    }

    @JsonSetter(
        value = "inference",
        nulls = Nulls.SKIP
    )
    public Builder inference(Optional<TenantInferenceSection> inference) {
      this.inference = inference;
      return this;
    }

    public Builder inference(TenantInferenceSection inference) {
      this.inference = Optional.ofNullable(inference);
      return this;
    }

    public ContextDetail build() {
      return new ContextDetail(contextId, tenantId, tenantMode, credits, search, documents, records, inference, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
