/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CountAndCredits.Builder.class
)
public final class CountAndCredits {
  private final Optional<Long> count;

  private final Optional<Long> credits;

  private final Optional<Long> creditsMilli;

  private final Map<String, Object> additionalProperties;

  private CountAndCredits(Optional<Long> count, Optional<Long> credits, Optional<Long> creditsMilli,
      Map<String, Object> additionalProperties) {
    this.count = count;
    this.credits = credits;
    this.creditsMilli = creditsMilli;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Number of operations this period
   */
  @JsonProperty("count")
  public Optional<Long> getCount() {
    return count;
  }

  /**
   * @return Credits charged for these operations (rounded down)
   */
  @JsonProperty("credits")
  public Optional<Long> getCredits() {
    return credits;
  }

  /**
   * @return credits in milli-credit precision (exact, 1 credit = 1000 milli-credits)
   */
  @JsonProperty("creditsMilli")
  public Optional<Long> getCreditsMilli() {
    return creditsMilli;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CountAndCredits && equalTo((CountAndCredits) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CountAndCredits other) {
    return count.equals(other.count) && credits.equals(other.credits) && creditsMilli.equals(other.creditsMilli);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.count, this.credits, this.creditsMilli);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Long> count = Optional.empty();

    private Optional<Long> credits = Optional.empty();

    private Optional<Long> creditsMilli = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CountAndCredits other) {
      count(other.getCount());
      credits(other.getCredits());
      creditsMilli(other.getCreditsMilli());
      return this;
    }

    /**
     * <p>Number of operations this period</p>
     */
    @JsonSetter(
        value = "count",
        nulls = Nulls.SKIP
    )
    public Builder count(Optional<Long> count) {
      this.count = count;
      return this;
    }

    public Builder count(Long count) {
      this.count = Optional.ofNullable(count);
      return this;
    }

    /**
     * <p>Credits charged for these operations (rounded down)</p>
     */
    @JsonSetter(
        value = "credits",
        nulls = Nulls.SKIP
    )
    public Builder credits(Optional<Long> credits) {
      this.credits = credits;
      return this;
    }

    public Builder credits(Long credits) {
      this.credits = Optional.ofNullable(credits);
      return this;
    }

    /**
     * <p>credits in milli-credit precision (exact, 1 credit = 1000 milli-credits)</p>
     */
    @JsonSetter(
        value = "creditsMilli",
        nulls = Nulls.SKIP
    )
    public Builder creditsMilli(Optional<Long> creditsMilli) {
      this.creditsMilli = creditsMilli;
      return this;
    }

    public Builder creditsMilli(Long creditsMilli) {
      this.creditsMilli = Optional.ofNullable(creditsMilli);
      return this;
    }

    public CountAndCredits build() {
      return new CountAndCredits(count, credits, creditsMilli, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
