/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateInviteRequest.Builder.class
)
public final class CreateInviteRequest {
  private final String email;

  private final String contextId;

  private final AccessProfileSpec accessProfile;

  private final Optional<String> firstName;

  private final Optional<String> lastName;

  private final Optional<String> acceptUrl;

  private final Optional<String> fromName;

  private final Optional<Long> ttlSeconds;

  private final Optional<Boolean> sendEmail;

  private final Map<String, Object> additionalProperties;

  private CreateInviteRequest(String email, String contextId, AccessProfileSpec accessProfile,
      Optional<String> firstName, Optional<String> lastName, Optional<String> acceptUrl,
      Optional<String> fromName, Optional<Long> ttlSeconds, Optional<Boolean> sendEmail,
      Map<String, Object> additionalProperties) {
    this.email = email;
    this.contextId = contextId;
    this.accessProfile = accessProfile;
    this.firstName = firstName;
    this.lastName = lastName;
    this.acceptUrl = acceptUrl;
    this.fromName = fromName;
    this.ttlSeconds = ttlSeconds;
    this.sendEmail = sendEmail;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Email address to invite. Must be a valid email address. If it already belongs to an active or suspended member of this app context the request is rejected; if it already has a pending invitation in this app context, that invitation is resent with a fresh token instead of a new one being created.
   */
  @JsonProperty("email")
  public String getEmail() {
    return email;
  }

  /**
   * @return The app context the new member will operate in. Must reference an existing app context in your account. The invitee's access profile is bound to this context.
   */
  @JsonProperty("contextId")
  public String getContextId() {
    return contextId;
  }

  @JsonProperty("accessProfile")
  public AccessProfileSpec getAccessProfile() {
    return accessProfile;
  }

  /**
   * @return Invitee's first name. Optional; used to personalize the invitation email greeting.
   */
  @JsonProperty("firstName")
  public Optional<String> getFirstName() {
    return firstName;
  }

  /**
   * @return Invitee's last name. Optional; accepted but not currently stored or returned.
   */
  @JsonProperty("lastName")
  public Optional<String> getLastName() {
    return lastName;
  }

  /**
   * @return Your landing page where the invitee accepts the invitation. Required when <code>sendEmail</code> is true. The invitation token is appended as a <code>t</code> query parameter. Must be an https URL with a domain-name host (IP-literal hosts are rejected).
   */
  @JsonProperty("acceptUrl")
  public Optional<String> getAcceptUrl() {
    return acceptUrl;
  }

  /**
   * @return Display name shown in the From header of the invitation email. Defaults to <code>Vectros</code>. Maximum 100 characters; must not contain newlines.
   */
  @JsonProperty("fromName")
  public Optional<String> getFromName() {
    return fromName;
  }

  /**
   * @return How long the invitation token stays valid, in seconds. Defaults to 604800 (7 days). Must be between 3600 (1 hour) and 2592000 (30 days).
   */
  @JsonProperty("ttlSeconds")
  public Optional<Long> getTtlSeconds() {
    return ttlSeconds;
  }

  /**
   * @return Whether Vectros should deliver the invitation email for you. When true (the default), the email is sent on your behalf. When false, no email is sent and the response instead returns the raw token and a ready-to-use accept link so you can deliver the invitation through your own email provider.
   */
  @JsonProperty("sendEmail")
  public Optional<Boolean> getSendEmail() {
    return sendEmail;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateInviteRequest && equalTo((CreateInviteRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateInviteRequest other) {
    return email.equals(other.email) && contextId.equals(other.contextId) && accessProfile.equals(other.accessProfile) && firstName.equals(other.firstName) && lastName.equals(other.lastName) && acceptUrl.equals(other.acceptUrl) && fromName.equals(other.fromName) && ttlSeconds.equals(other.ttlSeconds) && sendEmail.equals(other.sendEmail);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.email, this.contextId, this.accessProfile, this.firstName, this.lastName, this.acceptUrl, this.fromName, this.ttlSeconds, this.sendEmail);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static EmailStage builder() {
    return new Builder();
  }

  public interface EmailStage {
    /**
     * <p>Email address to invite. Must be a valid email address. If it already belongs to an active or suspended member of this app context the request is rejected; if it already has a pending invitation in this app context, that invitation is resent with a fresh token instead of a new one being created.</p>
     */
    ContextIdStage email(@NotNull String email);

    Builder from(CreateInviteRequest other);
  }

  public interface ContextIdStage {
    /**
     * <p>The app context the new member will operate in. Must reference an existing app context in your account. The invitee's access profile is bound to this context.</p>
     */
    AccessProfileStage contextId(@NotNull String contextId);
  }

  public interface AccessProfileStage {
    _FinalStage accessProfile(@NotNull AccessProfileSpec accessProfile);
  }

  public interface _FinalStage {
    CreateInviteRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Invitee's first name. Optional; used to personalize the invitation email greeting.</p>
     */
    _FinalStage firstName(Optional<String> firstName);

    _FinalStage firstName(String firstName);

    /**
     * <p>Invitee's last name. Optional; accepted but not currently stored or returned.</p>
     */
    _FinalStage lastName(Optional<String> lastName);

    _FinalStage lastName(String lastName);

    /**
     * <p>Your landing page where the invitee accepts the invitation. Required when <code>sendEmail</code> is true. The invitation token is appended as a <code>t</code> query parameter. Must be an https URL with a domain-name host (IP-literal hosts are rejected).</p>
     */
    _FinalStage acceptUrl(Optional<String> acceptUrl);

    _FinalStage acceptUrl(String acceptUrl);

    /**
     * <p>Display name shown in the From header of the invitation email. Defaults to <code>Vectros</code>. Maximum 100 characters; must not contain newlines.</p>
     */
    _FinalStage fromName(Optional<String> fromName);

    _FinalStage fromName(String fromName);

    /**
     * <p>How long the invitation token stays valid, in seconds. Defaults to 604800 (7 days). Must be between 3600 (1 hour) and 2592000 (30 days).</p>
     */
    _FinalStage ttlSeconds(Optional<Long> ttlSeconds);

    _FinalStage ttlSeconds(Long ttlSeconds);

    /**
     * <p>Whether Vectros should deliver the invitation email for you. When true (the default), the email is sent on your behalf. When false, no email is sent and the response instead returns the raw token and a ready-to-use accept link so you can deliver the invitation through your own email provider.</p>
     */
    _FinalStage sendEmail(Optional<Boolean> sendEmail);

    _FinalStage sendEmail(Boolean sendEmail);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements EmailStage, ContextIdStage, AccessProfileStage, _FinalStage {
    private String email;

    private String contextId;

    private AccessProfileSpec accessProfile;

    private Optional<Boolean> sendEmail = Optional.empty();

    private Optional<Long> ttlSeconds = Optional.empty();

    private Optional<String> fromName = Optional.empty();

    private Optional<String> acceptUrl = Optional.empty();

    private Optional<String> lastName = Optional.empty();

    private Optional<String> firstName = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateInviteRequest other) {
      email(other.getEmail());
      contextId(other.getContextId());
      accessProfile(other.getAccessProfile());
      firstName(other.getFirstName());
      lastName(other.getLastName());
      acceptUrl(other.getAcceptUrl());
      fromName(other.getFromName());
      ttlSeconds(other.getTtlSeconds());
      sendEmail(other.getSendEmail());
      return this;
    }

    /**
     * <p>Email address to invite. Must be a valid email address. If it already belongs to an active or suspended member of this app context the request is rejected; if it already has a pending invitation in this app context, that invitation is resent with a fresh token instead of a new one being created.</p>
     * <p>Email address to invite. Must be a valid email address. If it already belongs to an active or suspended member of this app context the request is rejected; if it already has a pending invitation in this app context, that invitation is resent with a fresh token instead of a new one being created.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("email")
    public ContextIdStage email(@NotNull String email) {
      this.email = Objects.requireNonNull(email, "email must not be null");
      return this;
    }

    /**
     * <p>The app context the new member will operate in. Must reference an existing app context in your account. The invitee's access profile is bound to this context.</p>
     * <p>The app context the new member will operate in. Must reference an existing app context in your account. The invitee's access profile is bound to this context.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("contextId")
    public AccessProfileStage contextId(@NotNull String contextId) {
      this.contextId = Objects.requireNonNull(contextId, "contextId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("accessProfile")
    public _FinalStage accessProfile(@NotNull AccessProfileSpec accessProfile) {
      this.accessProfile = Objects.requireNonNull(accessProfile, "accessProfile must not be null");
      return this;
    }

    /**
     * <p>Whether Vectros should deliver the invitation email for you. When true (the default), the email is sent on your behalf. When false, no email is sent and the response instead returns the raw token and a ready-to-use accept link so you can deliver the invitation through your own email provider.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage sendEmail(Boolean sendEmail) {
      this.sendEmail = Optional.ofNullable(sendEmail);
      return this;
    }

    /**
     * <p>Whether Vectros should deliver the invitation email for you. When true (the default), the email is sent on your behalf. When false, no email is sent and the response instead returns the raw token and a ready-to-use accept link so you can deliver the invitation through your own email provider.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "sendEmail",
        nulls = Nulls.SKIP
    )
    public _FinalStage sendEmail(Optional<Boolean> sendEmail) {
      this.sendEmail = sendEmail;
      return this;
    }

    /**
     * <p>How long the invitation token stays valid, in seconds. Defaults to 604800 (7 days). Must be between 3600 (1 hour) and 2592000 (30 days).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage ttlSeconds(Long ttlSeconds) {
      this.ttlSeconds = Optional.ofNullable(ttlSeconds);
      return this;
    }

    /**
     * <p>How long the invitation token stays valid, in seconds. Defaults to 604800 (7 days). Must be between 3600 (1 hour) and 2592000 (30 days).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "ttlSeconds",
        nulls = Nulls.SKIP
    )
    public _FinalStage ttlSeconds(Optional<Long> ttlSeconds) {
      this.ttlSeconds = ttlSeconds;
      return this;
    }

    /**
     * <p>Display name shown in the From header of the invitation email. Defaults to <code>Vectros</code>. Maximum 100 characters; must not contain newlines.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage fromName(String fromName) {
      this.fromName = Optional.ofNullable(fromName);
      return this;
    }

    /**
     * <p>Display name shown in the From header of the invitation email. Defaults to <code>Vectros</code>. Maximum 100 characters; must not contain newlines.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "fromName",
        nulls = Nulls.SKIP
    )
    public _FinalStage fromName(Optional<String> fromName) {
      this.fromName = fromName;
      return this;
    }

    /**
     * <p>Your landing page where the invitee accepts the invitation. Required when <code>sendEmail</code> is true. The invitation token is appended as a <code>t</code> query parameter. Must be an https URL with a domain-name host (IP-literal hosts are rejected).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage acceptUrl(String acceptUrl) {
      this.acceptUrl = Optional.ofNullable(acceptUrl);
      return this;
    }

    /**
     * <p>Your landing page where the invitee accepts the invitation. Required when <code>sendEmail</code> is true. The invitation token is appended as a <code>t</code> query parameter. Must be an https URL with a domain-name host (IP-literal hosts are rejected).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "acceptUrl",
        nulls = Nulls.SKIP
    )
    public _FinalStage acceptUrl(Optional<String> acceptUrl) {
      this.acceptUrl = acceptUrl;
      return this;
    }

    /**
     * <p>Invitee's last name. Optional; accepted but not currently stored or returned.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage lastName(String lastName) {
      this.lastName = Optional.ofNullable(lastName);
      return this;
    }

    /**
     * <p>Invitee's last name. Optional; accepted but not currently stored or returned.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "lastName",
        nulls = Nulls.SKIP
    )
    public _FinalStage lastName(Optional<String> lastName) {
      this.lastName = lastName;
      return this;
    }

    /**
     * <p>Invitee's first name. Optional; used to personalize the invitation email greeting.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage firstName(String firstName) {
      this.firstName = Optional.ofNullable(firstName);
      return this;
    }

    /**
     * <p>Invitee's first name. Optional; used to personalize the invitation email greeting.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "firstName",
        nulls = Nulls.SKIP
    )
    public _FinalStage firstName(Optional<String> firstName) {
      this.firstName = firstName;
      return this;
    }

    @java.lang.Override
    public CreateInviteRequest build() {
      return new CreateInviteRequest(email, contextId, accessProfile, firstName, lastName, acceptUrl, fromName, ttlSeconds, sendEmail, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
