/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.Nullable;
import ai.vectros.core.NullableNonemptyFilter;
import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = Credits.Builder.class
)
public final class Credits {
  private final Optional<Long> used;

  private final Optional<Long> usedMilli;

  private final Optional<Long> limit;

  private final Optional<Long> remaining;

  private final Optional<CreditBreakdown> breakdown;

  private final Map<String, Object> additionalProperties;

  private Credits(Optional<Long> used, Optional<Long> usedMilli, Optional<Long> limit,
      Optional<Long> remaining, Optional<CreditBreakdown> breakdown,
      Map<String, Object> additionalProperties) {
    this.used = used;
    this.usedMilli = usedMilli;
    this.limit = limit;
    this.remaining = remaining;
    this.breakdown = breakdown;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Credits consumed this period (rounded down to whole credits)
   */
  @JsonProperty("used")
  public Optional<Long> getUsed() {
    return used;
  }

  /**
   * @return Credits consumed this period in milli-credit precision (1 credit = 1000 milli-credits). Use this for exact accounting and for cross-checking per-environment totals — the rounded <code>used</code> value can differ from <code>live.used + test.used</code> by up to 1 credit per category due to independent truncation. The milli value is exact.
   */
  @JsonProperty("usedMilli")
  public Optional<Long> getUsedMilli() {
    return usedMilli;
  }

  /**
   * @return Plan monthly credit limit. Null for unlimited (enterprise) plans.
   */
  @JsonIgnore
  public Optional<Long> getLimit() {
    if (limit == null) {
      return Optional.empty();
    }
    return limit;
  }

  /**
   * @return Remaining credits before plan limit hit. Null for unlimited plans.
   */
  @JsonIgnore
  public Optional<Long> getRemaining() {
    if (remaining == null) {
      return Optional.empty();
    }
    return remaining;
  }

  @JsonProperty("breakdown")
  public Optional<CreditBreakdown> getBreakdown() {
    return breakdown;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("limit")
  private Optional<Long> _getLimit() {
    return limit;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("remaining")
  private Optional<Long> _getRemaining() {
    return remaining;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Credits && equalTo((Credits) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(Credits other) {
    return used.equals(other.used) && usedMilli.equals(other.usedMilli) && limit.equals(other.limit) && remaining.equals(other.remaining) && breakdown.equals(other.breakdown);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.used, this.usedMilli, this.limit, this.remaining, this.breakdown);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Long> used = Optional.empty();

    private Optional<Long> usedMilli = Optional.empty();

    private Optional<Long> limit = Optional.empty();

    private Optional<Long> remaining = Optional.empty();

    private Optional<CreditBreakdown> breakdown = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(Credits other) {
      used(other.getUsed());
      usedMilli(other.getUsedMilli());
      limit(other.getLimit());
      remaining(other.getRemaining());
      breakdown(other.getBreakdown());
      return this;
    }

    /**
     * <p>Credits consumed this period (rounded down to whole credits)</p>
     */
    @JsonSetter(
        value = "used",
        nulls = Nulls.SKIP
    )
    public Builder used(Optional<Long> used) {
      this.used = used;
      return this;
    }

    public Builder used(Long used) {
      this.used = Optional.ofNullable(used);
      return this;
    }

    /**
     * <p>Credits consumed this period in milli-credit precision (1 credit = 1000 milli-credits). Use this for exact accounting and for cross-checking per-environment totals — the rounded <code>used</code> value can differ from <code>live.used + test.used</code> by up to 1 credit per category due to independent truncation. The milli value is exact.</p>
     */
    @JsonSetter(
        value = "usedMilli",
        nulls = Nulls.SKIP
    )
    public Builder usedMilli(Optional<Long> usedMilli) {
      this.usedMilli = usedMilli;
      return this;
    }

    public Builder usedMilli(Long usedMilli) {
      this.usedMilli = Optional.ofNullable(usedMilli);
      return this;
    }

    /**
     * <p>Plan monthly credit limit. Null for unlimited (enterprise) plans.</p>
     */
    @JsonSetter(
        value = "limit",
        nulls = Nulls.SKIP
    )
    public Builder limit(Optional<Long> limit) {
      this.limit = limit;
      return this;
    }

    public Builder limit(Long limit) {
      this.limit = Optional.ofNullable(limit);
      return this;
    }

    public Builder limit(Nullable<Long> limit) {
      if (limit.isNull()) {
        this.limit = null;
      }
      else if (limit.isEmpty()) {
        this.limit = Optional.empty();
      }
      else {
        this.limit = Optional.of(limit.get());
      }
      return this;
    }

    /**
     * <p>Remaining credits before plan limit hit. Null for unlimited plans.</p>
     */
    @JsonSetter(
        value = "remaining",
        nulls = Nulls.SKIP
    )
    public Builder remaining(Optional<Long> remaining) {
      this.remaining = remaining;
      return this;
    }

    public Builder remaining(Long remaining) {
      this.remaining = Optional.ofNullable(remaining);
      return this;
    }

    public Builder remaining(Nullable<Long> remaining) {
      if (remaining.isNull()) {
        this.remaining = null;
      }
      else if (remaining.isEmpty()) {
        this.remaining = Optional.empty();
      }
      else {
        this.remaining = Optional.of(remaining.get());
      }
      return this;
    }

    @JsonSetter(
        value = "breakdown",
        nulls = Nulls.SKIP
    )
    public Builder breakdown(Optional<CreditBreakdown> breakdown) {
      this.breakdown = breakdown;
      return this;
    }

    public Builder breakdown(CreditBreakdown breakdown) {
      this.breakdown = Optional.ofNullable(breakdown);
      return this;
    }

    public Credits build() {
      return new Credits(used, usedMilli, limit, remaining, breakdown, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
