/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class DocumentContextEventEvent {
  public static final DocumentContextEventEvent DOCUMENT_CONTEXT = new DocumentContextEventEvent(Value.DOCUMENT_CONTEXT, "document_context");

  private final Value value;

  private final String string;

  DocumentContextEventEvent(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof DocumentContextEventEvent && this.string.equals(((DocumentContextEventEvent) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case DOCUMENT_CONTEXT:
        return visitor.visitDocumentContext();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static DocumentContextEventEvent valueOf(String value) {
    switch (value) {
      case "document_context":
        return DOCUMENT_CONTEXT;
      default:
        return new DocumentContextEventEvent(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    DOCUMENT_CONTEXT,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitDocumentContext();

    T visitUnknown(String unknownType);
  }
}
