/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DoneEvent.Builder.class
)
public final class DoneEvent {
  private final DoneEventEvent event;

  private final int inputTokens;

  private final int outputTokens;

  private final String model;

  private final double platformCreditsCharged;

  private final long inferenceBalanceCentsCharged;

  private final Optional<Integer> cacheReadTokens;

  private final Optional<Integer> cacheCreateTokens;

  private final Map<String, Object> additionalProperties;

  private DoneEvent(DoneEventEvent event, int inputTokens, int outputTokens, String model,
      double platformCreditsCharged, long inferenceBalanceCentsCharged,
      Optional<Integer> cacheReadTokens, Optional<Integer> cacheCreateTokens,
      Map<String, Object> additionalProperties) {
    this.event = event;
    this.inputTokens = inputTokens;
    this.outputTokens = outputTokens;
    this.model = model;
    this.platformCreditsCharged = platformCreditsCharged;
    this.inferenceBalanceCentsCharged = inferenceBalanceCentsCharged;
    this.cacheReadTokens = cacheReadTokens;
    this.cacheCreateTokens = cacheCreateTokens;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Backward-compatible alias of <code>type</code>. Always <code>done</code>.
   */
  @JsonProperty("event")
  public DoneEventEvent getEvent() {
    return event;
  }

  /**
   * @return Total input tokens consumed by the model, including the system prompt and all messages.
   */
  @JsonProperty("inputTokens")
  public int getInputTokens() {
    return inputTokens;
  }

  /**
   * @return Total output tokens generated by the model.
   */
  @JsonProperty("outputTokens")
  public int getOutputTokens() {
    return outputTokens;
  }

  /**
   * @return The model alias used for this call.
   */
  @JsonProperty("model")
  public String getModel() {
    return model;
  }

  /**
   * @return Credits debited from your monthly plan allowance for this call's per-call platform overhead. One credit equals one cent.
   */
  @JsonProperty("platformCreditsCharged")
  public double getPlatformCreditsCharged() {
    return platformCreditsCharged;
  }

  /**
   * @return Cents debited from your pre-paid inference balance for the model's token cost.
   */
  @JsonProperty("inferenceBalanceCentsCharged")
  public long getInferenceBalanceCentsCharged() {
    return inferenceBalanceCentsCharged;
  }

  /**
   * @return Number of input tokens served from the prompt cache. Present only when prompt caching applied to this call. Prompt caching is not yet used; this field is reserved for forward compatibility.
   */
  @JsonProperty("cacheReadTokens")
  public Optional<Integer> getCacheReadTokens() {
    return cacheReadTokens;
  }

  /**
   * @return Number of tokens written to the prompt cache. Present only when prompt caching applied to this call. Prompt caching is not yet used; this field is reserved for forward compatibility.
   */
  @JsonProperty("cacheCreateTokens")
  public Optional<Integer> getCacheCreateTokens() {
    return cacheCreateTokens;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DoneEvent && equalTo((DoneEvent) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DoneEvent other) {
    return event.equals(other.event) && inputTokens == other.inputTokens && outputTokens == other.outputTokens && model.equals(other.model) && platformCreditsCharged == other.platformCreditsCharged && inferenceBalanceCentsCharged == other.inferenceBalanceCentsCharged && cacheReadTokens.equals(other.cacheReadTokens) && cacheCreateTokens.equals(other.cacheCreateTokens);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.event, this.inputTokens, this.outputTokens, this.model, this.platformCreditsCharged, this.inferenceBalanceCentsCharged, this.cacheReadTokens, this.cacheCreateTokens);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static EventStage builder() {
    return new Builder();
  }

  public interface EventStage {
    /**
     * <p>Backward-compatible alias of <code>type</code>. Always <code>done</code>.</p>
     */
    InputTokensStage event(@NotNull DoneEventEvent event);

    Builder from(DoneEvent other);
  }

  public interface InputTokensStage {
    /**
     * <p>Total input tokens consumed by the model, including the system prompt and all messages.</p>
     */
    OutputTokensStage inputTokens(int inputTokens);
  }

  public interface OutputTokensStage {
    /**
     * <p>Total output tokens generated by the model.</p>
     */
    ModelStage outputTokens(int outputTokens);
  }

  public interface ModelStage {
    /**
     * <p>The model alias used for this call.</p>
     */
    PlatformCreditsChargedStage model(@NotNull String model);
  }

  public interface PlatformCreditsChargedStage {
    /**
     * <p>Credits debited from your monthly plan allowance for this call's per-call platform overhead. One credit equals one cent.</p>
     */
    InferenceBalanceCentsChargedStage platformCreditsCharged(double platformCreditsCharged);
  }

  public interface InferenceBalanceCentsChargedStage {
    /**
     * <p>Cents debited from your pre-paid inference balance for the model's token cost.</p>
     */
    _FinalStage inferenceBalanceCentsCharged(long inferenceBalanceCentsCharged);
  }

  public interface _FinalStage {
    DoneEvent build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Number of input tokens served from the prompt cache. Present only when prompt caching applied to this call. Prompt caching is not yet used; this field is reserved for forward compatibility.</p>
     */
    _FinalStage cacheReadTokens(Optional<Integer> cacheReadTokens);

    _FinalStage cacheReadTokens(Integer cacheReadTokens);

    /**
     * <p>Number of tokens written to the prompt cache. Present only when prompt caching applied to this call. Prompt caching is not yet used; this field is reserved for forward compatibility.</p>
     */
    _FinalStage cacheCreateTokens(Optional<Integer> cacheCreateTokens);

    _FinalStage cacheCreateTokens(Integer cacheCreateTokens);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements EventStage, InputTokensStage, OutputTokensStage, ModelStage, PlatformCreditsChargedStage, InferenceBalanceCentsChargedStage, _FinalStage {
    private DoneEventEvent event;

    private int inputTokens;

    private int outputTokens;

    private String model;

    private double platformCreditsCharged;

    private long inferenceBalanceCentsCharged;

    private Optional<Integer> cacheCreateTokens = Optional.empty();

    private Optional<Integer> cacheReadTokens = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(DoneEvent other) {
      event(other.getEvent());
      inputTokens(other.getInputTokens());
      outputTokens(other.getOutputTokens());
      model(other.getModel());
      platformCreditsCharged(other.getPlatformCreditsCharged());
      inferenceBalanceCentsCharged(other.getInferenceBalanceCentsCharged());
      cacheReadTokens(other.getCacheReadTokens());
      cacheCreateTokens(other.getCacheCreateTokens());
      return this;
    }

    /**
     * <p>Backward-compatible alias of <code>type</code>. Always <code>done</code>.</p>
     * <p>Backward-compatible alias of <code>type</code>. Always <code>done</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("event")
    public InputTokensStage event(@NotNull DoneEventEvent event) {
      this.event = Objects.requireNonNull(event, "event must not be null");
      return this;
    }

    /**
     * <p>Total input tokens consumed by the model, including the system prompt and all messages.</p>
     * <p>Total input tokens consumed by the model, including the system prompt and all messages.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("inputTokens")
    public OutputTokensStage inputTokens(int inputTokens) {
      this.inputTokens = inputTokens;
      return this;
    }

    /**
     * <p>Total output tokens generated by the model.</p>
     * <p>Total output tokens generated by the model.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("outputTokens")
    public ModelStage outputTokens(int outputTokens) {
      this.outputTokens = outputTokens;
      return this;
    }

    /**
     * <p>The model alias used for this call.</p>
     * <p>The model alias used for this call.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("model")
    public PlatformCreditsChargedStage model(@NotNull String model) {
      this.model = Objects.requireNonNull(model, "model must not be null");
      return this;
    }

    /**
     * <p>Credits debited from your monthly plan allowance for this call's per-call platform overhead. One credit equals one cent.</p>
     * <p>Credits debited from your monthly plan allowance for this call's per-call platform overhead. One credit equals one cent.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("platformCreditsCharged")
    public InferenceBalanceCentsChargedStage platformCreditsCharged(double platformCreditsCharged) {
      this.platformCreditsCharged = platformCreditsCharged;
      return this;
    }

    /**
     * <p>Cents debited from your pre-paid inference balance for the model's token cost.</p>
     * <p>Cents debited from your pre-paid inference balance for the model's token cost.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("inferenceBalanceCentsCharged")
    public _FinalStage inferenceBalanceCentsCharged(long inferenceBalanceCentsCharged) {
      this.inferenceBalanceCentsCharged = inferenceBalanceCentsCharged;
      return this;
    }

    /**
     * <p>Number of tokens written to the prompt cache. Present only when prompt caching applied to this call. Prompt caching is not yet used; this field is reserved for forward compatibility.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage cacheCreateTokens(Integer cacheCreateTokens) {
      this.cacheCreateTokens = Optional.ofNullable(cacheCreateTokens);
      return this;
    }

    /**
     * <p>Number of tokens written to the prompt cache. Present only when prompt caching applied to this call. Prompt caching is not yet used; this field is reserved for forward compatibility.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "cacheCreateTokens",
        nulls = Nulls.SKIP
    )
    public _FinalStage cacheCreateTokens(Optional<Integer> cacheCreateTokens) {
      this.cacheCreateTokens = cacheCreateTokens;
      return this;
    }

    /**
     * <p>Number of input tokens served from the prompt cache. Present only when prompt caching applied to this call. Prompt caching is not yet used; this field is reserved for forward compatibility.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage cacheReadTokens(Integer cacheReadTokens) {
      this.cacheReadTokens = Optional.ofNullable(cacheReadTokens);
      return this;
    }

    /**
     * <p>Number of input tokens served from the prompt cache. Present only when prompt caching applied to this call. Prompt caching is not yet used; this field is reserved for forward compatibility.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "cacheReadTokens",
        nulls = Nulls.SKIP
    )
    public _FinalStage cacheReadTokens(Optional<Integer> cacheReadTokens) {
      this.cacheReadTokens = cacheReadTokens;
      return this;
    }

    @java.lang.Override
    public DoneEvent build() {
      return new DoneEvent(event, inputTokens, outputTokens, model, platformCreditsCharged, inferenceBalanceCentsCharged, cacheReadTokens, cacheCreateTokens, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
