/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = EntityResponse.Builder.class
)
public final class EntityResponse {
  private final Optional<Boolean> created;

  private final Optional<String> id;

  private final Optional<String> namespace;

  private final Optional<String> contextId;

  private final Optional<String> externalId;

  private final Optional<String> name;

  private final Optional<String> status;

  private final Optional<List<String>> scopes;

  private final Optional<Map<String, Object>> payload;

  private final Optional<String> schemaId;

  private final Optional<Integer> schemaVersion;

  private final Optional<String> createdAt;

  private final Map<String, Object> additionalProperties;

  private EntityResponse(Optional<Boolean> created, Optional<String> id, Optional<String> namespace,
      Optional<String> contextId, Optional<String> externalId, Optional<String> name,
      Optional<String> status, Optional<List<String>> scopes, Optional<Map<String, Object>> payload,
      Optional<String> schemaId, Optional<Integer> schemaVersion, Optional<String> createdAt,
      Map<String, Object> additionalProperties) {
    this.created = created;
    this.id = id;
    this.namespace = namespace;
    this.contextId = contextId;
    this.externalId = externalId;
    this.name = name;
    this.status = status;
    this.scopes = scopes;
    this.payload = payload;
    this.schemaId = schemaId;
    this.schemaVersion = schemaVersion;
    this.createdAt = createdAt;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Whether this call created a new entity. True when a new entity was created; false when an entity with the same <code>externalId</code> already existed and was returned unchanged (idempotent create) or updated (when <code>?upsert=true</code>). Present only on the create response; absent on reads. The HTTP status mirrors it — 201 when created, 200 when an existing entity was returned.
   */
  @JsonProperty("created")
  public Optional<Boolean> getCreated() {
    return created;
  }

  /**
   * @return The Vectros-assigned ID (UUID) for this entity.
   */
  @JsonProperty("id")
  public Optional<String> getId() {
    return id;
  }

  /**
   * @return The namespace this entity belongs to.
   */
  @JsonProperty("namespace")
  public Optional<String> getNamespace() {
    return namespace;
  }

  /**
   * @return The app context that owns this entity, or null for a TENANT-WIDE entity visible to every app context. Mirrors the owning namespace registration's <code>contextId</code> (see <code>GET /v1/namespaces</code>) — a context-owned namespace's entities all carry that same context.
   */
  @JsonProperty("contextId")
  public Optional<String> getContextId() {
    return contextId;
  }

  /**
   * @return Your own identifier for this entity, as supplied when it was created.
   */
  @JsonProperty("externalId")
  public Optional<String> getExternalId() {
    return externalId;
  }

  /**
   * @return Human-readable name of the entity.
   */
  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  /**
   * @return Lifecycle status of the entity: <code>ACTIVE</code> or <code>SUSPENDED</code>.
   */
  @JsonProperty("status")
  public Optional<String> getStatus() {
    return status;
  }

  /**
   * @return The entity's effective scopes: its own reference (<code>&lt;namespace&gt;:&lt;id&gt;</code>) followed by its parent edges. Use these values to reference the entity as an owner elsewhere.
   */
  @JsonProperty("scopes")
  public Optional<List<String>> getScopes() {
    return scopes;
  }

  /**
   * @return Free-form key-value attributes stored with the entity.
   */
  @JsonProperty("payload")
  public Optional<Map<String, Object>> getPayload() {
    return payload;
  }

  /**
   * @return ID of the record schema governing this entity, or null if unbound.
   */
  @JsonProperty("schemaId")
  public Optional<String> getSchemaId() {
    return schemaId;
  }

  /**
   * @return The governing schema's version in effect when this entity was last written, or null when unbound.
   */
  @JsonProperty("schemaVersion")
  public Optional<Integer> getSchemaVersion() {
    return schemaVersion;
  }

  /**
   * @return Timestamp when the entity was created, as an ISO-8601 UTC timestamp.
   */
  @JsonProperty("createdAt")
  public Optional<String> getCreatedAt() {
    return createdAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof EntityResponse && equalTo((EntityResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(EntityResponse other) {
    return created.equals(other.created) && id.equals(other.id) && namespace.equals(other.namespace) && contextId.equals(other.contextId) && externalId.equals(other.externalId) && name.equals(other.name) && status.equals(other.status) && scopes.equals(other.scopes) && payload.equals(other.payload) && schemaId.equals(other.schemaId) && schemaVersion.equals(other.schemaVersion) && createdAt.equals(other.createdAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.created, this.id, this.namespace, this.contextId, this.externalId, this.name, this.status, this.scopes, this.payload, this.schemaId, this.schemaVersion, this.createdAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Boolean> created = Optional.empty();

    private Optional<String> id = Optional.empty();

    private Optional<String> namespace = Optional.empty();

    private Optional<String> contextId = Optional.empty();

    private Optional<String> externalId = Optional.empty();

    private Optional<String> name = Optional.empty();

    private Optional<String> status = Optional.empty();

    private Optional<List<String>> scopes = Optional.empty();

    private Optional<Map<String, Object>> payload = Optional.empty();

    private Optional<String> schemaId = Optional.empty();

    private Optional<Integer> schemaVersion = Optional.empty();

    private Optional<String> createdAt = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(EntityResponse other) {
      created(other.getCreated());
      id(other.getId());
      namespace(other.getNamespace());
      contextId(other.getContextId());
      externalId(other.getExternalId());
      name(other.getName());
      status(other.getStatus());
      scopes(other.getScopes());
      payload(other.getPayload());
      schemaId(other.getSchemaId());
      schemaVersion(other.getSchemaVersion());
      createdAt(other.getCreatedAt());
      return this;
    }

    /**
     * <p>Whether this call created a new entity. True when a new entity was created; false when an entity with the same <code>externalId</code> already existed and was returned unchanged (idempotent create) or updated (when <code>?upsert=true</code>). Present only on the create response; absent on reads. The HTTP status mirrors it — 201 when created, 200 when an existing entity was returned.</p>
     */
    @JsonSetter(
        value = "created",
        nulls = Nulls.SKIP
    )
    public Builder created(Optional<Boolean> created) {
      this.created = created;
      return this;
    }

    public Builder created(Boolean created) {
      this.created = Optional.ofNullable(created);
      return this;
    }

    /**
     * <p>The Vectros-assigned ID (UUID) for this entity.</p>
     */
    @JsonSetter(
        value = "id",
        nulls = Nulls.SKIP
    )
    public Builder id(Optional<String> id) {
      this.id = id;
      return this;
    }

    public Builder id(String id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    /**
     * <p>The namespace this entity belongs to.</p>
     */
    @JsonSetter(
        value = "namespace",
        nulls = Nulls.SKIP
    )
    public Builder namespace(Optional<String> namespace) {
      this.namespace = namespace;
      return this;
    }

    public Builder namespace(String namespace) {
      this.namespace = Optional.ofNullable(namespace);
      return this;
    }

    /**
     * <p>The app context that owns this entity, or null for a TENANT-WIDE entity visible to every app context. Mirrors the owning namespace registration's <code>contextId</code> (see <code>GET /v1/namespaces</code>) — a context-owned namespace's entities all carry that same context.</p>
     */
    @JsonSetter(
        value = "contextId",
        nulls = Nulls.SKIP
    )
    public Builder contextId(Optional<String> contextId) {
      this.contextId = contextId;
      return this;
    }

    public Builder contextId(String contextId) {
      this.contextId = Optional.ofNullable(contextId);
      return this;
    }

    /**
     * <p>Your own identifier for this entity, as supplied when it was created.</p>
     */
    @JsonSetter(
        value = "externalId",
        nulls = Nulls.SKIP
    )
    public Builder externalId(Optional<String> externalId) {
      this.externalId = externalId;
      return this;
    }

    public Builder externalId(String externalId) {
      this.externalId = Optional.ofNullable(externalId);
      return this;
    }

    /**
     * <p>Human-readable name of the entity.</p>
     */
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    /**
     * <p>Lifecycle status of the entity: <code>ACTIVE</code> or <code>SUSPENDED</code>.</p>
     */
    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<String> status) {
      this.status = status;
      return this;
    }

    public Builder status(String status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    /**
     * <p>The entity's effective scopes: its own reference (<code>&lt;namespace&gt;:&lt;id&gt;</code>) followed by its parent edges. Use these values to reference the entity as an owner elsewhere.</p>
     */
    @JsonSetter(
        value = "scopes",
        nulls = Nulls.SKIP
    )
    public Builder scopes(Optional<List<String>> scopes) {
      this.scopes = scopes;
      return this;
    }

    public Builder scopes(List<String> scopes) {
      this.scopes = Optional.ofNullable(scopes);
      return this;
    }

    /**
     * <p>Free-form key-value attributes stored with the entity.</p>
     */
    @JsonSetter(
        value = "payload",
        nulls = Nulls.SKIP
    )
    public Builder payload(Optional<Map<String, Object>> payload) {
      this.payload = payload;
      return this;
    }

    public Builder payload(Map<String, Object> payload) {
      this.payload = Optional.ofNullable(payload);
      return this;
    }

    /**
     * <p>ID of the record schema governing this entity, or null if unbound.</p>
     */
    @JsonSetter(
        value = "schemaId",
        nulls = Nulls.SKIP
    )
    public Builder schemaId(Optional<String> schemaId) {
      this.schemaId = schemaId;
      return this;
    }

    public Builder schemaId(String schemaId) {
      this.schemaId = Optional.ofNullable(schemaId);
      return this;
    }

    /**
     * <p>The governing schema's version in effect when this entity was last written, or null when unbound.</p>
     */
    @JsonSetter(
        value = "schemaVersion",
        nulls = Nulls.SKIP
    )
    public Builder schemaVersion(Optional<Integer> schemaVersion) {
      this.schemaVersion = schemaVersion;
      return this;
    }

    public Builder schemaVersion(Integer schemaVersion) {
      this.schemaVersion = Optional.ofNullable(schemaVersion);
      return this;
    }

    /**
     * <p>Timestamp when the entity was created, as an ISO-8601 UTC timestamp.</p>
     */
    @JsonSetter(
        value = "createdAt",
        nulls = Nulls.SKIP
    )
    public Builder createdAt(Optional<String> createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    public Builder createdAt(String createdAt) {
      this.createdAt = Optional.ofNullable(createdAt);
      return this;
    }

    public EntityResponse build() {
      return new EntityResponse(created, id, namespace, contextId, externalId, name, status, scopes, payload, schemaId, schemaVersion, createdAt, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
