/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ErasureCertificateAuditDisposition {
  public static final ErasureCertificateAuditDisposition PURGE = new ErasureCertificateAuditDisposition(Value.PURGE, "purge");

  public static final ErasureCertificateAuditDisposition RETAIN_REDACTED = new ErasureCertificateAuditDisposition(Value.RETAIN_REDACTED, "retain-redacted");

  private final Value value;

  private final String string;

  ErasureCertificateAuditDisposition(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ErasureCertificateAuditDisposition && this.string.equals(((ErasureCertificateAuditDisposition) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case PURGE:
        return visitor.visitPurge();
      case RETAIN_REDACTED:
        return visitor.visitRetainRedacted();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ErasureCertificateAuditDisposition valueOf(String value) {
    switch (value) {
      case "purge":
        return PURGE;
      case "retain-redacted":
        return RETAIN_REDACTED;
      default:
        return new ErasureCertificateAuditDisposition(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    RETAIN_REDACTED,

    PURGE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitRetainRedacted();

    T visitPurge();

    T visitUnknown(String unknownType);
  }
}
