/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class FieldDefTargetSurface {
  public static final FieldDefTargetSurface ORG = new FieldDefTargetSurface(Value.ORG, "org");

  public static final FieldDefTargetSurface USER = new FieldDefTargetSurface(Value.USER, "user");

  public static final FieldDefTargetSurface DOCUMENT = new FieldDefTargetSurface(Value.DOCUMENT, "document");

  public static final FieldDefTargetSurface CLIENT = new FieldDefTargetSurface(Value.CLIENT, "client");

  public static final FieldDefTargetSurface RECORD = new FieldDefTargetSurface(Value.RECORD, "record");

  private final Value value;

  private final String string;

  FieldDefTargetSurface(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof FieldDefTargetSurface && this.string.equals(((FieldDefTargetSurface) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case ORG:
        return visitor.visitOrg();
      case USER:
        return visitor.visitUser();
      case DOCUMENT:
        return visitor.visitDocument();
      case CLIENT:
        return visitor.visitClient();
      case RECORD:
        return visitor.visitRecord();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static FieldDefTargetSurface valueOf(String value) {
    switch (value) {
      case "org":
        return ORG;
      case "user":
        return USER;
      case "document":
        return DOCUMENT;
      case "client":
        return CLIENT;
      case "record":
        return RECORD;
      default:
        return new FieldDefTargetSurface(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    RECORD,

    DOCUMENT,

    USER,

    ORG,

    CLIENT,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitRecord();

    T visitDocument();

    T visitUser();

    T visitOrg();

    T visitClient();

    T visitUnknown(String unknownType);
  }
}
