/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = IndexFailure.Builder.class
)
public final class IndexFailure {
  private final Optional<IndexFailureCode> code;

  private final Optional<String> message;

  private final Map<String, Object> additionalProperties;

  private IndexFailure(Optional<IndexFailureCode> code, Optional<String> message,
      Map<String, Object> additionalProperties) {
    this.code = code;
    this.message = message;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return A stable, machine-readable reason code. Branch on this value rather than on <code>message</code>. <code>SOURCE_UNAVAILABLE</code> — the underlying item could not be loaded and may have been deleted. <code>TEXT_INDEX_FAILED</code> — keyword indexing failed; the content may still be findable by semantic search. <code>EMBEDDING_FAILED</code> — semantic indexing failed; the content may still be findable by keyword search. <code>INDEXING_FAILED</code> — no index leg is serving this content, so it is not findable by search at all. <code>VECTOR_LIMIT_EXCEEDED</code> — your vector storage limit was reached, so semantic indexing was skipped; keyword search is still serving this content. <code>INTERNAL</code> — an error on our side; retry, and contact support if it persists.
   */
  @JsonProperty("code")
  public Optional<IndexFailureCode> getCode() {
    return code;
  }

  /**
   * @return A human-readable explanation of the failure, suitable for showing to an end user. Wording may change between releases — branch on <code>code</code> instead.
   */
  @JsonProperty("message")
  public Optional<String> getMessage() {
    return message;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof IndexFailure && equalTo((IndexFailure) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(IndexFailure other) {
    return code.equals(other.code) && message.equals(other.message);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.code, this.message);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<IndexFailureCode> code = Optional.empty();

    private Optional<String> message = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(IndexFailure other) {
      code(other.getCode());
      message(other.getMessage());
      return this;
    }

    /**
     * <p>A stable, machine-readable reason code. Branch on this value rather than on <code>message</code>. <code>SOURCE_UNAVAILABLE</code> — the underlying item could not be loaded and may have been deleted. <code>TEXT_INDEX_FAILED</code> — keyword indexing failed; the content may still be findable by semantic search. <code>EMBEDDING_FAILED</code> — semantic indexing failed; the content may still be findable by keyword search. <code>INDEXING_FAILED</code> — no index leg is serving this content, so it is not findable by search at all. <code>VECTOR_LIMIT_EXCEEDED</code> — your vector storage limit was reached, so semantic indexing was skipped; keyword search is still serving this content. <code>INTERNAL</code> — an error on our side; retry, and contact support if it persists.</p>
     */
    @JsonSetter(
        value = "code",
        nulls = Nulls.SKIP
    )
    public Builder code(Optional<IndexFailureCode> code) {
      this.code = code;
      return this;
    }

    public Builder code(IndexFailureCode code) {
      this.code = Optional.ofNullable(code);
      return this;
    }

    /**
     * <p>A human-readable explanation of the failure, suitable for showing to an end user. Wording may change between releases — branch on <code>code</code> instead.</p>
     */
    @JsonSetter(
        value = "message",
        nulls = Nulls.SKIP
    )
    public Builder message(Optional<String> message) {
      this.message = message;
      return this;
    }

    public Builder message(String message) {
      this.message = Optional.ofNullable(message);
      return this;
    }

    public IndexFailure build() {
      return new IndexFailure(code, message, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
