/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = InferenceCallStats.Builder.class
)
public final class InferenceCallStats {
  private final Optional<Long> calls;

  private final Optional<Long> inputTokens;

  private final Optional<Long> outputTokens;

  private final Map<String, Object> additionalProperties;

  private InferenceCallStats(Optional<Long> calls, Optional<Long> inputTokens,
      Optional<Long> outputTokens, Map<String, Object> additionalProperties) {
    this.calls = calls;
    this.inputTokens = inputTokens;
    this.outputTokens = outputTokens;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Number of inference calls this period
   */
  @JsonProperty("calls")
  public Optional<Long> getCalls() {
    return calls;
  }

  /**
   * @return Total input tokens consumed across all calls
   */
  @JsonProperty("inputTokens")
  public Optional<Long> getInputTokens() {
    return inputTokens;
  }

  /**
   * @return Total output tokens generated across all calls
   */
  @JsonProperty("outputTokens")
  public Optional<Long> getOutputTokens() {
    return outputTokens;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof InferenceCallStats && equalTo((InferenceCallStats) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(InferenceCallStats other) {
    return calls.equals(other.calls) && inputTokens.equals(other.inputTokens) && outputTokens.equals(other.outputTokens);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.calls, this.inputTokens, this.outputTokens);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Long> calls = Optional.empty();

    private Optional<Long> inputTokens = Optional.empty();

    private Optional<Long> outputTokens = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(InferenceCallStats other) {
      calls(other.getCalls());
      inputTokens(other.getInputTokens());
      outputTokens(other.getOutputTokens());
      return this;
    }

    /**
     * <p>Number of inference calls this period</p>
     */
    @JsonSetter(
        value = "calls",
        nulls = Nulls.SKIP
    )
    public Builder calls(Optional<Long> calls) {
      this.calls = calls;
      return this;
    }

    public Builder calls(Long calls) {
      this.calls = Optional.ofNullable(calls);
      return this;
    }

    /**
     * <p>Total input tokens consumed across all calls</p>
     */
    @JsonSetter(
        value = "inputTokens",
        nulls = Nulls.SKIP
    )
    public Builder inputTokens(Optional<Long> inputTokens) {
      this.inputTokens = inputTokens;
      return this;
    }

    public Builder inputTokens(Long inputTokens) {
      this.inputTokens = Optional.ofNullable(inputTokens);
      return this;
    }

    /**
     * <p>Total output tokens generated across all calls</p>
     */
    @JsonSetter(
        value = "outputTokens",
        nulls = Nulls.SKIP
    )
    public Builder outputTokens(Optional<Long> outputTokens) {
      this.outputTokens = outputTokens;
      return this;
    }

    public Builder outputTokens(Long outputTokens) {
      this.outputTokens = Optional.ofNullable(outputTokens);
      return this;
    }

    public InferenceCallStats build() {
      return new InferenceCallStats(calls, inputTokens, outputTokens, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
