/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = IssuerResponse.Builder.class
)
public final class IssuerResponse {
  private final Optional<String> issuerId;

  private final Optional<String> issuer;

  private final Optional<String> jwksUri;

  private final Optional<String> audience;

  private final Optional<String> contextId;

  private final Optional<String> subClaim;

  private final Optional<String> emailClaim;

  private final Optional<String> status;

  private final Optional<String> createdAt;

  private final Optional<Boolean> created;

  private final Optional<List<SelfSignupPolicy>> selfSignupPolicies;

  private final Map<String, Object> additionalProperties;

  private IssuerResponse(Optional<String> issuerId, Optional<String> issuer,
      Optional<String> jwksUri, Optional<String> audience, Optional<String> contextId,
      Optional<String> subClaim, Optional<String> emailClaim, Optional<String> status,
      Optional<String> createdAt, Optional<Boolean> created,
      Optional<List<SelfSignupPolicy>> selfSignupPolicies,
      Map<String, Object> additionalProperties) {
    this.issuerId = issuerId;
    this.issuer = issuer;
    this.jwksUri = jwksUri;
    this.audience = audience;
    this.contextId = contextId;
    this.subClaim = subClaim;
    this.emailClaim = emailClaim;
    this.status = status;
    this.createdAt = createdAt;
    this.created = created;
    this.selfSignupPolicies = selfSignupPolicies;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return This issuer's slug within your tenant.
   */
  @JsonProperty("issuerId")
  public Optional<String> getIssuerId() {
    return issuerId;
  }

  /**
   * @return The IdP's <code>iss</code> claim value.
   */
  @JsonProperty("issuer")
  public Optional<String> getIssuer() {
    return issuer;
  }

  /**
   * @return The IdP's remote JWKS endpoint.
   */
  @JsonProperty("jwksUri")
  public Optional<String> getJwksUri() {
    return jwksUri;
  }

  /**
   * @return The required <code>aud</code> claim value.
   */
  @JsonProperty("audience")
  public Optional<String> getAudience() {
    return audience;
  }

  /**
   * @return The app context an exchanged token targets.
   */
  @JsonProperty("contextId")
  public Optional<String> getContextId() {
    return contextId;
  }

  /**
   * @return The subject-identifier claim.
   */
  @JsonProperty("subClaim")
  public Optional<String> getSubClaim() {
    return subClaim;
  }

  /**
   * @return The subject-email claim.
   */
  @JsonProperty("emailClaim")
  public Optional<String> getEmailClaim() {
    return emailClaim;
  }

  /**
   * @return <code>active</code> or <code>suspended</code>. A suspended issuer is registered but its tokens are no longer accepted for exchange.
   */
  @JsonProperty("status")
  public Optional<String> getStatus() {
    return status;
  }

  /**
   * @return Timestamp when the issuer was registered, as an ISO-8601 UTC timestamp.
   */
  @JsonProperty("createdAt")
  public Optional<String> getCreatedAt() {
    return createdAt;
  }

  /**
   * @return <code>true</code> if this call registered a new issuer, <code>false</code> if issuerId already existed in your tenant and the existing registration was returned unchanged. Only present on the create response (POST /v1/auth/issuers); absent on reads. The HTTP status mirrors it — 201 when created, 200 when an existing registration was returned.
   */
  @JsonProperty("created")
  public Optional<Boolean> getCreated() {
    return created;
  }

  /**
   * @return Configured self-service signup policies, if any. Absent (not an empty list) when self-signup is not configured for this issuer.
   */
  @JsonProperty("selfSignupPolicies")
  public Optional<List<SelfSignupPolicy>> getSelfSignupPolicies() {
    return selfSignupPolicies;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof IssuerResponse && equalTo((IssuerResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(IssuerResponse other) {
    return issuerId.equals(other.issuerId) && issuer.equals(other.issuer) && jwksUri.equals(other.jwksUri) && audience.equals(other.audience) && contextId.equals(other.contextId) && subClaim.equals(other.subClaim) && emailClaim.equals(other.emailClaim) && status.equals(other.status) && createdAt.equals(other.createdAt) && created.equals(other.created) && selfSignupPolicies.equals(other.selfSignupPolicies);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.issuerId, this.issuer, this.jwksUri, this.audience, this.contextId, this.subClaim, this.emailClaim, this.status, this.createdAt, this.created, this.selfSignupPolicies);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> issuerId = Optional.empty();

    private Optional<String> issuer = Optional.empty();

    private Optional<String> jwksUri = Optional.empty();

    private Optional<String> audience = Optional.empty();

    private Optional<String> contextId = Optional.empty();

    private Optional<String> subClaim = Optional.empty();

    private Optional<String> emailClaim = Optional.empty();

    private Optional<String> status = Optional.empty();

    private Optional<String> createdAt = Optional.empty();

    private Optional<Boolean> created = Optional.empty();

    private Optional<List<SelfSignupPolicy>> selfSignupPolicies = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(IssuerResponse other) {
      issuerId(other.getIssuerId());
      issuer(other.getIssuer());
      jwksUri(other.getJwksUri());
      audience(other.getAudience());
      contextId(other.getContextId());
      subClaim(other.getSubClaim());
      emailClaim(other.getEmailClaim());
      status(other.getStatus());
      createdAt(other.getCreatedAt());
      created(other.getCreated());
      selfSignupPolicies(other.getSelfSignupPolicies());
      return this;
    }

    /**
     * <p>This issuer's slug within your tenant.</p>
     */
    @JsonSetter(
        value = "issuerId",
        nulls = Nulls.SKIP
    )
    public Builder issuerId(Optional<String> issuerId) {
      this.issuerId = issuerId;
      return this;
    }

    public Builder issuerId(String issuerId) {
      this.issuerId = Optional.ofNullable(issuerId);
      return this;
    }

    /**
     * <p>The IdP's <code>iss</code> claim value.</p>
     */
    @JsonSetter(
        value = "issuer",
        nulls = Nulls.SKIP
    )
    public Builder issuer(Optional<String> issuer) {
      this.issuer = issuer;
      return this;
    }

    public Builder issuer(String issuer) {
      this.issuer = Optional.ofNullable(issuer);
      return this;
    }

    /**
     * <p>The IdP's remote JWKS endpoint.</p>
     */
    @JsonSetter(
        value = "jwksUri",
        nulls = Nulls.SKIP
    )
    public Builder jwksUri(Optional<String> jwksUri) {
      this.jwksUri = jwksUri;
      return this;
    }

    public Builder jwksUri(String jwksUri) {
      this.jwksUri = Optional.ofNullable(jwksUri);
      return this;
    }

    /**
     * <p>The required <code>aud</code> claim value.</p>
     */
    @JsonSetter(
        value = "audience",
        nulls = Nulls.SKIP
    )
    public Builder audience(Optional<String> audience) {
      this.audience = audience;
      return this;
    }

    public Builder audience(String audience) {
      this.audience = Optional.ofNullable(audience);
      return this;
    }

    /**
     * <p>The app context an exchanged token targets.</p>
     */
    @JsonSetter(
        value = "contextId",
        nulls = Nulls.SKIP
    )
    public Builder contextId(Optional<String> contextId) {
      this.contextId = contextId;
      return this;
    }

    public Builder contextId(String contextId) {
      this.contextId = Optional.ofNullable(contextId);
      return this;
    }

    /**
     * <p>The subject-identifier claim.</p>
     */
    @JsonSetter(
        value = "subClaim",
        nulls = Nulls.SKIP
    )
    public Builder subClaim(Optional<String> subClaim) {
      this.subClaim = subClaim;
      return this;
    }

    public Builder subClaim(String subClaim) {
      this.subClaim = Optional.ofNullable(subClaim);
      return this;
    }

    /**
     * <p>The subject-email claim.</p>
     */
    @JsonSetter(
        value = "emailClaim",
        nulls = Nulls.SKIP
    )
    public Builder emailClaim(Optional<String> emailClaim) {
      this.emailClaim = emailClaim;
      return this;
    }

    public Builder emailClaim(String emailClaim) {
      this.emailClaim = Optional.ofNullable(emailClaim);
      return this;
    }

    /**
     * <p><code>active</code> or <code>suspended</code>. A suspended issuer is registered but its tokens are no longer accepted for exchange.</p>
     */
    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<String> status) {
      this.status = status;
      return this;
    }

    public Builder status(String status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    /**
     * <p>Timestamp when the issuer was registered, as an ISO-8601 UTC timestamp.</p>
     */
    @JsonSetter(
        value = "createdAt",
        nulls = Nulls.SKIP
    )
    public Builder createdAt(Optional<String> createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    public Builder createdAt(String createdAt) {
      this.createdAt = Optional.ofNullable(createdAt);
      return this;
    }

    /**
     * <p><code>true</code> if this call registered a new issuer, <code>false</code> if issuerId already existed in your tenant and the existing registration was returned unchanged. Only present on the create response (POST /v1/auth/issuers); absent on reads. The HTTP status mirrors it — 201 when created, 200 when an existing registration was returned.</p>
     */
    @JsonSetter(
        value = "created",
        nulls = Nulls.SKIP
    )
    public Builder created(Optional<Boolean> created) {
      this.created = created;
      return this;
    }

    public Builder created(Boolean created) {
      this.created = Optional.ofNullable(created);
      return this;
    }

    /**
     * <p>Configured self-service signup policies, if any. Absent (not an empty list) when self-signup is not configured for this issuer.</p>
     */
    @JsonSetter(
        value = "selfSignupPolicies",
        nulls = Nulls.SKIP
    )
    public Builder selfSignupPolicies(Optional<List<SelfSignupPolicy>> selfSignupPolicies) {
      this.selfSignupPolicies = selfSignupPolicies;
      return this;
    }

    public Builder selfSignupPolicies(List<SelfSignupPolicy> selfSignupPolicies) {
      this.selfSignupPolicies = Optional.ofNullable(selfSignupPolicies);
      return this;
    }

    public IssuerResponse build() {
      return new IssuerResponse(issuerId, issuer, jwksUri, audience, contextId, subClaim, emailClaim, status, createdAt, created, selfSignupPolicies, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
