/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.Nullable;
import ai.vectros.core.NullableNonemptyFilter;
import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = LogEntry.Builder.class
)
public final class LogEntry {
  private final String timestamp;

  private final String method;

  private final String resource;

  private final Optional<String> contextId;

  private final int status;

  private final Optional<String> keyId;

  private final Optional<Long> durationMs;

  private final Optional<String> path;

  private final Map<String, Object> additionalProperties;

  private LogEntry(String timestamp, String method, String resource, Optional<String> contextId,
      int status, Optional<String> keyId, Optional<Long> durationMs, Optional<String> path,
      Map<String, Object> additionalProperties) {
    this.timestamp = timestamp;
    this.method = method;
    this.resource = resource;
    this.contextId = contextId;
    this.status = status;
    this.keyId = keyId;
    this.durationMs = durationMs;
    this.path = path;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return When the API call completed (ISO-8601 UTC).
   */
  @JsonProperty("timestamp")
  public String getTimestamp() {
    return timestamp;
  }

  /**
   * @return HTTP method of the request.
   */
  @JsonProperty("method")
  public String getMethod() {
    return method;
  }

  /**
   * @return Top-level resource the call targeted (one of <code>documents</code>, <code>records</code>, <code>search</code>, <code>schemas</code>, <code>folders</code>, <code>clients</code>, <code>orgs</code>, <code>users</code>, <code>usage</code>, <code>auth</code>, <code>models</code>, <code>ping</code>, <code>rag</code>, <code>chat</code>, <code>ask</code>, <code>erasure-requests</code>, or <code>export</code>), derived from the request path.
   */
  @JsonProperty("resource")
  public String getResource() {
    return resource;
  }

  /**
   * @return The app context the request operated under — the context partition the credential carried. <code>*</code> for a root/cross-context caller. Null for older log lines or for entry points that are not context-scoped.
   */
  @JsonIgnore
  public Optional<String> getContextId() {
    if (contextId == null) {
      return Optional.empty();
    }
    return contextId;
  }

  /**
   * @return HTTP response status code.
   */
  @JsonProperty("status")
  public int getStatus() {
    return status;
  }

  /**
   * @return ID of the API key or scoped token that issued the request. Null if the request was unauthenticated (extremely rare — most paths require auth before logging).
   */
  @JsonIgnore
  public Optional<String> getKeyId() {
    if (keyId == null) {
      return Optional.empty();
    }
    return keyId;
  }

  /**
   * @return Total request duration in milliseconds, from auth to response completion.
   */
  @JsonProperty("durationMs")
  public Optional<Long> getDurationMs() {
    return durationMs;
  }

  /**
   * @return Full request path.
   */
  @JsonProperty("path")
  public Optional<String> getPath() {
    return path;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("contextId")
  private Optional<String> _getContextId() {
    return contextId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("keyId")
  private Optional<String> _getKeyId() {
    return keyId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof LogEntry && equalTo((LogEntry) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(LogEntry other) {
    return timestamp.equals(other.timestamp) && method.equals(other.method) && resource.equals(other.resource) && contextId.equals(other.contextId) && status == other.status && keyId.equals(other.keyId) && durationMs.equals(other.durationMs) && path.equals(other.path);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.timestamp, this.method, this.resource, this.contextId, this.status, this.keyId, this.durationMs, this.path);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TimestampStage builder() {
    return new Builder();
  }

  public interface TimestampStage {
    /**
     * <p>When the API call completed (ISO-8601 UTC).</p>
     */
    MethodStage timestamp(@NotNull String timestamp);

    Builder from(LogEntry other);
  }

  public interface MethodStage {
    /**
     * <p>HTTP method of the request.</p>
     */
    ResourceStage method(@NotNull String method);
  }

  public interface ResourceStage {
    /**
     * <p>Top-level resource the call targeted (one of <code>documents</code>, <code>records</code>, <code>search</code>, <code>schemas</code>, <code>folders</code>, <code>clients</code>, <code>orgs</code>, <code>users</code>, <code>usage</code>, <code>auth</code>, <code>models</code>, <code>ping</code>, <code>rag</code>, <code>chat</code>, <code>ask</code>, <code>erasure-requests</code>, or <code>export</code>), derived from the request path.</p>
     */
    StatusStage resource(@NotNull String resource);
  }

  public interface StatusStage {
    /**
     * <p>HTTP response status code.</p>
     */
    _FinalStage status(int status);
  }

  public interface _FinalStage {
    LogEntry build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>The app context the request operated under — the context partition the credential carried. <code>*</code> for a root/cross-context caller. Null for older log lines or for entry points that are not context-scoped.</p>
     */
    _FinalStage contextId(Optional<String> contextId);

    _FinalStage contextId(String contextId);

    _FinalStage contextId(Nullable<String> contextId);

    /**
     * <p>ID of the API key or scoped token that issued the request. Null if the request was unauthenticated (extremely rare — most paths require auth before logging).</p>
     */
    _FinalStage keyId(Optional<String> keyId);

    _FinalStage keyId(String keyId);

    _FinalStage keyId(Nullable<String> keyId);

    /**
     * <p>Total request duration in milliseconds, from auth to response completion.</p>
     */
    _FinalStage durationMs(Optional<Long> durationMs);

    _FinalStage durationMs(Long durationMs);

    /**
     * <p>Full request path.</p>
     */
    _FinalStage path(Optional<String> path);

    _FinalStage path(String path);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TimestampStage, MethodStage, ResourceStage, StatusStage, _FinalStage {
    private String timestamp;

    private String method;

    private String resource;

    private int status;

    private Optional<String> path = Optional.empty();

    private Optional<Long> durationMs = Optional.empty();

    private Optional<String> keyId = Optional.empty();

    private Optional<String> contextId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(LogEntry other) {
      timestamp(other.getTimestamp());
      method(other.getMethod());
      resource(other.getResource());
      contextId(other.getContextId());
      status(other.getStatus());
      keyId(other.getKeyId());
      durationMs(other.getDurationMs());
      path(other.getPath());
      return this;
    }

    /**
     * <p>When the API call completed (ISO-8601 UTC).</p>
     * <p>When the API call completed (ISO-8601 UTC).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("timestamp")
    public MethodStage timestamp(@NotNull String timestamp) {
      this.timestamp = Objects.requireNonNull(timestamp, "timestamp must not be null");
      return this;
    }

    /**
     * <p>HTTP method of the request.</p>
     * <p>HTTP method of the request.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("method")
    public ResourceStage method(@NotNull String method) {
      this.method = Objects.requireNonNull(method, "method must not be null");
      return this;
    }

    /**
     * <p>Top-level resource the call targeted (one of <code>documents</code>, <code>records</code>, <code>search</code>, <code>schemas</code>, <code>folders</code>, <code>clients</code>, <code>orgs</code>, <code>users</code>, <code>usage</code>, <code>auth</code>, <code>models</code>, <code>ping</code>, <code>rag</code>, <code>chat</code>, <code>ask</code>, <code>erasure-requests</code>, or <code>export</code>), derived from the request path.</p>
     * <p>Top-level resource the call targeted (one of <code>documents</code>, <code>records</code>, <code>search</code>, <code>schemas</code>, <code>folders</code>, <code>clients</code>, <code>orgs</code>, <code>users</code>, <code>usage</code>, <code>auth</code>, <code>models</code>, <code>ping</code>, <code>rag</code>, <code>chat</code>, <code>ask</code>, <code>erasure-requests</code>, or <code>export</code>), derived from the request path.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("resource")
    public StatusStage resource(@NotNull String resource) {
      this.resource = Objects.requireNonNull(resource, "resource must not be null");
      return this;
    }

    /**
     * <p>HTTP response status code.</p>
     * <p>HTTP response status code.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("status")
    public _FinalStage status(int status) {
      this.status = status;
      return this;
    }

    /**
     * <p>Full request path.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage path(String path) {
      this.path = Optional.ofNullable(path);
      return this;
    }

    /**
     * <p>Full request path.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "path",
        nulls = Nulls.SKIP
    )
    public _FinalStage path(Optional<String> path) {
      this.path = path;
      return this;
    }

    /**
     * <p>Total request duration in milliseconds, from auth to response completion.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage durationMs(Long durationMs) {
      this.durationMs = Optional.ofNullable(durationMs);
      return this;
    }

    /**
     * <p>Total request duration in milliseconds, from auth to response completion.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "durationMs",
        nulls = Nulls.SKIP
    )
    public _FinalStage durationMs(Optional<Long> durationMs) {
      this.durationMs = durationMs;
      return this;
    }

    /**
     * <p>ID of the API key or scoped token that issued the request. Null if the request was unauthenticated (extremely rare — most paths require auth before logging).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage keyId(Nullable<String> keyId) {
      if (keyId.isNull()) {
        this.keyId = null;
      }
      else if (keyId.isEmpty()) {
        this.keyId = Optional.empty();
      }
      else {
        this.keyId = Optional.of(keyId.get());
      }
      return this;
    }

    /**
     * <p>ID of the API key or scoped token that issued the request. Null if the request was unauthenticated (extremely rare — most paths require auth before logging).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage keyId(String keyId) {
      this.keyId = Optional.ofNullable(keyId);
      return this;
    }

    /**
     * <p>ID of the API key or scoped token that issued the request. Null if the request was unauthenticated (extremely rare — most paths require auth before logging).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "keyId",
        nulls = Nulls.SKIP
    )
    public _FinalStage keyId(Optional<String> keyId) {
      this.keyId = keyId;
      return this;
    }

    /**
     * <p>The app context the request operated under — the context partition the credential carried. <code>*</code> for a root/cross-context caller. Null for older log lines or for entry points that are not context-scoped.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage contextId(Nullable<String> contextId) {
      if (contextId.isNull()) {
        this.contextId = null;
      }
      else if (contextId.isEmpty()) {
        this.contextId = Optional.empty();
      }
      else {
        this.contextId = Optional.of(contextId.get());
      }
      return this;
    }

    /**
     * <p>The app context the request operated under — the context partition the credential carried. <code>*</code> for a root/cross-context caller. Null for older log lines or for entry points that are not context-scoped.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage contextId(String contextId) {
      this.contextId = Optional.ofNullable(contextId);
      return this;
    }

    /**
     * <p>The app context the request operated under — the context partition the credential carried. <code>*</code> for a root/cross-context caller. Null for older log lines or for entry points that are not context-scoped.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "contextId",
        nulls = Nulls.SKIP
    )
    public _FinalStage contextId(Optional<String> contextId) {
      this.contextId = contextId;
      return this;
    }

    @java.lang.Override
    public LogEntry build() {
      return new LogEntry(timestamp, method, resource, contextId, status, keyId, durationMs, path, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
