/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.Nullable;
import ai.vectros.core.NullableNonemptyFilter;
import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = OrgPage.Builder.class
)
public final class OrgPage {
  private final Optional<List<OrgResponse>> data;

  private final Optional<String> nextCursor;

  private final Map<String, Object> additionalProperties;

  private OrgPage(Optional<List<OrgResponse>> data, Optional<String> nextCursor,
      Map<String, Object> additionalProperties) {
    this.data = data;
    this.nextCursor = nextCursor;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The items on this page, in the endpoint's natural order. Empty when there are no results.
   */
  @JsonProperty("data")
  public Optional<List<OrgResponse>> getData() {
    return data;
  }

  /**
   * @return An opaque cursor for the next page. Pass it back as the <code>startFrom</code> query parameter to continue paging; null when there are no more results. Treat it as opaque — do not parse or construct it.
   */
  @JsonIgnore
  public Optional<String> getNextCursor() {
    if (nextCursor == null) {
      return Optional.empty();
    }
    return nextCursor;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("nextCursor")
  private Optional<String> _getNextCursor() {
    return nextCursor;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof OrgPage && equalTo((OrgPage) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(OrgPage other) {
    return data.equals(other.data) && nextCursor.equals(other.nextCursor);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.data, this.nextCursor);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<List<OrgResponse>> data = Optional.empty();

    private Optional<String> nextCursor = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(OrgPage other) {
      data(other.getData());
      nextCursor(other.getNextCursor());
      return this;
    }

    /**
     * <p>The items on this page, in the endpoint's natural order. Empty when there are no results.</p>
     */
    @JsonSetter(
        value = "data",
        nulls = Nulls.SKIP
    )
    public Builder data(Optional<List<OrgResponse>> data) {
      this.data = data;
      return this;
    }

    public Builder data(List<OrgResponse> data) {
      this.data = Optional.ofNullable(data);
      return this;
    }

    /**
     * <p>An opaque cursor for the next page. Pass it back as the <code>startFrom</code> query parameter to continue paging; null when there are no more results. Treat it as opaque — do not parse or construct it.</p>
     */
    @JsonSetter(
        value = "nextCursor",
        nulls = Nulls.SKIP
    )
    public Builder nextCursor(Optional<String> nextCursor) {
      this.nextCursor = nextCursor;
      return this;
    }

    public Builder nextCursor(String nextCursor) {
      this.nextCursor = Optional.ofNullable(nextCursor);
      return this;
    }

    public Builder nextCursor(Nullable<String> nextCursor) {
      if (nextCursor.isNull()) {
        this.nextCursor = null;
      }
      else if (nextCursor.isEmpty()) {
        this.nextCursor = Optional.empty();
      }
      else {
        this.nextCursor = Optional.of(nextCursor.get());
      }
      return this;
    }

    public OrgPage build() {
      return new OrgPage(data, nextCursor, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
