/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PingResponse.Builder.class
)
public final class PingResponse {
  private final String status;

  private final String tenantId;

  private final PingResponseEnvironment environment;

  private final PingResponsePrincipalType principalType;

  private final String principalKeyId;

  private final Optional<String> principalLabel;

  private final Optional<List<String>> allowedActions;

  private final Optional<DataScope> dataScope;

  private final Optional<Long> tokenExpiresAt;

  private final Map<String, Object> additionalProperties;

  private PingResponse(String status, String tenantId, PingResponseEnvironment environment,
      PingResponsePrincipalType principalType, String principalKeyId,
      Optional<String> principalLabel, Optional<List<String>> allowedActions,
      Optional<DataScope> dataScope, Optional<Long> tokenExpiresAt,
      Map<String, Object> additionalProperties) {
    this.status = status;
    this.tenantId = tenantId;
    this.environment = environment;
    this.principalType = principalType;
    this.principalKeyId = principalKeyId;
    this.principalLabel = principalLabel;
    this.allowedActions = allowedActions;
    this.dataScope = dataScope;
    this.tokenExpiresAt = tokenExpiresAt;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Always &quot;ok&quot; on a successful (2xx) response. Failures are returned as a non-2xx status, so this value is never anything but &quot;ok&quot;.
   */
  @JsonProperty("status")
  public String getStatus() {
    return status;
  }

  /**
   * @return Identifier of the account this credential authenticates under.
   */
  @JsonProperty("tenantId")
  public String getTenantId() {
    return tenantId;
  }

  /**
   * @return The environment that served this response.
   */
  @JsonProperty("environment")
  public PingResponseEnvironment getEnvironment() {
    return environment;
  }

  /**
   * @return The kind of credential you authenticated with: <code>root_key</code> = an unscoped <code>sk_*</code> API key; <code>scoped_key</code> = an <code>ssk_*</code> API key with a bound access profile; <code>token</code> = a short-lived <code>st_*</code> token (its expiry is in <code>tokenExpiresAt</code>).
   */
  @JsonProperty("principalType")
  public PingResponsePrincipalType getPrincipalType() {
    return principalType;
  }

  /**
   * @return Stable identifier for your credential. For <code>sk_*</code> and <code>ssk_*</code> keys this is the key id; for <code>st_*</code> tokens it is the token's JWT id (jti).
   */
  @JsonProperty("principalKeyId")
  public String getPrincipalKeyId() {
    return principalKeyId;
  }

  /**
   * @return The label you set on the originating <code>sk_*</code> or <code>ssk_*</code> key. Omitted when no label is set, or when the credential is an <code>st_*</code> token.
   */
  @JsonProperty("principalLabel")
  public Optional<String> getPrincipalLabel() {
    return principalLabel;
  }

  /**
   * @return The actions this credential is allowed to perform. Present only when <code>principalType</code> is <code>scoped_key</code>.
   */
  @JsonProperty("allowedActions")
  public Optional<List<String>> getAllowedActions() {
    return allowedActions;
  }

  @JsonProperty("dataScope")
  public Optional<DataScope> getDataScope() {
    return dataScope;
  }

  /**
   * @return When the token expires, as seconds since the Unix epoch (mirrors the JWT <code>exp</code> claim). Present only when <code>principalType</code> is <code>token</code>.
   */
  @JsonProperty("tokenExpiresAt")
  public Optional<Long> getTokenExpiresAt() {
    return tokenExpiresAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PingResponse && equalTo((PingResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PingResponse other) {
    return status.equals(other.status) && tenantId.equals(other.tenantId) && environment.equals(other.environment) && principalType.equals(other.principalType) && principalKeyId.equals(other.principalKeyId) && principalLabel.equals(other.principalLabel) && allowedActions.equals(other.allowedActions) && dataScope.equals(other.dataScope) && tokenExpiresAt.equals(other.tokenExpiresAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.status, this.tenantId, this.environment, this.principalType, this.principalKeyId, this.principalLabel, this.allowedActions, this.dataScope, this.tokenExpiresAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static StatusStage builder() {
    return new Builder();
  }

  public interface StatusStage {
    /**
     * <p>Always &quot;ok&quot; on a successful (2xx) response. Failures are returned as a non-2xx status, so this value is never anything but &quot;ok&quot;.</p>
     */
    TenantIdStage status(@NotNull String status);

    Builder from(PingResponse other);
  }

  public interface TenantIdStage {
    /**
     * <p>Identifier of the account this credential authenticates under.</p>
     */
    EnvironmentStage tenantId(@NotNull String tenantId);
  }

  public interface EnvironmentStage {
    /**
     * <p>The environment that served this response.</p>
     */
    PrincipalTypeStage environment(@NotNull PingResponseEnvironment environment);
  }

  public interface PrincipalTypeStage {
    /**
     * <p>The kind of credential you authenticated with: <code>root_key</code> = an unscoped <code>sk_*</code> API key; <code>scoped_key</code> = an <code>ssk_*</code> API key with a bound access profile; <code>token</code> = a short-lived <code>st_*</code> token (its expiry is in <code>tokenExpiresAt</code>).</p>
     */
    PrincipalKeyIdStage principalType(@NotNull PingResponsePrincipalType principalType);
  }

  public interface PrincipalKeyIdStage {
    /**
     * <p>Stable identifier for your credential. For <code>sk_*</code> and <code>ssk_*</code> keys this is the key id; for <code>st_*</code> tokens it is the token's JWT id (jti).</p>
     */
    _FinalStage principalKeyId(@NotNull String principalKeyId);
  }

  public interface _FinalStage {
    PingResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>The label you set on the originating <code>sk_*</code> or <code>ssk_*</code> key. Omitted when no label is set, or when the credential is an <code>st_*</code> token.</p>
     */
    _FinalStage principalLabel(Optional<String> principalLabel);

    _FinalStage principalLabel(String principalLabel);

    /**
     * <p>The actions this credential is allowed to perform. Present only when <code>principalType</code> is <code>scoped_key</code>.</p>
     */
    _FinalStage allowedActions(Optional<List<String>> allowedActions);

    _FinalStage allowedActions(List<String> allowedActions);

    _FinalStage dataScope(Optional<DataScope> dataScope);

    _FinalStage dataScope(DataScope dataScope);

    /**
     * <p>When the token expires, as seconds since the Unix epoch (mirrors the JWT <code>exp</code> claim). Present only when <code>principalType</code> is <code>token</code>.</p>
     */
    _FinalStage tokenExpiresAt(Optional<Long> tokenExpiresAt);

    _FinalStage tokenExpiresAt(Long tokenExpiresAt);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements StatusStage, TenantIdStage, EnvironmentStage, PrincipalTypeStage, PrincipalKeyIdStage, _FinalStage {
    private String status;

    private String tenantId;

    private PingResponseEnvironment environment;

    private PingResponsePrincipalType principalType;

    private String principalKeyId;

    private Optional<Long> tokenExpiresAt = Optional.empty();

    private Optional<DataScope> dataScope = Optional.empty();

    private Optional<List<String>> allowedActions = Optional.empty();

    private Optional<String> principalLabel = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PingResponse other) {
      status(other.getStatus());
      tenantId(other.getTenantId());
      environment(other.getEnvironment());
      principalType(other.getPrincipalType());
      principalKeyId(other.getPrincipalKeyId());
      principalLabel(other.getPrincipalLabel());
      allowedActions(other.getAllowedActions());
      dataScope(other.getDataScope());
      tokenExpiresAt(other.getTokenExpiresAt());
      return this;
    }

    /**
     * <p>Always &quot;ok&quot; on a successful (2xx) response. Failures are returned as a non-2xx status, so this value is never anything but &quot;ok&quot;.</p>
     * <p>Always &quot;ok&quot; on a successful (2xx) response. Failures are returned as a non-2xx status, so this value is never anything but &quot;ok&quot;.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("status")
    public TenantIdStage status(@NotNull String status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    /**
     * <p>Identifier of the account this credential authenticates under.</p>
     * <p>Identifier of the account this credential authenticates under.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("tenantId")
    public EnvironmentStage tenantId(@NotNull String tenantId) {
      this.tenantId = Objects.requireNonNull(tenantId, "tenantId must not be null");
      return this;
    }

    /**
     * <p>The environment that served this response.</p>
     * <p>The environment that served this response.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("environment")
    public PrincipalTypeStage environment(@NotNull PingResponseEnvironment environment) {
      this.environment = Objects.requireNonNull(environment, "environment must not be null");
      return this;
    }

    /**
     * <p>The kind of credential you authenticated with: <code>root_key</code> = an unscoped <code>sk_*</code> API key; <code>scoped_key</code> = an <code>ssk_*</code> API key with a bound access profile; <code>token</code> = a short-lived <code>st_*</code> token (its expiry is in <code>tokenExpiresAt</code>).</p>
     * <p>The kind of credential you authenticated with: <code>root_key</code> = an unscoped <code>sk_*</code> API key; <code>scoped_key</code> = an <code>ssk_*</code> API key with a bound access profile; <code>token</code> = a short-lived <code>st_*</code> token (its expiry is in <code>tokenExpiresAt</code>).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("principalType")
    public PrincipalKeyIdStage principalType(@NotNull PingResponsePrincipalType principalType) {
      this.principalType = Objects.requireNonNull(principalType, "principalType must not be null");
      return this;
    }

    /**
     * <p>Stable identifier for your credential. For <code>sk_*</code> and <code>ssk_*</code> keys this is the key id; for <code>st_*</code> tokens it is the token's JWT id (jti).</p>
     * <p>Stable identifier for your credential. For <code>sk_*</code> and <code>ssk_*</code> keys this is the key id; for <code>st_*</code> tokens it is the token's JWT id (jti).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("principalKeyId")
    public _FinalStage principalKeyId(@NotNull String principalKeyId) {
      this.principalKeyId = Objects.requireNonNull(principalKeyId, "principalKeyId must not be null");
      return this;
    }

    /**
     * <p>When the token expires, as seconds since the Unix epoch (mirrors the JWT <code>exp</code> claim). Present only when <code>principalType</code> is <code>token</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage tokenExpiresAt(Long tokenExpiresAt) {
      this.tokenExpiresAt = Optional.ofNullable(tokenExpiresAt);
      return this;
    }

    /**
     * <p>When the token expires, as seconds since the Unix epoch (mirrors the JWT <code>exp</code> claim). Present only when <code>principalType</code> is <code>token</code>.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "tokenExpiresAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage tokenExpiresAt(Optional<Long> tokenExpiresAt) {
      this.tokenExpiresAt = tokenExpiresAt;
      return this;
    }

    @java.lang.Override
    public _FinalStage dataScope(DataScope dataScope) {
      this.dataScope = Optional.ofNullable(dataScope);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "dataScope",
        nulls = Nulls.SKIP
    )
    public _FinalStage dataScope(Optional<DataScope> dataScope) {
      this.dataScope = dataScope;
      return this;
    }

    /**
     * <p>The actions this credential is allowed to perform. Present only when <code>principalType</code> is <code>scoped_key</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage allowedActions(List<String> allowedActions) {
      this.allowedActions = Optional.ofNullable(allowedActions);
      return this;
    }

    /**
     * <p>The actions this credential is allowed to perform. Present only when <code>principalType</code> is <code>scoped_key</code>.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "allowedActions",
        nulls = Nulls.SKIP
    )
    public _FinalStage allowedActions(Optional<List<String>> allowedActions) {
      this.allowedActions = allowedActions;
      return this;
    }

    /**
     * <p>The label you set on the originating <code>sk_*</code> or <code>ssk_*</code> key. Omitted when no label is set, or when the credential is an <code>st_*</code> token.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage principalLabel(String principalLabel) {
      this.principalLabel = Optional.ofNullable(principalLabel);
      return this;
    }

    /**
     * <p>The label you set on the originating <code>sk_*</code> or <code>ssk_*</code> key. Omitted when no label is set, or when the credential is an <code>st_*</code> token.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "principalLabel",
        nulls = Nulls.SKIP
    )
    public _FinalStage principalLabel(Optional<String> principalLabel) {
      this.principalLabel = principalLabel;
      return this;
    }

    @java.lang.Override
    public PingResponse build() {
      return new PingResponse(status, tenantId, environment, principalType, principalKeyId, principalLabel, allowedActions, dataScope, tokenExpiresAt, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
