/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class RagSearchContentTypesItem {
  public static final RagSearchContentTypesItem DOCUMENTS = new RagSearchContentTypesItem(Value.DOCUMENTS, "documents");

  public static final RagSearchContentTypesItem RECORDS = new RagSearchContentTypesItem(Value.RECORDS, "records");

  private final Value value;

  private final String string;

  RagSearchContentTypesItem(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof RagSearchContentTypesItem && this.string.equals(((RagSearchContentTypesItem) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case DOCUMENTS:
        return visitor.visitDocuments();
      case RECORDS:
        return visitor.visitRecords();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static RagSearchContentTypesItem valueOf(String value) {
    switch (value) {
      case "documents":
        return DOCUMENTS;
      case "records":
        return RECORDS;
      default:
        return new RagSearchContentTypesItem(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    DOCUMENTS,

    RECORDS,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitDocuments();

    T visitRecords();

    T visitUnknown(String unknownType);
  }
}
