/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = RegionRates.Builder.class
)
public final class RegionRates {
  private final double input;

  private final double output;

  private final Map<String, Object> additionalProperties;

  private RegionRates(double input, double output, Map<String, Object> additionalProperties) {
    this.input = input;
    this.output = output;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Credits charged per 1K input tokens.
   */
  @JsonProperty("input")
  public double getInput() {
    return input;
  }

  /**
   * @return Credits charged per 1K output tokens.
   */
  @JsonProperty("output")
  public double getOutput() {
    return output;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof RegionRates && equalTo((RegionRates) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(RegionRates other) {
    return input == other.input && output == other.output;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.input, this.output);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static InputStage builder() {
    return new Builder();
  }

  public interface InputStage {
    /**
     * <p>Credits charged per 1K input tokens.</p>
     */
    OutputStage input(double input);

    Builder from(RegionRates other);
  }

  public interface OutputStage {
    /**
     * <p>Credits charged per 1K output tokens.</p>
     */
    _FinalStage output(double output);
  }

  public interface _FinalStage {
    RegionRates build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements InputStage, OutputStage, _FinalStage {
    private double input;

    private double output;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(RegionRates other) {
      input(other.getInput());
      output(other.getOutput());
      return this;
    }

    /**
     * <p>Credits charged per 1K input tokens.</p>
     * <p>Credits charged per 1K input tokens.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("input")
    public OutputStage input(double input) {
      this.input = input;
      return this;
    }

    /**
     * <p>Credits charged per 1K output tokens.</p>
     * <p>Credits charged per 1K output tokens.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("output")
    public _FinalStage output(double output) {
      this.output = output;
      return this;
    }

    @java.lang.Override
    public RegionRates build() {
      return new RegionRates(input, output, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
