/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class SchemaResponseIndexMode {
  public static final SchemaResponseIndexMode TEXT = new SchemaResponseIndexMode(Value.TEXT, "TEXT");

  public static final SchemaResponseIndexMode HYBRID = new SchemaResponseIndexMode(Value.HYBRID, "HYBRID");

  public static final SchemaResponseIndexMode SEMANTIC = new SchemaResponseIndexMode(Value.SEMANTIC, "SEMANTIC");

  public static final SchemaResponseIndexMode NONE = new SchemaResponseIndexMode(Value.NONE, "NONE");

  private final Value value;

  private final String string;

  SchemaResponseIndexMode(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof SchemaResponseIndexMode && this.string.equals(((SchemaResponseIndexMode) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case TEXT:
        return visitor.visitText();
      case HYBRID:
        return visitor.visitHybrid();
      case SEMANTIC:
        return visitor.visitSemantic();
      case NONE:
        return visitor.visitNone();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static SchemaResponseIndexMode valueOf(String value) {
    switch (value) {
      case "TEXT":
        return TEXT;
      case "HYBRID":
        return HYBRID;
      case "SEMANTIC":
        return SEMANTIC;
      case "NONE":
        return NONE;
      default:
        return new SchemaResponseIndexMode(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    HYBRID,

    SEMANTIC,

    TEXT,

    NONE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitHybrid();

    T visitSemantic();

    T visitText();

    T visitNone();

    T visitUnknown(String unknownType);
  }
}
