/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ScopedKeyResponseStatus {
  public static final ScopedKeyResponseStatus REVOKED = new ScopedKeyResponseStatus(Value.REVOKED, "revoked");

  public static final ScopedKeyResponseStatus ACTIVE = new ScopedKeyResponseStatus(Value.ACTIVE, "active");

  private final Value value;

  private final String string;

  ScopedKeyResponseStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ScopedKeyResponseStatus && this.string.equals(((ScopedKeyResponseStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case REVOKED:
        return visitor.visitRevoked();
      case ACTIVE:
        return visitor.visitActive();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ScopedKeyResponseStatus valueOf(String value) {
    switch (value) {
      case "revoked":
        return REVOKED;
      case "active":
        return ACTIVE;
      default:
        return new ScopedKeyResponseStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    ACTIVE,

    REVOKED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitActive();

    T visitRevoked();

    T visitUnknown(String unknownType);
  }
}
