/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = StorageBytesSearch.Builder.class
)
public final class StorageBytesSearch {
  private final Optional<StorageEntry> text;

  private final Optional<StorageEntry> semantic;

  private final Optional<StorageEntry> hybrid;

  private final Optional<StorageEntry> parentChunks;

  private final Map<String, Object> additionalProperties;

  private StorageBytesSearch(Optional<StorageEntry> text, Optional<StorageEntry> semantic,
      Optional<StorageEntry> hybrid, Optional<StorageEntry> parentChunks,
      Map<String, Object> additionalProperties) {
    this.text = text;
    this.semantic = semantic;
    this.hybrid = hybrid;
    this.parentChunks = parentChunks;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("text")
  public Optional<StorageEntry> getText() {
    return text;
  }

  @JsonProperty("semantic")
  public Optional<StorageEntry> getSemantic() {
    return semantic;
  }

  @JsonProperty("hybrid")
  public Optional<StorageEntry> getHybrid() {
    return hybrid;
  }

  @JsonProperty("parentChunks")
  public Optional<StorageEntry> getParentChunks() {
    return parentChunks;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof StorageBytesSearch && equalTo((StorageBytesSearch) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(StorageBytesSearch other) {
    return text.equals(other.text) && semantic.equals(other.semantic) && hybrid.equals(other.hybrid) && parentChunks.equals(other.parentChunks);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.text, this.semantic, this.hybrid, this.parentChunks);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<StorageEntry> text = Optional.empty();

    private Optional<StorageEntry> semantic = Optional.empty();

    private Optional<StorageEntry> hybrid = Optional.empty();

    private Optional<StorageEntry> parentChunks = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(StorageBytesSearch other) {
      text(other.getText());
      semantic(other.getSemantic());
      hybrid(other.getHybrid());
      parentChunks(other.getParentChunks());
      return this;
    }

    @JsonSetter(
        value = "text",
        nulls = Nulls.SKIP
    )
    public Builder text(Optional<StorageEntry> text) {
      this.text = text;
      return this;
    }

    public Builder text(StorageEntry text) {
      this.text = Optional.ofNullable(text);
      return this;
    }

    @JsonSetter(
        value = "semantic",
        nulls = Nulls.SKIP
    )
    public Builder semantic(Optional<StorageEntry> semantic) {
      this.semantic = semantic;
      return this;
    }

    public Builder semantic(StorageEntry semantic) {
      this.semantic = Optional.ofNullable(semantic);
      return this;
    }

    @JsonSetter(
        value = "hybrid",
        nulls = Nulls.SKIP
    )
    public Builder hybrid(Optional<StorageEntry> hybrid) {
      this.hybrid = hybrid;
      return this;
    }

    public Builder hybrid(StorageEntry hybrid) {
      this.hybrid = Optional.ofNullable(hybrid);
      return this;
    }

    @JsonSetter(
        value = "parentChunks",
        nulls = Nulls.SKIP
    )
    public Builder parentChunks(Optional<StorageEntry> parentChunks) {
      this.parentChunks = parentChunks;
      return this;
    }

    public Builder parentChunks(StorageEntry parentChunks) {
      this.parentChunks = Optional.ofNullable(parentChunks);
      return this;
    }

    public StorageBytesSearch build() {
      return new StorageBytesSearch(text, semantic, hybrid, parentChunks, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
