/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import ai.vectros.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TenantCredits.Builder.class
)
public final class TenantCredits {
  private final Optional<Long> used;

  private final Optional<Long> usedMilli;

  private final Map<String, Object> additionalProperties;

  private TenantCredits(Optional<Long> used, Optional<Long> usedMilli,
      Map<String, Object> additionalProperties) {
    this.used = used;
    this.usedMilli = usedMilli;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Credits consumed by this environment this period (rounded down)
   */
  @JsonProperty("used")
  public Optional<Long> getUsed() {
    return used;
  }

  /**
   * @return used in milli-credit precision (exact, 1 credit = 1000 milli-credits). Use this for exact accounting — <code>tenants.live.credits.used + tenants.test.credits.used</code> can differ from the account-level <code>credits.used</code> by up to 1 credit due to independent truncation, but <code>live.usedMilli + test.usedMilli == credits.usedMilli</code> always.
   */
  @JsonProperty("usedMilli")
  public Optional<Long> getUsedMilli() {
    return usedMilli;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TenantCredits && equalTo((TenantCredits) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TenantCredits other) {
    return used.equals(other.used) && usedMilli.equals(other.usedMilli);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.used, this.usedMilli);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Long> used = Optional.empty();

    private Optional<Long> usedMilli = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(TenantCredits other) {
      used(other.getUsed());
      usedMilli(other.getUsedMilli());
      return this;
    }

    /**
     * <p>Credits consumed by this environment this period (rounded down)</p>
     */
    @JsonSetter(
        value = "used",
        nulls = Nulls.SKIP
    )
    public Builder used(Optional<Long> used) {
      this.used = used;
      return this;
    }

    public Builder used(Long used) {
      this.used = Optional.ofNullable(used);
      return this;
    }

    /**
     * <p>used in milli-credit precision (exact, 1 credit = 1000 milli-credits). Use this for exact accounting — <code>tenants.live.credits.used + tenants.test.credits.used</code> can differ from the account-level <code>credits.used</code> by up to 1 credit due to independent truncation, but <code>live.usedMilli + test.usedMilli == credits.usedMilli</code> always.</p>
     */
    @JsonSetter(
        value = "usedMilli",
        nulls = Nulls.SKIP
    )
    public Builder usedMilli(Optional<Long> usedMilli) {
      this.usedMilli = usedMilli;
      return this;
    }

    public Builder usedMilli(Long usedMilli) {
      this.usedMilli = Optional.ofNullable(usedMilli);
      return this;
    }

    public TenantCredits build() {
      return new TenantCredits(used, usedMilli, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
