/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class TruncationWarningEventReason {
  public static final TruncationWarningEventReason CONTEXT_WINDOW_BUDGET = new TruncationWarningEventReason(Value.CONTEXT_WINDOW_BUDGET, "context_window_budget");

  private final Value value;

  private final String string;

  TruncationWarningEventReason(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof TruncationWarningEventReason && this.string.equals(((TruncationWarningEventReason) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case CONTEXT_WINDOW_BUDGET:
        return visitor.visitContextWindowBudget();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static TruncationWarningEventReason valueOf(String value) {
    switch (value) {
      case "context_window_budget":
        return CONTEXT_WINDOW_BUDGET;
      default:
        return new TruncationWarningEventReason(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    CONTEXT_WINDOW_BUDGET,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitContextWindowBudget();

    T visitUnknown(String unknownType);
  }
}
