/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class UserExistsResponseStatus {
  public static final UserExistsResponseStatus SUSPENDED = new UserExistsResponseStatus(Value.SUSPENDED, "SUSPENDED");

  public static final UserExistsResponseStatus ACTIVE = new UserExistsResponseStatus(Value.ACTIVE, "ACTIVE");

  public static final UserExistsResponseStatus PENDING = new UserExistsResponseStatus(Value.PENDING, "PENDING");

  private final Value value;

  private final String string;

  UserExistsResponseStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof UserExistsResponseStatus && this.string.equals(((UserExistsResponseStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case SUSPENDED:
        return visitor.visitSuspended();
      case ACTIVE:
        return visitor.visitActive();
      case PENDING:
        return visitor.visitPending();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static UserExistsResponseStatus valueOf(String value) {
    switch (value) {
      case "SUSPENDED":
        return SUSPENDED;
      case "ACTIVE":
        return ACTIVE;
      case "PENDING":
        return PENDING;
      default:
        return new UserExistsResponseStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    ACTIVE,

    SUSPENDED,

    PENDING,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitActive();

    T visitSuspended();

    T visitPending();

    T visitUnknown(String unknownType);
  }
}
