/**
 * This file was auto-generated by Fern from our API Definition.
 */

package ai.vectros.resources.auth;

import ai.vectros.core.ClientOptions;
import ai.vectros.core.RequestOptions;
import ai.vectros.resources.auth.requests.CreateAccessProfileRequest;
import ai.vectros.resources.auth.requests.CreateAppContextRequest;
import ai.vectros.resources.auth.requests.CreateRoleRequest;
import ai.vectros.resources.auth.requests.CreateScopedKeyRequest;
import ai.vectros.resources.auth.requests.DeleteAccessProfileRequest;
import ai.vectros.resources.auth.requests.DeleteAppContextRequest;
import ai.vectros.resources.auth.requests.DeleteRoleRequest;
import ai.vectros.resources.auth.requests.GetAccessLogRequest;
import ai.vectros.resources.auth.requests.GetAccessProfileRequest;
import ai.vectros.resources.auth.requests.GetAccessProfileVersionsRequest;
import ai.vectros.resources.auth.requests.GetAdminLogsRequest;
import ai.vectros.resources.auth.requests.GetAppContextRequest;
import ai.vectros.resources.auth.requests.GetRoleRequest;
import ai.vectros.resources.auth.requests.GetRoleVersionsRequest;
import ai.vectros.resources.auth.requests.GetScopedKeyRequest;
import ai.vectros.resources.auth.requests.GetUsageRequest;
import ai.vectros.resources.auth.requests.ListAccessProfilesRequest;
import ai.vectros.resources.auth.requests.ListAppContextsRequest;
import ai.vectros.resources.auth.requests.ListProfilesForPrincipalRequest;
import ai.vectros.resources.auth.requests.ListRolesRequest;
import ai.vectros.resources.auth.requests.RevokeScopedKeyRequest;
import ai.vectros.resources.auth.requests.TokenRequest;
import ai.vectros.resources.auth.requests.UpdateAccessProfileRequest;
import ai.vectros.resources.auth.requests.UpdateAppContextRequest;
import ai.vectros.resources.auth.requests.UpdateRoleRequest;
import ai.vectros.types.AccessProfilePage;
import ai.vectros.types.AccessProfileRequest;
import ai.vectros.types.AccessProfileResponse;
import ai.vectros.types.AdminLogsResponse;
import ai.vectros.types.AppContextPage;
import ai.vectros.types.AppContextRequest;
import ai.vectros.types.AppContextResponse;
import ai.vectros.types.CreateInviteRequest;
import ai.vectros.types.CreateInviteResponse;
import ai.vectros.types.JwksResponse;
import ai.vectros.types.MintTokenResponse;
import ai.vectros.types.ModelDataVersionPage;
import ai.vectros.types.PingResponse;
import ai.vectros.types.ReadAccessLogPage;
import ai.vectros.types.RolePage;
import ai.vectros.types.RoleRequest;
import ai.vectros.types.RoleResponse;
import ai.vectros.types.ScopedKeyPage;
import ai.vectros.types.ScopedKeyResponse;
import ai.vectros.types.UsageReportResponse;
import java.lang.String;
import java.lang.Void;
import java.util.concurrent.CompletableFuture;

public class AsyncAuthClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawAuthClient rawClient;

  public AsyncAuthClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawAuthClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawAuthClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Returns the platform's JWT signing public key in RFC 7517 JWKS format. Use it with any JWKS-aware JWT library to verify <code>inv_*</code> invite tokens, <code>st_*</code> scoped tokens, and other platform-signed tokens locally, without calling back to the API for each verification. The response carries a one-hour <code>Cache-Control</code>, so cache it and re-fetch roughly hourly rather than on every verification. The <code>kid</code> value changes when the key rotates; re-fetch this document whenever you encounter a token signed with an unknown <code>kid</code>.
   */
  public CompletableFuture<JwksResponse> getJwks() {
    return this.rawClient.getJwks().thenApply(response -> response.body());
  }

  /**
   * Returns the platform's JWT signing public key in RFC 7517 JWKS format. Use it with any JWKS-aware JWT library to verify <code>inv_*</code> invite tokens, <code>st_*</code> scoped tokens, and other platform-signed tokens locally, without calling back to the API for each verification. The response carries a one-hour <code>Cache-Control</code>, so cache it and re-fetch roughly hourly rather than on every verification. The <code>kid</code> value changes when the key rotates; re-fetch this document whenever you encounter a token signed with an unknown <code>kid</code>.
   */
  public CompletableFuture<JwksResponse> getJwks(RequestOptions requestOptions) {
    return this.rawClient.getJwks(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a page of per-subject PHI read-access rows: who read which subject's PHI, when, against which record, and whether any sensitive value was actually revealed in plaintext. Metadata only — never the PHI itself. This is the disclosure-accounting surface from which a covered entity derives its HIPAA §164.528 accounting of disclosures. Provide at least one query axis: a subject (<code>subjectType</code> + <code>subjectId</code>, plus optional <code>clientId</code>) within a <code>contextId</code> for the primary accounting query; <code>resourceId</code> within a <code>contextId</code> for 'who read this record'; <code>callerKeyId</code> for 'what did this credential read' (account-wide forensic); or <code>contextId</code> alone to enumerate a whole context. <code>from</code>/<code>to</code> bound the time window. Results are scoped to your account, derived from your token — never from input. Requires the <code>access-log:r</code> scope.
   */
  public CompletableFuture<ReadAccessLogPage> getAccessLog() {
    return this.rawClient.getAccessLog().thenApply(response -> response.body());
  }

  /**
   * Returns a page of per-subject PHI read-access rows: who read which subject's PHI, when, against which record, and whether any sensitive value was actually revealed in plaintext. Metadata only — never the PHI itself. This is the disclosure-accounting surface from which a covered entity derives its HIPAA §164.528 accounting of disclosures. Provide at least one query axis: a subject (<code>subjectType</code> + <code>subjectId</code>, plus optional <code>clientId</code>) within a <code>contextId</code> for the primary accounting query; <code>resourceId</code> within a <code>contextId</code> for 'who read this record'; <code>callerKeyId</code> for 'what did this credential read' (account-wide forensic); or <code>contextId</code> alone to enumerate a whole context. <code>from</code>/<code>to</code> bound the time window. Results are scoped to your account, derived from your token — never from input. Requires the <code>access-log:r</code> scope.
   */
  public CompletableFuture<ReadAccessLogPage> getAccessLog(RequestOptions requestOptions) {
    return this.rawClient.getAccessLog(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a page of per-subject PHI read-access rows: who read which subject's PHI, when, against which record, and whether any sensitive value was actually revealed in plaintext. Metadata only — never the PHI itself. This is the disclosure-accounting surface from which a covered entity derives its HIPAA §164.528 accounting of disclosures. Provide at least one query axis: a subject (<code>subjectType</code> + <code>subjectId</code>, plus optional <code>clientId</code>) within a <code>contextId</code> for the primary accounting query; <code>resourceId</code> within a <code>contextId</code> for 'who read this record'; <code>callerKeyId</code> for 'what did this credential read' (account-wide forensic); or <code>contextId</code> alone to enumerate a whole context. <code>from</code>/<code>to</code> bound the time window. Results are scoped to your account, derived from your token — never from input. Requires the <code>access-log:r</code> scope.
   */
  public CompletableFuture<ReadAccessLogPage> getAccessLog(GetAccessLogRequest request) {
    return this.rawClient.getAccessLog(request).thenApply(response -> response.body());
  }

  /**
   * Returns a page of per-subject PHI read-access rows: who read which subject's PHI, when, against which record, and whether any sensitive value was actually revealed in plaintext. Metadata only — never the PHI itself. This is the disclosure-accounting surface from which a covered entity derives its HIPAA §164.528 accounting of disclosures. Provide at least one query axis: a subject (<code>subjectType</code> + <code>subjectId</code>, plus optional <code>clientId</code>) within a <code>contextId</code> for the primary accounting query; <code>resourceId</code> within a <code>contextId</code> for 'who read this record'; <code>callerKeyId</code> for 'what did this credential read' (account-wide forensic); or <code>contextId</code> alone to enumerate a whole context. <code>from</code>/<code>to</code> bound the time window. Results are scoped to your account, derived from your token — never from input. Requires the <code>access-log:r</code> scope.
   */
  public CompletableFuture<ReadAccessLogPage> getAccessLog(GetAccessLogRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getAccessLog(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Lists all of your scoped API keys (<code>ssk_*</code>) across both your live and test environments. Revoked keys are excluded. Requires the <code>keys:r</code> scope.
   */
  public CompletableFuture<ScopedKeyPage> listScopedKeys() {
    return this.rawClient.listScopedKeys().thenApply(response -> response.body());
  }

  /**
   * Lists all of your scoped API keys (<code>ssk_*</code>) across both your live and test environments. Revoked keys are excluded. Requires the <code>keys:r</code> scope.
   */
  public CompletableFuture<ScopedKeyPage> listScopedKeys(RequestOptions requestOptions) {
    return this.rawClient.listScopedKeys(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Creates a scoped API key (an <code>ssk_*</code> secret) that inherits its permissions from an existing access profile in your account. The call is idempotent on the combination of tenant, context, user, and key name: re-issuing the same request returns the existing key WITHOUT re-disclosing its raw secret. The raw key is returned ONLY in this response — store it securely, as it cannot be retrieved again. Requires the <code>keys:c</code> scope.
   */
  public CompletableFuture<ScopedKeyResponse> createScopedKey(CreateScopedKeyRequest request) {
    return this.rawClient.createScopedKey(request).thenApply(response -> response.body());
  }

  /**
   * Creates a scoped API key (an <code>ssk_*</code> secret) that inherits its permissions from an existing access profile in your account. The call is idempotent on the combination of tenant, context, user, and key name: re-issuing the same request returns the existing key WITHOUT re-disclosing its raw secret. The raw key is returned ONLY in this response — store it securely, as it cannot be retrieved again. Requires the <code>keys:c</code> scope.
   */
  public CompletableFuture<ScopedKeyResponse> createScopedKey(CreateScopedKeyRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.createScopedKey(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the metadata for a single scoped API key. The raw secret is NOT included — it is only ever returned once, when the key is first created. Requires the <code>keys:r</code> scope.
   */
  public CompletableFuture<ScopedKeyResponse> getScopedKey(String keyId) {
    return this.rawClient.getScopedKey(keyId).thenApply(response -> response.body());
  }

  /**
   * Returns the metadata for a single scoped API key. The raw secret is NOT included — it is only ever returned once, when the key is first created. Requires the <code>keys:r</code> scope.
   */
  public CompletableFuture<ScopedKeyResponse> getScopedKey(String keyId,
      RequestOptions requestOptions) {
    return this.rawClient.getScopedKey(keyId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the metadata for a single scoped API key. The raw secret is NOT included — it is only ever returned once, when the key is first created. Requires the <code>keys:r</code> scope.
   */
  public CompletableFuture<ScopedKeyResponse> getScopedKey(String keyId,
      GetScopedKeyRequest request) {
    return this.rawClient.getScopedKey(keyId, request).thenApply(response -> response.body());
  }

  /**
   * Returns the metadata for a single scoped API key. The raw secret is NOT included — it is only ever returned once, when the key is first created. Requires the <code>keys:r</code> scope.
   */
  public CompletableFuture<ScopedKeyResponse> getScopedKey(String keyId,
      GetScopedKeyRequest request, RequestOptions requestOptions) {
    return this.rawClient.getScopedKey(keyId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Revokes a scoped API key. Its status changes to <code>revoked</code> and it stops working within about 5 minutes, the maximum time authorization is cached. Revocation is permanent. Requires the <code>keys:d</code> scope.
   */
  public CompletableFuture<Void> revokeScopedKey(String keyId) {
    return this.rawClient.revokeScopedKey(keyId).thenApply(response -> response.body());
  }

  /**
   * Revokes a scoped API key. Its status changes to <code>revoked</code> and it stops working within about 5 minutes, the maximum time authorization is cached. Revocation is permanent. Requires the <code>keys:d</code> scope.
   */
  public CompletableFuture<Void> revokeScopedKey(String keyId, RequestOptions requestOptions) {
    return this.rawClient.revokeScopedKey(keyId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Revokes a scoped API key. Its status changes to <code>revoked</code> and it stops working within about 5 minutes, the maximum time authorization is cached. Revocation is permanent. Requires the <code>keys:d</code> scope.
   */
  public CompletableFuture<Void> revokeScopedKey(String keyId, RevokeScopedKeyRequest request) {
    return this.rawClient.revokeScopedKey(keyId, request).thenApply(response -> response.body());
  }

  /**
   * Revokes a scoped API key. Its status changes to <code>revoked</code> and it stops working within about 5 minutes, the maximum time authorization is cached. Revocation is permanent. Requires the <code>keys:d</code> scope.
   */
  public CompletableFuture<Void> revokeScopedKey(String keyId, RevokeScopedKeyRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.revokeScopedKey(keyId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns recent API call logs for your account. Each entry represents one API request; request and response bodies are never logged. <code>startTime</code> and <code>endTime</code> must be ISO-8601 UTC (e.g. <code>2025-01-15T09:00:00Z</code>); <code>endTime</code> defaults to now. Filter by resource, method, key id, or context id, or set <code>errorsOnly</code> to see only failures. Results are scoped to your account, derived from your token — never from input. Requires the <code>logs:r</code> scope.
   */
  public CompletableFuture<AdminLogsResponse> getAdminLogs(GetAdminLogsRequest request) {
    return this.rawClient.getAdminLogs(request).thenApply(response -> response.body());
  }

  /**
   * Returns recent API call logs for your account. Each entry represents one API request; request and response bodies are never logged. <code>startTime</code> and <code>endTime</code> must be ISO-8601 UTC (e.g. <code>2025-01-15T09:00:00Z</code>); <code>endTime</code> defaults to now. Filter by resource, method, key id, or context id, or set <code>errorsOnly</code> to see only failures. Results are scoped to your account, derived from your token — never from input. Requires the <code>logs:r</code> scope.
   */
  public CompletableFuture<AdminLogsResponse> getAdminLogs(GetAdminLogsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getAdminLogs(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the access profiles assigned within the given app context — in effect, who has access to this context and with what scopes. Each profile binds a principal to either a set of inline scopes or a referenced role. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<AccessProfilePage> listAccessProfiles(String contextId) {
    return this.rawClient.listAccessProfiles(contextId).thenApply(response -> response.body());
  }

  /**
   * Returns the access profiles assigned within the given app context — in effect, who has access to this context and with what scopes. Each profile binds a principal to either a set of inline scopes or a referenced role. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<AccessProfilePage> listAccessProfiles(String contextId,
      RequestOptions requestOptions) {
    return this.rawClient.listAccessProfiles(contextId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the access profiles assigned within the given app context — in effect, who has access to this context and with what scopes. Each profile binds a principal to either a set of inline scopes or a referenced role. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<AccessProfilePage> listAccessProfiles(String contextId,
      ListAccessProfilesRequest request) {
    return this.rawClient.listAccessProfiles(contextId, request).thenApply(response -> response.body());
  }

  /**
   * Returns the access profiles assigned within the given app context — in effect, who has access to this context and with what scopes. Each profile binds a principal to either a set of inline scopes or a referenced role. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<AccessProfilePage> listAccessProfiles(String contextId,
      ListAccessProfilesRequest request, RequestOptions requestOptions) {
    return this.rawClient.listAccessProfiles(contextId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Creates a new access profile under the given app context. This call is idempotent by <code>principalId</code>: if a profile with the same <code>principalId</code> already exists, the existing profile is returned (with status 200) instead of creating a duplicate. The response's <code>created</code> field (and the HTTP status — 201 when created, 200 when an existing profile was returned) tells the two apart. To overwrite an existing profile's <code>scopes</code>/<code>roleId</code>, <code>identityOverrides</code>, and <code>status</code> instead of returning it unchanged, set <code>?upsert=true</code> (this also requires the <code>profiles:u</code> scope). You must provide exactly one of <code>scopes</code> (an inline list of scopes) or <code>roleId</code> (a reference to a role); supplying both, or neither, is rejected. <code>identityOverrides</code> may set only <code>orgId</code> and <code>clientId</code>; any other key (including the account identifier or <code>userId</code>) is rejected. If you use a scoped credential, the profile's effective scopes may not exceed your own; a root API key (<code>sk_</code>) is exempt. Requires the <code>profiles:c</code> scope.
   */
  public CompletableFuture<AccessProfileResponse> createAccessProfile(String contextId,
      AccessProfileRequest body) {
    return this.rawClient.createAccessProfile(contextId, body).thenApply(response -> response.body());
  }

  /**
   * Creates a new access profile under the given app context. This call is idempotent by <code>principalId</code>: if a profile with the same <code>principalId</code> already exists, the existing profile is returned (with status 200) instead of creating a duplicate. The response's <code>created</code> field (and the HTTP status — 201 when created, 200 when an existing profile was returned) tells the two apart. To overwrite an existing profile's <code>scopes</code>/<code>roleId</code>, <code>identityOverrides</code>, and <code>status</code> instead of returning it unchanged, set <code>?upsert=true</code> (this also requires the <code>profiles:u</code> scope). You must provide exactly one of <code>scopes</code> (an inline list of scopes) or <code>roleId</code> (a reference to a role); supplying both, or neither, is rejected. <code>identityOverrides</code> may set only <code>orgId</code> and <code>clientId</code>; any other key (including the account identifier or <code>userId</code>) is rejected. If you use a scoped credential, the profile's effective scopes may not exceed your own; a root API key (<code>sk_</code>) is exempt. Requires the <code>profiles:c</code> scope.
   */
  public CompletableFuture<AccessProfileResponse> createAccessProfile(String contextId,
      AccessProfileRequest body, RequestOptions requestOptions) {
    return this.rawClient.createAccessProfile(contextId, body, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Creates a new access profile under the given app context. This call is idempotent by <code>principalId</code>: if a profile with the same <code>principalId</code> already exists, the existing profile is returned (with status 200) instead of creating a duplicate. The response's <code>created</code> field (and the HTTP status — 201 when created, 200 when an existing profile was returned) tells the two apart. To overwrite an existing profile's <code>scopes</code>/<code>roleId</code>, <code>identityOverrides</code>, and <code>status</code> instead of returning it unchanged, set <code>?upsert=true</code> (this also requires the <code>profiles:u</code> scope). You must provide exactly one of <code>scopes</code> (an inline list of scopes) or <code>roleId</code> (a reference to a role); supplying both, or neither, is rejected. <code>identityOverrides</code> may set only <code>orgId</code> and <code>clientId</code>; any other key (including the account identifier or <code>userId</code>) is rejected. If you use a scoped credential, the profile's effective scopes may not exceed your own; a root API key (<code>sk_</code>) is exempt. Requires the <code>profiles:c</code> scope.
   */
  public CompletableFuture<AccessProfileResponse> createAccessProfile(String contextId,
      CreateAccessProfileRequest request) {
    return this.rawClient.createAccessProfile(contextId, request).thenApply(response -> response.body());
  }

  /**
   * Creates a new access profile under the given app context. This call is idempotent by <code>principalId</code>: if a profile with the same <code>principalId</code> already exists, the existing profile is returned (with status 200) instead of creating a duplicate. The response's <code>created</code> field (and the HTTP status — 201 when created, 200 when an existing profile was returned) tells the two apart. To overwrite an existing profile's <code>scopes</code>/<code>roleId</code>, <code>identityOverrides</code>, and <code>status</code> instead of returning it unchanged, set <code>?upsert=true</code> (this also requires the <code>profiles:u</code> scope). You must provide exactly one of <code>scopes</code> (an inline list of scopes) or <code>roleId</code> (a reference to a role); supplying both, or neither, is rejected. <code>identityOverrides</code> may set only <code>orgId</code> and <code>clientId</code>; any other key (including the account identifier or <code>userId</code>) is rejected. If you use a scoped credential, the profile's effective scopes may not exceed your own; a root API key (<code>sk_</code>) is exempt. Requires the <code>profiles:c</code> scope.
   */
  public CompletableFuture<AccessProfileResponse> createAccessProfile(String contextId,
      CreateAccessProfileRequest request, RequestOptions requestOptions) {
    return this.rawClient.createAccessProfile(contextId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a paginated list of the app contexts in your account. Each app context is a namespace that groups the access profiles and roles for one of your applications. Requires the <code>app-contexts:r</code> scope.
   */
  public CompletableFuture<AppContextPage> listAppContexts() {
    return this.rawClient.listAppContexts().thenApply(response -> response.body());
  }

  /**
   * Returns a paginated list of the app contexts in your account. Each app context is a namespace that groups the access profiles and roles for one of your applications. Requires the <code>app-contexts:r</code> scope.
   */
  public CompletableFuture<AppContextPage> listAppContexts(RequestOptions requestOptions) {
    return this.rawClient.listAppContexts(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a paginated list of the app contexts in your account. Each app context is a namespace that groups the access profiles and roles for one of your applications. Requires the <code>app-contexts:r</code> scope.
   */
  public CompletableFuture<AppContextPage> listAppContexts(ListAppContextsRequest request) {
    return this.rawClient.listAppContexts(request).thenApply(response -> response.body());
  }

  /**
   * Returns a paginated list of the app contexts in your account. Each app context is a namespace that groups the access profiles and roles for one of your applications. Requires the <code>app-contexts:r</code> scope.
   */
  public CompletableFuture<AppContextPage> listAppContexts(ListAppContextsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.listAppContexts(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Creates a new app context. This call is idempotent by <code>contextId</code>: if an app context with the same <code>contextId</code> already exists, the existing app context is returned (with status 200) instead of creating a duplicate. The response's <code>created</code> field (and the HTTP status — 201 when created, 200 when an existing context was returned) tells the two apart. To overwrite an existing context's <code>name</code>/<code>description</code> instead of returning it unchanged, set <code>?upsert=true</code> (this also requires the <code>app-contexts:u</code> scope). The reserved <code>contextId</code> value <code>vectros-admin</code> cannot be created through this endpoint; it is provisioned automatically for your account. Requires the <code>app-contexts:c</code> scope.
   */
  public CompletableFuture<AppContextResponse> createAppContext(AppContextRequest body) {
    return this.rawClient.createAppContext(body).thenApply(response -> response.body());
  }

  /**
   * Creates a new app context. This call is idempotent by <code>contextId</code>: if an app context with the same <code>contextId</code> already exists, the existing app context is returned (with status 200) instead of creating a duplicate. The response's <code>created</code> field (and the HTTP status — 201 when created, 200 when an existing context was returned) tells the two apart. To overwrite an existing context's <code>name</code>/<code>description</code> instead of returning it unchanged, set <code>?upsert=true</code> (this also requires the <code>app-contexts:u</code> scope). The reserved <code>contextId</code> value <code>vectros-admin</code> cannot be created through this endpoint; it is provisioned automatically for your account. Requires the <code>app-contexts:c</code> scope.
   */
  public CompletableFuture<AppContextResponse> createAppContext(AppContextRequest body,
      RequestOptions requestOptions) {
    return this.rawClient.createAppContext(body, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Creates a new app context. This call is idempotent by <code>contextId</code>: if an app context with the same <code>contextId</code> already exists, the existing app context is returned (with status 200) instead of creating a duplicate. The response's <code>created</code> field (and the HTTP status — 201 when created, 200 when an existing context was returned) tells the two apart. To overwrite an existing context's <code>name</code>/<code>description</code> instead of returning it unchanged, set <code>?upsert=true</code> (this also requires the <code>app-contexts:u</code> scope). The reserved <code>contextId</code> value <code>vectros-admin</code> cannot be created through this endpoint; it is provisioned automatically for your account. Requires the <code>app-contexts:c</code> scope.
   */
  public CompletableFuture<AppContextResponse> createAppContext(CreateAppContextRequest request) {
    return this.rawClient.createAppContext(request).thenApply(response -> response.body());
  }

  /**
   * Creates a new app context. This call is idempotent by <code>contextId</code>: if an app context with the same <code>contextId</code> already exists, the existing app context is returned (with status 200) instead of creating a duplicate. The response's <code>created</code> field (and the HTTP status — 201 when created, 200 when an existing context was returned) tells the two apart. To overwrite an existing context's <code>name</code>/<code>description</code> instead of returning it unchanged, set <code>?upsert=true</code> (this also requires the <code>app-contexts:u</code> scope). The reserved <code>contextId</code> value <code>vectros-admin</code> cannot be created through this endpoint; it is provisioned automatically for your account. Requires the <code>app-contexts:c</code> scope.
   */
  public CompletableFuture<AppContextResponse> createAppContext(CreateAppContextRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.createAppContext(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the roles defined under the given app context. A role is a reusable, named bundle of scopes that access profiles can reference instead of listing scopes inline. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<RolePage> listRoles(String contextId) {
    return this.rawClient.listRoles(contextId).thenApply(response -> response.body());
  }

  /**
   * Returns the roles defined under the given app context. A role is a reusable, named bundle of scopes that access profiles can reference instead of listing scopes inline. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<RolePage> listRoles(String contextId, RequestOptions requestOptions) {
    return this.rawClient.listRoles(contextId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the roles defined under the given app context. A role is a reusable, named bundle of scopes that access profiles can reference instead of listing scopes inline. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<RolePage> listRoles(String contextId, ListRolesRequest request) {
    return this.rawClient.listRoles(contextId, request).thenApply(response -> response.body());
  }

  /**
   * Returns the roles defined under the given app context. A role is a reusable, named bundle of scopes that access profiles can reference instead of listing scopes inline. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<RolePage> listRoles(String contextId, ListRolesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.listRoles(contextId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Creates a new role under the given app context. This call is idempotent by <code>roleId</code>: if a role with the same <code>roleId</code> already exists, the existing role is returned (with status 200) instead of creating a duplicate. The response's <code>created</code> field (and the HTTP status — 201 when created, 200 when an existing role was returned) tells the two apart. To overwrite an existing role's <code>name</code>/<code>description</code>/<code>scopes</code> instead of returning it unchanged, set <code>?upsert=true</code> (this also requires the <code>profiles:u</code> scope). If you use a scoped credential, the role's scopes may not exceed your own; a root API key (<code>sk_</code>) is exempt. Requires the <code>profiles:c</code> scope.
   */
  public CompletableFuture<RoleResponse> createRole(String contextId, RoleRequest body) {
    return this.rawClient.createRole(contextId, body).thenApply(response -> response.body());
  }

  /**
   * Creates a new role under the given app context. This call is idempotent by <code>roleId</code>: if a role with the same <code>roleId</code> already exists, the existing role is returned (with status 200) instead of creating a duplicate. The response's <code>created</code> field (and the HTTP status — 201 when created, 200 when an existing role was returned) tells the two apart. To overwrite an existing role's <code>name</code>/<code>description</code>/<code>scopes</code> instead of returning it unchanged, set <code>?upsert=true</code> (this also requires the <code>profiles:u</code> scope). If you use a scoped credential, the role's scopes may not exceed your own; a root API key (<code>sk_</code>) is exempt. Requires the <code>profiles:c</code> scope.
   */
  public CompletableFuture<RoleResponse> createRole(String contextId, RoleRequest body,
      RequestOptions requestOptions) {
    return this.rawClient.createRole(contextId, body, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Creates a new role under the given app context. This call is idempotent by <code>roleId</code>: if a role with the same <code>roleId</code> already exists, the existing role is returned (with status 200) instead of creating a duplicate. The response's <code>created</code> field (and the HTTP status — 201 when created, 200 when an existing role was returned) tells the two apart. To overwrite an existing role's <code>name</code>/<code>description</code>/<code>scopes</code> instead of returning it unchanged, set <code>?upsert=true</code> (this also requires the <code>profiles:u</code> scope). If you use a scoped credential, the role's scopes may not exceed your own; a root API key (<code>sk_</code>) is exempt. Requires the <code>profiles:c</code> scope.
   */
  public CompletableFuture<RoleResponse> createRole(String contextId, CreateRoleRequest request) {
    return this.rawClient.createRole(contextId, request).thenApply(response -> response.body());
  }

  /**
   * Creates a new role under the given app context. This call is idempotent by <code>roleId</code>: if a role with the same <code>roleId</code> already exists, the existing role is returned (with status 200) instead of creating a duplicate. The response's <code>created</code> field (and the HTTP status — 201 when created, 200 when an existing role was returned) tells the two apart. To overwrite an existing role's <code>name</code>/<code>description</code>/<code>scopes</code> instead of returning it unchanged, set <code>?upsert=true</code> (this also requires the <code>profiles:u</code> scope). If you use a scoped credential, the role's scopes may not exceed your own; a root API key (<code>sk_</code>) is exempt. Requires the <code>profiles:c</code> scope.
   */
  public CompletableFuture<RoleResponse> createRole(String contextId, CreateRoleRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.createRole(contextId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a single access profile by its <code>principalId</code> within the given app context. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<AccessProfileResponse> getAccessProfile(String contextId,
      String principalId) {
    return this.rawClient.getAccessProfile(contextId, principalId).thenApply(response -> response.body());
  }

  /**
   * Returns a single access profile by its <code>principalId</code> within the given app context. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<AccessProfileResponse> getAccessProfile(String contextId,
      String principalId, RequestOptions requestOptions) {
    return this.rawClient.getAccessProfile(contextId, principalId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a single access profile by its <code>principalId</code> within the given app context. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<AccessProfileResponse> getAccessProfile(String contextId,
      String principalId, GetAccessProfileRequest request) {
    return this.rawClient.getAccessProfile(contextId, principalId, request).thenApply(response -> response.body());
  }

  /**
   * Returns a single access profile by its <code>principalId</code> within the given app context. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<AccessProfileResponse> getAccessProfile(String contextId,
      String principalId, GetAccessProfileRequest request, RequestOptions requestOptions) {
    return this.rawClient.getAccessProfile(contextId, principalId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Updates an access profile. This is a partial update: any field you omit (or send as null) keeps its existing value. A profile must reference either inline <code>scopes</code> or a <code>roleId</code>, never both — so setting <code>scopes</code> clears any <code>roleId</code>, and setting <code>roleId</code> clears any inline <code>scopes</code>. The <code>contextId</code> and <code>principalId</code> are immutable. Status changes (for example active to suspended) take effect within about five minutes. If you use a scoped credential, the profile's effective scopes may not exceed your own; a root API key (<code>sk_</code>) is exempt. Requires the <code>profiles:u</code> scope.
   */
  public CompletableFuture<AccessProfileResponse> updateAccessProfile(String contextId,
      String principalId, UpdateAccessProfileRequest request) {
    return this.rawClient.updateAccessProfile(contextId, principalId, request).thenApply(response -> response.body());
  }

  /**
   * Updates an access profile. This is a partial update: any field you omit (or send as null) keeps its existing value. A profile must reference either inline <code>scopes</code> or a <code>roleId</code>, never both — so setting <code>scopes</code> clears any <code>roleId</code>, and setting <code>roleId</code> clears any inline <code>scopes</code>. The <code>contextId</code> and <code>principalId</code> are immutable. Status changes (for example active to suspended) take effect within about five minutes. If you use a scoped credential, the profile's effective scopes may not exceed your own; a root API key (<code>sk_</code>) is exempt. Requires the <code>profiles:u</code> scope.
   */
  public CompletableFuture<AccessProfileResponse> updateAccessProfile(String contextId,
      String principalId, UpdateAccessProfileRequest request, RequestOptions requestOptions) {
    return this.rawClient.updateAccessProfile(contextId, principalId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Deletes an access profile. Within about five minutes (the access-profile cache lifetime), token minting for this principal in this context will be denied. Requires the <code>profiles:d</code> scope.
   */
  public CompletableFuture<Void> deleteAccessProfile(String contextId, String principalId) {
    return this.rawClient.deleteAccessProfile(contextId, principalId).thenApply(response -> response.body());
  }

  /**
   * Deletes an access profile. Within about five minutes (the access-profile cache lifetime), token minting for this principal in this context will be denied. Requires the <code>profiles:d</code> scope.
   */
  public CompletableFuture<Void> deleteAccessProfile(String contextId, String principalId,
      RequestOptions requestOptions) {
    return this.rawClient.deleteAccessProfile(contextId, principalId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Deletes an access profile. Within about five minutes (the access-profile cache lifetime), token minting for this principal in this context will be denied. Requires the <code>profiles:d</code> scope.
   */
  public CompletableFuture<Void> deleteAccessProfile(String contextId, String principalId,
      DeleteAccessProfileRequest request) {
    return this.rawClient.deleteAccessProfile(contextId, principalId, request).thenApply(response -> response.body());
  }

  /**
   * Deletes an access profile. Within about five minutes (the access-profile cache lifetime), token minting for this principal in this context will be denied. Requires the <code>profiles:d</code> scope.
   */
  public CompletableFuture<Void> deleteAccessProfile(String contextId, String principalId,
      DeleteAccessProfileRequest request, RequestOptions requestOptions) {
    return this.rawClient.deleteAccessProfile(contextId, principalId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a single app context by its <code>contextId</code>. Requires the <code>app-contexts:r</code> scope.
   */
  public CompletableFuture<AppContextResponse> getAppContext(String contextId) {
    return this.rawClient.getAppContext(contextId).thenApply(response -> response.body());
  }

  /**
   * Returns a single app context by its <code>contextId</code>. Requires the <code>app-contexts:r</code> scope.
   */
  public CompletableFuture<AppContextResponse> getAppContext(String contextId,
      RequestOptions requestOptions) {
    return this.rawClient.getAppContext(contextId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a single app context by its <code>contextId</code>. Requires the <code>app-contexts:r</code> scope.
   */
  public CompletableFuture<AppContextResponse> getAppContext(String contextId,
      GetAppContextRequest request) {
    return this.rawClient.getAppContext(contextId, request).thenApply(response -> response.body());
  }

  /**
   * Returns a single app context by its <code>contextId</code>. Requires the <code>app-contexts:r</code> scope.
   */
  public CompletableFuture<AppContextResponse> getAppContext(String contextId,
      GetAppContextRequest request, RequestOptions requestOptions) {
    return this.rawClient.getAppContext(contextId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Updates the name and/or description of an app context. This is a partial update: any field you omit (or send as null) keeps its existing value. The <code>contextId</code> is immutable and is taken from the URL path, so any <code>contextId</code> in the request body is ignored. Requires the <code>app-contexts:u</code> scope.
   */
  public CompletableFuture<AppContextResponse> updateAppContext(String contextId,
      UpdateAppContextRequest request) {
    return this.rawClient.updateAppContext(contextId, request).thenApply(response -> response.body());
  }

  /**
   * Updates the name and/or description of an app context. This is a partial update: any field you omit (or send as null) keeps its existing value. The <code>contextId</code> is immutable and is taken from the URL path, so any <code>contextId</code> in the request body is ignored. Requires the <code>app-contexts:u</code> scope.
   */
  public CompletableFuture<AppContextResponse> updateAppContext(String contextId,
      UpdateAppContextRequest request, RequestOptions requestOptions) {
    return this.rawClient.updateAppContext(contextId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes an app context and everything in it — every record, document, folder, schema, role, and access profile belonging to the context. This is irreversible. The deletion runs asynchronously: the call returns 202 immediately and the context's data drains in the background. Poll the context's <code>status</code> field to observe when the teardown completes (<code>purging</code> while draining, then <code>deleted</code>). To guard against accidental deletion, you must echo the contextId back in the <code>confirm</code> query parameter (<code>?confirm={contextId}</code>). The reserved <code>default</code> and <code>vectros-admin</code> contexts cannot be deleted. This operation requires a root API key (one beginning with <code>sk_</code>): no scoped credential, not even one with full wildcard (<code>*</code>) scope, can trigger this teardown.
   */
  public CompletableFuture<Void> deleteAppContext(String contextId) {
    return this.rawClient.deleteAppContext(contextId).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes an app context and everything in it — every record, document, folder, schema, role, and access profile belonging to the context. This is irreversible. The deletion runs asynchronously: the call returns 202 immediately and the context's data drains in the background. Poll the context's <code>status</code> field to observe when the teardown completes (<code>purging</code> while draining, then <code>deleted</code>). To guard against accidental deletion, you must echo the contextId back in the <code>confirm</code> query parameter (<code>?confirm={contextId}</code>). The reserved <code>default</code> and <code>vectros-admin</code> contexts cannot be deleted. This operation requires a root API key (one beginning with <code>sk_</code>): no scoped credential, not even one with full wildcard (<code>*</code>) scope, can trigger this teardown.
   */
  public CompletableFuture<Void> deleteAppContext(String contextId, RequestOptions requestOptions) {
    return this.rawClient.deleteAppContext(contextId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes an app context and everything in it — every record, document, folder, schema, role, and access profile belonging to the context. This is irreversible. The deletion runs asynchronously: the call returns 202 immediately and the context's data drains in the background. Poll the context's <code>status</code> field to observe when the teardown completes (<code>purging</code> while draining, then <code>deleted</code>). To guard against accidental deletion, you must echo the contextId back in the <code>confirm</code> query parameter (<code>?confirm={contextId}</code>). The reserved <code>default</code> and <code>vectros-admin</code> contexts cannot be deleted. This operation requires a root API key (one beginning with <code>sk_</code>): no scoped credential, not even one with full wildcard (<code>*</code>) scope, can trigger this teardown.
   */
  public CompletableFuture<Void> deleteAppContext(String contextId,
      DeleteAppContextRequest request) {
    return this.rawClient.deleteAppContext(contextId, request).thenApply(response -> response.body());
  }

  /**
   * Permanently deletes an app context and everything in it — every record, document, folder, schema, role, and access profile belonging to the context. This is irreversible. The deletion runs asynchronously: the call returns 202 immediately and the context's data drains in the background. Poll the context's <code>status</code> field to observe when the teardown completes (<code>purging</code> while draining, then <code>deleted</code>). To guard against accidental deletion, you must echo the contextId back in the <code>confirm</code> query parameter (<code>?confirm={contextId}</code>). The reserved <code>default</code> and <code>vectros-admin</code> contexts cannot be deleted. This operation requires a root API key (one beginning with <code>sk_</code>): no scoped credential, not even one with full wildcard (<code>*</code>) scope, can trigger this teardown.
   */
  public CompletableFuture<Void> deleteAppContext(String contextId, DeleteAppContextRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.deleteAppContext(contextId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a single role by its <code>roleId</code> within the given app context. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<RoleResponse> getRole(String contextId, String roleId) {
    return this.rawClient.getRole(contextId, roleId).thenApply(response -> response.body());
  }

  /**
   * Returns a single role by its <code>roleId</code> within the given app context. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<RoleResponse> getRole(String contextId, String roleId,
      RequestOptions requestOptions) {
    return this.rawClient.getRole(contextId, roleId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns a single role by its <code>roleId</code> within the given app context. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<RoleResponse> getRole(String contextId, String roleId,
      GetRoleRequest request) {
    return this.rawClient.getRole(contextId, roleId, request).thenApply(response -> response.body());
  }

  /**
   * Returns a single role by its <code>roleId</code> within the given app context. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<RoleResponse> getRole(String contextId, String roleId,
      GetRoleRequest request, RequestOptions requestOptions) {
    return this.rawClient.getRole(contextId, roleId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Updates a role. This is a partial update: any field you omit (or send as null) keeps its existing value. The <code>roleId</code> and <code>contextId</code> are immutable. Scope changes take effect for access profiles that reference this role within about five minutes. If you use a scoped credential, the role's scopes may not exceed your own; a root API key (<code>sk_</code>) is exempt. Requires the <code>profiles:u</code> scope.
   */
  public CompletableFuture<RoleResponse> updateRole(String contextId, String roleId,
      UpdateRoleRequest request) {
    return this.rawClient.updateRole(contextId, roleId, request).thenApply(response -> response.body());
  }

  /**
   * Updates a role. This is a partial update: any field you omit (or send as null) keeps its existing value. The <code>roleId</code> and <code>contextId</code> are immutable. Scope changes take effect for access profiles that reference this role within about five minutes. If you use a scoped credential, the role's scopes may not exceed your own; a root API key (<code>sk_</code>) is exempt. Requires the <code>profiles:u</code> scope.
   */
  public CompletableFuture<RoleResponse> updateRole(String contextId, String roleId,
      UpdateRoleRequest request, RequestOptions requestOptions) {
    return this.rawClient.updateRole(contextId, roleId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Deletes a role. A role that is still referenced by one or more access profiles cannot be deleted: the request is rejected with 409. Reassign or delete those profiles first, then retry. Requires the <code>profiles:d</code> scope.
   */
  public CompletableFuture<Void> deleteRole(String contextId, String roleId) {
    return this.rawClient.deleteRole(contextId, roleId).thenApply(response -> response.body());
  }

  /**
   * Deletes a role. A role that is still referenced by one or more access profiles cannot be deleted: the request is rejected with 409. Reassign or delete those profiles first, then retry. Requires the <code>profiles:d</code> scope.
   */
  public CompletableFuture<Void> deleteRole(String contextId, String roleId,
      RequestOptions requestOptions) {
    return this.rawClient.deleteRole(contextId, roleId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Deletes a role. A role that is still referenced by one or more access profiles cannot be deleted: the request is rejected with 409. Reassign or delete those profiles first, then retry. Requires the <code>profiles:d</code> scope.
   */
  public CompletableFuture<Void> deleteRole(String contextId, String roleId,
      DeleteRoleRequest request) {
    return this.rawClient.deleteRole(contextId, roleId, request).thenApply(response -> response.body());
  }

  /**
   * Deletes a role. A role that is still referenced by one or more access profiles cannot be deleted: the request is rejected with 409. Reassign or delete those profiles first, then retry. Requires the <code>profiles:d</code> scope.
   */
  public CompletableFuture<Void> deleteRole(String contextId, String roleId,
      DeleteRoleRequest request, RequestOptions requestOptions) {
    return this.rawClient.deleteRole(contextId, roleId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes (create, update, and delete events) for an access profile, most recent first. Version history is always recorded for every access profile; there is no setting to turn it off. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getAccessProfileVersions(String contextId,
      String principalId) {
    return this.rawClient.getAccessProfileVersions(contextId, principalId).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes (create, update, and delete events) for an access profile, most recent first. Version history is always recorded for every access profile; there is no setting to turn it off. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getAccessProfileVersions(String contextId,
      String principalId, RequestOptions requestOptions) {
    return this.rawClient.getAccessProfileVersions(contextId, principalId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes (create, update, and delete events) for an access profile, most recent first. Version history is always recorded for every access profile; there is no setting to turn it off. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getAccessProfileVersions(String contextId,
      String principalId, GetAccessProfileVersionsRequest request) {
    return this.rawClient.getAccessProfileVersions(contextId, principalId, request).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes (create, update, and delete events) for an access profile, most recent first. Version history is always recorded for every access profile; there is no setting to turn it off. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getAccessProfileVersions(String contextId,
      String principalId, GetAccessProfileVersionsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getAccessProfileVersions(contextId, principalId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes (create, update, and delete events) for a role, newest first. Version history is always recorded for every role; there is no setting to turn it off. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getRoleVersions(String contextId, String roleId) {
    return this.rawClient.getRoleVersions(contextId, roleId).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes (create, update, and delete events) for a role, newest first. Version history is always recorded for every role; there is no setting to turn it off. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getRoleVersions(String contextId, String roleId,
      RequestOptions requestOptions) {
    return this.rawClient.getRoleVersions(contextId, roleId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes (create, update, and delete events) for a role, newest first. Version history is always recorded for every role; there is no setting to turn it off. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getRoleVersions(String contextId, String roleId,
      GetRoleVersionsRequest request) {
    return this.rawClient.getRoleVersions(contextId, roleId, request).thenApply(response -> response.body());
  }

  /**
   * Returns the audit trail of changes (create, update, and delete events) for a role, newest first. Version history is always recorded for every role; there is no setting to turn it off. Results are paginated. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<ModelDataVersionPage> getRoleVersions(String contextId, String roleId,
      GetRoleVersionsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getRoleVersions(contextId, roleId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns full usage detail for the requested calendar month, broken down by category (search, documents, and records) with per-category credit estimates and a split between your live and test environments. Defaults to the current month when <code>year</code> and <code>month</code> are omitted. Requires the <code>billing:r</code> scope on scoped tokens; API keys always have access.
   */
  public CompletableFuture<UsageReportResponse> getUsage() {
    return this.rawClient.getUsage().thenApply(response -> response.body());
  }

  /**
   * Returns full usage detail for the requested calendar month, broken down by category (search, documents, and records) with per-category credit estimates and a split between your live and test environments. Defaults to the current month when <code>year</code> and <code>month</code> are omitted. Requires the <code>billing:r</code> scope on scoped tokens; API keys always have access.
   */
  public CompletableFuture<UsageReportResponse> getUsage(RequestOptions requestOptions) {
    return this.rawClient.getUsage(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns full usage detail for the requested calendar month, broken down by category (search, documents, and records) with per-category credit estimates and a split between your live and test environments. Defaults to the current month when <code>year</code> and <code>month</code> are omitted. Requires the <code>billing:r</code> scope on scoped tokens; API keys always have access.
   */
  public CompletableFuture<UsageReportResponse> getUsage(GetUsageRequest request) {
    return this.rawClient.getUsage(request).thenApply(response -> response.body());
  }

  /**
   * Returns full usage detail for the requested calendar month, broken down by category (search, documents, and records) with per-category credit estimates and a split between your live and test environments. Defaults to the current month when <code>year</code> and <code>month</code> are omitted. Requires the <code>billing:r</code> scope on scoped tokens; API keys always have access.
   */
  public CompletableFuture<UsageReportResponse> getUsage(GetUsageRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getUsage(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the identity bound to your credential — your account, principal type, key id, and scope details — so you can confirm who you are authenticated as and that the credential is valid. MCP clients use this to render &quot;signed in as ...&quot; in a chat UI without a separate identity endpoint.
   */
  public CompletableFuture<PingResponse> ping() {
    return this.rawClient.ping().thenApply(response -> response.body());
  }

  /**
   * Returns the identity bound to your credential — your account, principal type, key id, and scope details — so you can confirm who you are authenticated as and that the credential is valid. MCP clients use this to render &quot;signed in as ...&quot; in a chat UI without a separate identity endpoint.
   */
  public CompletableFuture<PingResponse> ping(RequestOptions requestOptions) {
    return this.rawClient.ping(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the access profiles for the given principal across all of your contexts. Use this to answer questions like &quot;which apps does this user have access to?&quot; — for example, to build a member-access summary. Results are confined to your account. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<AccessProfilePage> listProfilesForPrincipal(String principalId) {
    return this.rawClient.listProfilesForPrincipal(principalId).thenApply(response -> response.body());
  }

  /**
   * Returns the access profiles for the given principal across all of your contexts. Use this to answer questions like &quot;which apps does this user have access to?&quot; — for example, to build a member-access summary. Results are confined to your account. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<AccessProfilePage> listProfilesForPrincipal(String principalId,
      RequestOptions requestOptions) {
    return this.rawClient.listProfilesForPrincipal(principalId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the access profiles for the given principal across all of your contexts. Use this to answer questions like &quot;which apps does this user have access to?&quot; — for example, to build a member-access summary. Results are confined to your account. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<AccessProfilePage> listProfilesForPrincipal(String principalId,
      ListProfilesForPrincipalRequest request) {
    return this.rawClient.listProfilesForPrincipal(principalId, request).thenApply(response -> response.body());
  }

  /**
   * Returns the access profiles for the given principal across all of your contexts. Use this to answer questions like &quot;which apps does this user have access to?&quot; — for example, to build a member-access summary. Results are confined to your account. Requires the <code>profiles:r</code> scope.
   */
  public CompletableFuture<AccessProfilePage> listProfilesForPrincipal(String principalId,
      ListProfilesForPrincipalRequest request, RequestOptions requestOptions) {
    return this.rawClient.listProfilesForPrincipal(principalId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Creates a short-lived JWT bearer token restricted to specific actions and, optionally, to a particular user, organization, or client. Use this to hand a narrowly-scoped credential to a browser or downstream service so it never sees your root API key. Only callable with a root API key (<code>sk_*</code>).
   */
  public CompletableFuture<MintTokenResponse> mintToken(TokenRequest request) {
    return this.rawClient.mintToken(request).thenApply(response -> response.body());
  }

  /**
   * Creates a short-lived JWT bearer token restricted to specific actions and, optionally, to a particular user, organization, or client. Use this to hand a narrowly-scoped credential to a browser or downstream service so it never sees your root API key. Only callable with a root API key (<code>sk_*</code>).
   */
  public CompletableFuture<MintTokenResponse> mintToken(TokenRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.mintToken(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Invite a new member to one of your app contexts by email. Creates a pending user with a pre-resolved access profile (their permissions on accept) and signs an invitation token. This call is idempotent on the combination of context and email: re-inviting the same email in the same context rotates the token and resends the invitation rather than creating a duplicate. Returns HTTP 201 on a new invite or a successful resend. Returns 409 if that email already belongs to an active or suspended member of the app context, or already has an identity elsewhere in your account (an email can currently belong to only one tenant per account, i.e. your test and live environments cannot share an email). When <code>sendEmail</code> is false, the response includes the raw token and a ready-to-use accept link so you can deliver the invitation through your own email provider. Requires the <code>admin:users</code> scope.
   */
  public CompletableFuture<CreateInviteResponse> createInvite(CreateInviteRequest request) {
    return this.rawClient.createInvite(request).thenApply(response -> response.body());
  }

  /**
   * Invite a new member to one of your app contexts by email. Creates a pending user with a pre-resolved access profile (their permissions on accept) and signs an invitation token. This call is idempotent on the combination of context and email: re-inviting the same email in the same context rotates the token and resends the invitation rather than creating a duplicate. Returns HTTP 201 on a new invite or a successful resend. Returns 409 if that email already belongs to an active or suspended member of the app context, or already has an identity elsewhere in your account (an email can currently belong to only one tenant per account, i.e. your test and live environments cannot share an email). When <code>sendEmail</code> is false, the response includes the raw token and a ready-to-use accept link so you can deliver the invitation through your own email provider. Requires the <code>admin:users</code> scope.
   */
  public CompletableFuture<CreateInviteResponse> createInvite(CreateInviteRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.createInvite(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Resend an outstanding invitation, identified by its email and app context. Rotates the invitation token and extends its expiry, then (when <code>sendEmail</code> is true) re-delivers the email. Rotating the token invalidates any previously issued link for this invitation, so only the newest link works. The invitee's pending permissions are left unchanged. Requires the <code>admin:users</code> scope.
   */
  public CompletableFuture<CreateInviteResponse> resendInvite(CreateInviteRequest request) {
    return this.rawClient.resendInvite(request).thenApply(response -> response.body());
  }

  /**
   * Resend an outstanding invitation, identified by its email and app context. Rotates the invitation token and extends its expiry, then (when <code>sendEmail</code> is true) re-delivers the email. Rotating the token invalidates any previously issued link for this invitation, so only the newest link works. The invitee's pending permissions are left unchanged. Requires the <code>admin:users</code> scope.
   */
  public CompletableFuture<CreateInviteResponse> resendInvite(CreateInviteRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.resendInvite(request, requestOptions).thenApply(response -> response.body());
  }
}
